Repository apollographql/apollo-client, pull requests merged in 2019-11, with the labels that each got.

#5514 Testing utilities cleanup
  config/jest.config.js
  config/rollup.config.js
  src/__mocks__/mockLinks.ts
  src/__tests__/ApolloClient.ts
  src/__tests__/client.ts
  src/__tests__/fetchMore.ts
  src/__tests__/graphqlSubscriptions.ts
  src/__tests__/local-state/general.ts
  src/__tests__/local-state/resolvers.ts
  src/__tests__/mutationResults.ts
  src/__tests__/optimistic.ts
  src/__tests__/subscribeToMore.ts
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/__tests__/readFromStore.ts
  src/core/__tests__/ObservableQuery.ts
  src/core/__tests__/QueryManager/index.ts
  src/core/__tests__/QueryManager/links.ts
  src/core/__tests__/QueryManager/live.ts
  src/core/__tests__/QueryManager/multiple-results.ts
  src/core/__tests__/QueryManager/recycler.ts
  src/core/__tests__/fetchPolicies.ts
  src/core/__tests__/scheduler.ts
  src/link/core/ApolloLink.ts
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/__tests__/useMutation.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/__tests__/useSubscription.test.tsx
  src/react/testing/__tests__/README.md
  src/react/testing/index.ts
  src/react/testing/mocks/types.ts
  src/react/testing/utils/wait.ts
  src/utilities/codemods/mockLinkRejection.ts
  src/utilities/testing/__tests__/stripSymbols.ts
  src/utilities/testing/index.ts
  src/utilities/testing/itAsync.ts
  src/utilities/testing/mocking/MockedProvider.tsx
  src/utilities/testing/mocking/mockClient.ts
  src/utilities/testing/mocking/mockFetch.ts
  src/utilities/testing/mocking/mockLink.ts
  src/utilities/testing/mocking/mockQueryManager.ts
  src/utilities/testing/mocking/mockSubscriptionLink.ts
  src/utilities/testing/mocking/mockWatchQuery.ts
  src/utilities/testing/observableToPromise.ts
  src/utilities/testing/stripSymbols.ts
  src/utilities/testing/subscribeAndCount.ts
  src/utilities/testing/wrap.ts
  tsconfig.json
Labels: :bulb: idea, 👩‍🏭 refactor, 📦 bundle size, 🛠 tooling

#5561 Use CommonJS to deduplicate React context copies
  config/rollup.config.js
  package-lock.json
  package.json
  src/index.ts
  src/react/context/ApolloConsumer.tsx
  src/react/context/ApolloContext.ts
  src/react/context/ApolloProvider.tsx
  src/react/context/__tests__/ApolloConsumer.test.tsx
  src/react/context/__tests__/ApolloProvider.test.tsx
  src/react/data/MutationData.ts
  src/react/data/OperationData.ts
  src/react/data/QueryData.ts
  src/react/data/SubscriptionData.ts
  src/react/hooks/__tests__/useApolloClient.test.tsx
  src/react/hooks/useApolloClient.ts
  src/react/hooks/useMutation.ts
  src/react/hooks/useSubscription.ts
  src/react/hooks/utils/useBaseQuery.ts
Labels: 🐞 bug

#5565 Avoid reading from cache in ObservableQuery#getCurrentResult.
  src/core/ObservableQuery.ts
  src/core/QueryManager.ts
  src/core/__tests__/ObservableQuery.ts
  src/react/data/QueryData.ts
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/utils/useBaseQuery.ts
Labels: :bulb: idea, :fried_egg: breaking change, 👩‍🏭 refactor, 🧞‍♂️ enhancement

#5541 [V3] Create @apollo/client/core bundle
  CHANGELOG.md
  config/prepareDist.js
  config/rollup.config.js
  package-lock.json
  package.json
  src/core/index.ts
  src/index.ts
  src/react/data/MutationData.ts
  src/react/data/QueryData.ts
  src/react/data/SubscriptionData.ts
  src/react/hooks/utils/useBaseQuery.ts
  src/react/index.ts
  src/react/ssr/RenderPromises.ts
  src/react/types/types.ts
Labels: :christmas_tree: dependencies, 👩‍🏭 refactor, 📦 bundle size, 🧞‍♂️ enhancement

#5577 Wire up the `@apollo/client/cache` entry point
  CHANGELOG.md
  config/prepareDist.js
  src/cache/index.ts
  src/core/index.ts
  src/react/context/ApolloConsumer.tsx
  src/react/context/ApolloContext.ts
  src/react/context/ApolloProvider.tsx
  src/react/context/__tests__/ApolloConsumer.test.tsx
  src/react/context/__tests__/ApolloProvider.test.tsx
  src/react/hooks/__tests__/useApolloClient.test.tsx
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/__tests__/useMutation.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/__tests__/useSubscription.test.tsx
  src/react/hooks/useApolloClient.ts
  src/react/hooks/useMutation.ts
  src/react/hooks/useSubscription.ts
  src/react/hooks/utils/useBaseQuery.ts
  src/react/hooks/utils/useDeepMemo.ts
  src/react/react.ts
Labels: :christmas_tree: dependencies, 📦 bundle size, 🧞‍♂️ enhancement

#5591 Fix closing html tag
  docs/source/development-testing/static-typing.md
Labels: 📝 documentation

#5603 Never merge fields in cache unless objects have same identity.
  CHANGELOG.md
  src/__tests__/__snapshots__/ApolloClient.ts.snap
  src/__tests__/local-state/export.ts
  src/__tests__/local-state/general.ts
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/__tests__/writeToStore.ts
  src/cache/inmemory/writeToStore.ts
  src/core/__tests__/QueryManager/index.ts
Labels: 🐞 bug, 🚨 high-priority, 🧞‍♂️ enhancement, 🧩 implementation-detail

#5617 Finer-grained InMemoryCache result caching.
  src/cache/inmemory/__tests__/diffAgainstStore.ts
  src/cache/inmemory/__tests__/optimistic.ts
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/__tests__/recordingCache.ts
  src/cache/inmemory/entityCache.ts
  src/cache/inmemory/helpers.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/readFromStore.ts
  src/cache/inmemory/types.ts
  src/cache/inmemory/writeToStore.ts
  src/core/__tests__/QueryManager/links.ts
Labels: :bulb: idea, :racehorse: performance, 👩‍🏭 refactor, 🧞‍♂️ enhancement, 🧩 implementation-detail

#5618 Rename EntityCache to EntityStore.
  src/cache/inmemory/__tests__/diffAgainstStore.ts
  src/cache/inmemory/__tests__/entityStore.ts
  src/cache/inmemory/__tests__/readFromStore.ts
  src/cache/inmemory/__tests__/recordingCache.ts
  src/cache/inmemory/__tests__/roundtrip.ts
  src/cache/inmemory/__tests__/writeToStore.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/readFromStore.ts
  src/cache/inmemory/writeToStore.ts
Labels: 🧩 implementation-detail

#5619 Deep-freeze existing values passed to read and merge functions.
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/readFromStore.ts
  src/cache/inmemory/writeToStore.ts
Labels: 🛠 tooling, 🧞‍♂️ enhancement, 🧩 implementation-detail

#5610 Add InMemoryCache import to introductory example code
  docs/source/get-started.mdx
Labels: 📝 documentation
