Repository apollographql/apollo-client, pull requests merged in 2019-09, with the labels that each got.

#5270 [docs] Remove references to an exported compose function in react-apollo.md
  docs/source/api/react-apollo.md
Labels: 📝 documentation

#5252 Update Authentication recipe with apollo-boost example
  docs/source/recipes/authentication.mdx
Labels: 📝 documentation

#5249 Fix misleading README
  packages/apollo-boost/README.md
Labels: 📝 documentation

#5223 Update error-handling.mdx
  docs/source/features/error-handling.mdx
Labels: 📝 documentation

#5181 Update queries.mdx
  docs/source/essentials/queries.mdx
Labels: 📝 documentation

#5151 Update Get Started documentation to have full file when connecting to component
  docs/source/essentials/get-started.mdx
Labels: 📝 documentation

#5138 Docs: Changed inline gql tag to variables.
  docs/source/essentials/get-started.mdx
Labels: 📝 documentation

#5129 Fix cacheRedirects href
  docs/source/essentials/get-started.mdx
Labels: 📝 documentation

#5104 docs: update react-native.md with missing package installs
  docs/source/recipes/react-native.md
Labels: 📝 documentation

#5064 docs: update link to Boost config options
  packages/apollo-boost/README.md
Labels: 📝 documentation

#5018 Fix typo
  docs/source/advanced/caching.md
Labels: 📝 documentation

#5004 Fix(#4577) update Bypassing the cache section
  docs/source/advanced/caching.md
  packages/apollo-client/src/core/QueryManager.ts
Labels: 📝 documentation

#4928 docs: added Svelte to the integration list
  docs/source/integrations.md
Labels: 📝 documentation

#4902 docs: fix typo in react-apollo.md
  docs/source/api/react-apollo.md
Labels: 📝 documentation

#4895 add warning to caching.md
  docs/source/advanced/caching.md
Labels: 📝 documentation

#4876 Update performance.md
  docs/source/recipes/performance.mdx
Labels: 📝 documentation

#4759 Update optimistic-ui.md
  docs/source/features/optimistic-ui.mdx
Labels: 📝 documentation

#4744 mention function as result in a mocked query
  docs/source/recipes/testing.mdx
Labels: 📝 documentation

#4718 Update MockedProvider docs
  docs/source/recipes/testing.mdx
Labels: 📝 documentation

#5310 Implement InMemoryCache garbage collection and eviction.
  CHANGELOG.md
  package.json
  src/cache/core/cache.ts
  src/cache/core/types/Cache.ts
  src/cache/inmemory/__tests__/entityCache.ts
  src/cache/inmemory/__tests__/writeToStore.ts
  src/cache/inmemory/entityCache.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/types.ts
  src/cache/inmemory/writeToStore.ts
Labels: 🛫 in-progress, 🧞‍♂️ enhancement

#5320 Stop calling addTypenameToDocument before InMemoryCache reads/writes.
  src/__tests__/__snapshots__/ApolloClient.ts.snap
  src/cache/inmemory/__tests__/__snapshots__/cache.ts.snap
  src/cache/inmemory/__tests__/diffAgainstStore.ts
  src/cache/inmemory/__tests__/readFromStore.ts
  src/cache/inmemory/__tests__/writeToStore.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/readFromStore.ts
  src/cache/inmemory/writeToStore.ts
  src/utilities/storeUtils.ts
Labels: 🧞‍♂️ enhancement

#5325 Update optimism to use lighter-weight dependency API in EntityCache.
  package-lock.json
  package.json
  src/cache/inmemory/entityCache.ts
Labels: :bulb: idea, :christmas_tree: dependencies, :racehorse: performance, 🧞‍♂️ enhancement

#5250 WIP: Docset switcher
  docs/gatsby-config.js
  docs/package-lock.json
  docs/package.json
Labels: 📝 documentation

#5321 Revamp documentation information architecture
  docs/gatsby-config.js
  docs/source/advanced/update-store.md
  docs/source/api/apollo-client.mdx
  docs/source/api/react-apollo.md
  docs/source/api/react-hoc.mdx
  docs/source/api/react-hooks.mdx
  docs/source/api/react-ssr.md
  docs/source/caching/cache-configuration.md
  docs/source/caching/cache-interaction.md
  docs/source/data/error-handling.mdx
  docs/source/data/fragments.md
  docs/source/data/local-state.mdx
  docs/source/data/mutations.mdx
  docs/source/data/pagination.mdx
  docs/source/data/queries.mdx
  docs/source/data/subscriptions.mdx
  docs/source/development-testing/client-schema-mocking.mdx
  docs/source/development-testing/developer-tooling.md
  docs/source/development-testing/recompose.md
  docs/source/development-testing/static-typing.md
  docs/source/development-testing/testing.mdx
  docs/source/get-started.mdx
  docs/source/index.mdx
  docs/source/integrations/integrations.md
  docs/source/integrations/meteor.md
  docs/source/integrations/react-native.md
  docs/source/integrations/webpack.md
  docs/source/migrating/boost-migration.md
  docs/source/migrating/hooks-migration.md
  docs/source/networking/authentication.mdx
  docs/source/networking/network-layer.md
  docs/source/performance/babel.md
  docs/source/performance/optimistic-ui.mdx
  docs/source/performance/performance.mdx
  docs/source/performance/server-side-rendering.mdx
  docs/source/recipes/simple-example.md
  docs/source/why-apollo.mdx
  docs/static/_redirects
Labels: 🛫 in-progress
