Repository apollographql/apollo-client, pull requests merged in 2019-12, with the labels that each got.

#5639 Adjust `fetchData` to accommodate #5565
  src/react/data/QueryData.ts
Labels: 👩‍🏭 refactor, 🧞‍♂️ enhancement

#5643 Support eviction of specific entity fields.
  package.json
  src/__tests__/__snapshots__/client.ts.snap
  src/cache/core/cache.ts
  src/cache/inmemory/__tests__/entityStore.ts
  src/cache/inmemory/__tests__/readFromStore.ts
  src/cache/inmemory/__tests__/writeToStore.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/helpers.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/types.ts
Labels: :bulb: idea, 🧞‍♂️ enhancement, 🧩 implementation-detail

#5644 Stop paying attention to previousResult in InMemoryCache.
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/readFromStore.ts
Labels: :fried_egg: breaking change, :racehorse: performance, 🧞‍♂️ enhancement

#5648 Improve optimistic result caching by limiting cache key diversity.
  src/cache/inmemory/__tests__/optimistic.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/readFromStore.ts
Labels: :racehorse: performance, 🐞 bug, 🧞‍♂️ enhancement, 🧩 implementation-detail

#5651 Allow getFieldValue to read from foreign Reference objects.
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/readFromStore.ts
Labels: :bulb: idea, 🧞‍♂️ enhancement

#5667 Storage and invalidation for custom field read functions.
  package.json
  src/cache/inmemory/__tests__/diffAgainstStore.ts
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/readFromStore.ts
  src/core/__tests__/QueryManager/links.ts
Labels: :bulb: idea, 🧞‍♂️ enhancement

#5680 Assume keyArgs:false when read or merge functions are defined.
  package.json
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/writeToStore.ts
Labels: :bulb: idea, 🧞‍♂️ enhancement, 🧩 implementation-detail

#5684 Fully eliminate the concept of heuristic fragment matching.
  package.json
  src/cache/inmemory/__tests__/diffAgainstStore.ts
  src/cache/inmemory/__tests__/entityStore.ts
  src/cache/inmemory/__tests__/roundtrip.ts
  src/cache/inmemory/__tests__/writeToStore.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/readFromStore.ts
  src/cache/inmemory/writeToStore.ts
  src/utilities/graphql/storeUtils.ts
Labels: :fried_egg: breaking change, :racehorse: performance, 🧞‍♂️ enhancement

#5513 Correct docs typo use `dataIdFromObject` not `dataObjectFromId`
  docs/source/data/local-state.mdx
Labels: 📝 documentation

#5683 Export utilities via @apollo/client/utilities
  CHANGELOG.md
  config/prepareDist.js
  config/rollup.config.js
  src/cache/inmemory/entityStore.ts
  src/core/LocalState.ts
  src/core/ObservableQuery.ts
  src/data/queries.ts
  src/react/data/MutationData.ts
  src/react/data/OperationData.ts
  src/react/data/QueryData.ts
  src/react/data/SubscriptionData.ts
  src/react/hooks/utils/useDeepMemo.ts
  src/utilities/common/__tests__/isEqual.ts
  src/utilities/common/capitalizeFirstLetter.ts
  src/utilities/common/isEqual.ts
  src/utilities/graphql/__tests__/getFromAST.ts
  src/utilities/graphql/__tests__/transform.ts
  src/utilities/graphql/directives.ts
  src/utilities/graphql/getFromAST.ts
  src/utilities/graphql/storeUtils.ts
  src/utilities/graphql/transform.ts
  src/utilities/index.ts
  src/utilities/testing/mocking/mockLink.ts
Labels: :bulb: idea, 👩‍🏭 refactor, 📦 bundle size, 🧞‍♂️ enhancement

#5712 Refactor custom field merge function processing.
  src/cache/inmemory/helpers.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/writeToStore.ts
Labels: 👩‍🏭 refactor, 🧞‍♂️ enhancement, 🧩 implementation-detail
