Repository apollographql/apollo-client, pull requests merged in 2019-10, with the labels that each got.

#5442 Properly merge StoreObjects in StoreWriter#processSelectionSet.
  src/cache/inmemory/writeToStore.ts
Labels: 🐞 bug, 🧞‍♂️ enhancement

#5451 `react` and `graphql-tag` dependency adjustments
  config/rollup.config.js
  docs/source/api/react-apollo.md
  docs/source/api/react-hoc.mdx
  docs/source/api/react-hooks.mdx
  docs/source/caching/cache-interaction.md
  docs/source/data/fragments.md
  docs/source/data/local-state.mdx
  docs/source/data/queries.mdx
  docs/source/data/subscriptions.mdx
  docs/source/development-testing/recompose.md
  docs/source/development-testing/static-typing.md
  docs/source/development-testing/testing.mdx
  docs/source/features/caching.md
  docs/source/get-started.mdx
  package-lock.json
  package.json
  src/index.ts
Labels: :christmas_tree: dependencies, 👩‍🏭 refactor, 📝 documentation, 📦 bundle size, 🧞‍♂️ enhancement

#5474 Promise-ify all tests, and pass a Promise reject function to mocking utilities.
  src/__mocks__/mockLinks.ts
  src/__mocks__/mockQueryManager.ts
  src/__mocks__/mockWatchQuery.ts
  src/__tests__/__snapshots__/client.ts.snap
  src/__tests__/client.ts
  src/__tests__/fetchMore.ts
  src/__tests__/local-state/general.ts
  src/__tests__/local-state/resolvers.ts
  src/__tests__/mutationResults.ts
  src/__tests__/optimistic.ts
  src/__tests__/subscribeToMore.ts
  src/__tests__/utils/itAsync.ts
  src/__tests__/utils/subscribeAndCount.ts
  src/__tests__/utils/wrap.ts
  src/core/__tests__/ObservableQuery.ts
  src/core/__tests__/QueryManager/index.ts
  src/core/__tests__/fetchPolicies.ts
  src/core/__tests__/scheduler.ts
  src/react/hooks/__tests__/useMutation.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/testing/mocks/MockedProvider.tsx
  src/react/testing/mocks/mockLink.ts
  src/react/testing/utils/createClient.ts
Labels: ⛑ TypeScript, 👩‍🏭 refactor, 🛠 tooling, 🧞‍♂️ enhancement

#5479 Content edit on Fragments article
  docs/source/data/fragments.md
Labels: 📝 documentation

#5443 Enable customization of cache normalization behavior.
  docs/source/caching/cache-configuration.md
  docs/source/caching/cache-interaction.md
  package.json
  src/__tests__/ApolloClient.ts
  src/__tests__/__snapshots__/ApolloClient.ts.snap
  src/__tests__/__snapshots__/client.ts.snap
  src/__tests__/client.ts
  src/__tests__/mutationResults.ts
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/__tests__/diffAgainstStore.ts
  src/cache/inmemory/__tests__/entityCache.ts
  src/cache/inmemory/__tests__/optimistic.ts
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/__tests__/readFromStore.ts
  src/cache/inmemory/__tests__/roundtrip.ts
  src/cache/inmemory/__tests__/writeToStore.ts
  src/cache/inmemory/fragments.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/readFromStore.ts
  src/cache/inmemory/types.ts
  src/cache/inmemory/writeToStore.ts
  src/core/__tests__/QueryManager/links.ts
  src/index.ts
  src/utilities/common/__tests__/mergeDeep.ts
  src/utilities/common/mergeDeep.ts
  src/utilities/graphql/storeUtils.ts
Labels: :bulb: idea, ⛑ TypeScript, 👩‍🏭 refactor, 💬 discussion, 📝 documentation, 🛫 in-progress, 🧞‍♂️ enhancement

#5484 Avoid modifying actual cache while recording optimistic transactions.
  src/__tests__/optimistic.ts
  src/cache/inmemory/__tests__/optimistic.ts
  src/cache/inmemory/inMemoryCache.ts
  src/core/QueryManager.ts
Labels: :bulb: idea, :fried_egg: breaking change, 🧞‍♂️ enhancement, 🧩 implementation-detail

#5501 Revert recent useQuery onCompleted changes
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/utils/useBaseQuery.ts
Labels: ✔ confirmed, 🐞 bug

#5506 Provide toReference helper function in FieldFunctionOptions.
  src/cache/inmemory/__tests__/diffAgainstStore.ts
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/__tests__/writeToStore.ts
  src/cache/inmemory/policies.ts
  src/core/__tests__/QueryManager/links.ts
Labels: 🧞‍♂️ enhancement

#5519 Add cache eviction docs
  docs/source/api/core.mdx
  docs/source/api/react-apollo.md
  docs/source/api/react-hoc.mdx
  docs/source/api/react-hooks.mdx
  docs/source/api/react-ssr.md
  docs/source/api/react-testing.md
  docs/source/caching/cache-configuration.md
  docs/source/caching/cache-interaction.md
  docs/source/data/fragments.md
  docs/source/data/local-state.mdx
  docs/source/data/mutations.mdx
  docs/source/data/pagination.mdx
  docs/source/data/queries.mdx
  docs/source/data/subscriptions.mdx
  docs/source/development-testing/static-typing.md
  docs/source/features/caching.md
  docs/source/get-started.mdx
  docs/source/index.mdx
  docs/source/integrations/meteor.md
  docs/source/integrations/react-native.md
  docs/source/performance/optimistic-ui.mdx
  docs/source/performance/performance.mdx
  docs/source/performance/server-side-rendering.mdx
  docs/source/why-apollo.mdx
Labels: 🛫 in-progress
