Repository apollographql/apollo-client, pull requests merged in 2019-01, with the labels that each got.

#4213 Docs: Include GET_TODOS in essentials/mutations
  CHANGELOG.md
  docs/source/essentials/mutations.md
Labels: docs

#4319 Avoid copying entire cache on each optimistic read.
  CHANGELOG.md
  packages/apollo-cache-inmemory/src/__tests__/recordingCache.ts
  packages/apollo-cache-inmemory/src/inMemoryCache.ts
  packages/apollo-cache-inmemory/src/index.ts
  packages/apollo-cache-inmemory/src/objectCache.ts
  packages/apollo-cache-inmemory/src/recordingCache.ts
  packages/apollo-client/src/__tests__/client.ts
Labels: perf

#4234 Trim low-hanging fruit to reduce bundle sizes (part 1 of issue #4324).
  CHANGELOG.md
  config/rollup.config.js
  config/tsconfig.base.json
  package.json
  packages/apollo-cache-inmemory/src/__tests__/__snapshots__/mapCache.ts.snap
  packages/apollo-cache-inmemory/src/__tests__/__snapshots__/roundtrip.ts.snap
  packages/apollo-cache-inmemory/src/__tests__/__snapshots__/writeToStore.ts.snap
  packages/apollo-cache-inmemory/src/__tests__/queryKeyMaker.ts
  packages/apollo-cache-inmemory/src/queryKeyMaker.ts
  packages/apollo-cache-inmemory/src/readFromStore.ts
  packages/apollo-cache-inmemory/src/writeToStore.ts
  packages/apollo-client/rollup.config.js
  packages/apollo-client/src/ApolloClient.ts
  packages/apollo-client/src/__mocks__/mockLinks.ts
  packages/apollo-client/src/__tests__/client.ts
  packages/apollo-client/src/core/ObservableQuery.ts
  packages/apollo-client/src/core/QueryManager.ts
  packages/apollo-client/src/core/__tests__/scheduler.ts
  packages/apollo-client/src/data/mutations.ts
  packages/apollo-client/src/data/queries.ts
  packages/apollo-client/src/index.ts
  packages/apollo-client/src/scheduler/scheduler.ts
  packages/apollo-client/tsconfig.test.json
  packages/apollo-utilities/src/directives.ts
Labels: discussion, help-wanted, high-priority, in-progress, pull-requests-encouraged, refactor, tooling

#4331 Update optimism to use its new TypeScript declarations.
  CHANGELOG.md
  packages/apollo-cache-inmemory/package-lock.json
  packages/apollo-cache-inmemory/package.json
  packages/apollo-cache-inmemory/src/cacheKeys.ts
  packages/apollo-cache-inmemory/src/declarations.d.ts
  packages/apollo-cache-inmemory/src/depTrackingCache.ts
  packages/apollo-cache-inmemory/src/inMemoryCache.ts
  packages/apollo-cache-inmemory/src/readFromStore.ts
Labels: dependencies, typescript

#4041 QueryManager, fix "invalidate" -> "invalidated" typo i think.
  CHANGELOG.md
  packages/apollo-client/src/core/QueryManager.ts
Labels: bug, confirmed, help-wanted
