Repository apollographql/apollo-client, pull requests merged in 2019-05, with the labels that each got.

#4716 Add recipe for mocking with client schemas
  docs/gatsby-config.js
  docs/source/assets/client-mocking/cli-clientcheck.png
  docs/source/assets/client-mocking/devtools-clientstate.png
  docs/source/assets/client-mocking/vscode-autocomplete.png
  docs/source/assets/client-mocking/vscode-errors.png
  docs/source/assets/client-mocking/vscode-typeinfo.png
  docs/source/recipes/client-schema-mocking.md
Labels: 📝 docs

#4586 Release 2.6.0
  CHANGELOG.md
  lerna.json
  package-lock.json
  package.json
  packages/apollo-boost/package-lock.json
  packages/apollo-boost/package.json
  packages/apollo-cache-inmemory/package-lock.json
  packages/apollo-cache-inmemory/package.json
  packages/apollo-cache-inmemory/src/__tests__/roundtrip.ts
  packages/apollo-cache-inmemory/src/cacheKeys.ts
  packages/apollo-cache-inmemory/src/depTrackingCache.ts
  packages/apollo-cache-inmemory/src/inMemoryCache.ts
  packages/apollo-cache-inmemory/src/readFromStore.ts
  packages/apollo-cache/package.json
  packages/apollo-client/package-lock.json
  packages/apollo-client/package.json
  packages/apollo-client/src/ApolloClient.ts
  packages/apollo-client/src/__tests__/client.ts
  packages/apollo-client/src/__tests__/fetchMore.ts
  packages/apollo-client/src/__tests__/graphqlSubscriptions.ts
  packages/apollo-client/src/__tests__/local-state/__snapshots__/general.ts.snap
  packages/apollo-client/src/__tests__/local-state/export.ts
  packages/apollo-client/src/__tests__/local-state/general.ts
  packages/apollo-client/src/__tests__/local-state/resolvers.ts
  packages/apollo-client/src/core/LocalState.ts
  packages/apollo-client/src/core/ObservableQuery.ts
  packages/apollo-client/src/core/QueryManager.ts
  packages/apollo-client/src/core/__tests__/ObservableQuery.ts
  packages/apollo-client/src/core/__tests__/QueryManager/index.ts
  packages/apollo-client/src/core/__tests__/fetchPolicies.ts
  packages/apollo-client/src/core/watchQueryOptions.ts
  packages/apollo-client/src/data/mutations.ts
  packages/apollo-client/src/data/queries.ts
  packages/apollo-client/src/data/store.ts
  packages/apollo-client/src/errors/ApolloError.ts
  packages/apollo-client/src/index.ts
  packages/apollo-client/src/util/arrays.ts
  packages/apollo-client/src/util/observables.ts
  packages/apollo-client/src/util/subscribeAndCount.ts
  packages/apollo-client/src/version.ts
  packages/apollo-utilities/package-lock.json
  packages/apollo-utilities/package.json
  packages/apollo-utilities/src/index.ts
  packages/apollo-utilities/src/transform.ts
  packages/apollo-utilities/src/util/canUse.ts
  packages/graphql-anywhere/package.json
Labels: 👩‍🏭 refactor, 📦 bundle size, 😍 pull-requests-welcome, 🛫 in-progress

#4856 Enable typecheck cache apollo-cache-inmemory tests
  packages/apollo-cache-inmemory/src/__tests__/cache.ts
  packages/apollo-cache-inmemory/src/__tests__/diffAgainstStore.ts
  packages/apollo-cache-inmemory/src/__tests__/fragmentMatcher.ts
  packages/apollo-cache-inmemory/src/__tests__/readFromStore.ts
  packages/apollo-cache-inmemory/src/__tests__/roundtrip.ts
  packages/apollo-cache-inmemory/src/__tests__/writeToStore.ts
  packages/apollo-cache-inmemory/tsconfig.json
Labels: ⛑ TypeScript, 🛠 tooling, 🧞‍♂️ enhancement
