Repository apollographql/apollo-client, pull requests merged in 2020-02, with the labels that each got.

#5900 export fromPromise
  src/core/index.ts
Labels: 🧞‍♂️ enhancement

#5904 Simplify EntityStore#merge.
  src/cache/inmemory/__tests__/__snapshots__/roundtrip.ts.snap
  src/cache/inmemory/__tests__/__snapshots__/writeToStore.ts.snap
  src/cache/inmemory/__tests__/writeToStore.ts
  src/cache/inmemory/entityStore.ts
  src/core/__tests__/QueryManager/index.ts
Labels: :bulb: idea, 👩‍🏭 refactor, 📦 bundle size, 🧞‍♂️ enhancement

#5913 Allow keyArgs functions to return KeySpecifier arrays.
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/policies.ts
Labels: :bulb: idea, 🧞‍♂️ enhancement, 🧪 tests

#5914 Allow keyFields functions to return KeySpecifier arrays.
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/policies.ts
Labels: 🔠 quick-and-easy, 🧞‍♂️ enhancement

#5919 Simplify makeFieldValueGetter.
  src/cache/inmemory/__tests__/entityStore.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/readFromStore.ts
  src/cache/inmemory/types.ts
  src/cache/inmemory/writeToStore.ts
Labels: :bulb: idea, 👩‍🏭 refactor, 🧞‍♂️ enhancement, 🧩 implementation-detail

#5906 Remove graphql-tag type overrides
  package-lock.json
  package.json
  src/types/graphql-tag.d.ts
  tsconfig.json
Labels: :christmas_tree: dependencies, ⛑ TypeScript, 👩‍🏭 refactor

#5925 AC3 apollo-link-rest doc updates
  docs/source/api/link/apollo-link-rest.md
  docs/source/data/local-state.mdx
  docs/source/migrating/apollo-client-3-migration.md
Labels: dependencies, 📝 documentation, 🛫 in-progress

#5909 Implement InMemoryCache#modify for surgically transforming fields.
  CHANGELOG.md
  src/cache/core/types/Cache.ts
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/readFromStore.ts
  src/cache/inmemory/types.ts
  src/cache/inmemory/writeToStore.ts
Labels: :bulb: idea, 🧞‍♂️ enhancement, 🧩 implementation-detail

#5930 Allow cache.{read,write}Query to take options.id.
  CHANGELOG.md
  src/__tests__/client.ts
  src/cache/core/cache.ts
  src/cache/core/types/DataProxy.ts
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/readFromStore.ts
Labels: :bulb: idea, 🧞‍♂️ enhancement

#5946 Prevent @client @export from firing unnecessary network requests
  CHANGELOG.md
  package.json
  src/__tests__/local-state/export.ts
  src/core/ObservableQuery.ts
Labels: 🐞 bug

#5935 tighten QueryTuple to indicate observable fields may be absent
  src/react/data/QueryData.ts
  src/react/types/types.ts
Labels: ⛑ TypeScript

#5948 Various cache read and write performance optimizations.
  CHANGELOG.md
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/readFromStore.ts
  src/cache/inmemory/writeToStore.ts
  src/utilities/common/mergeDeep.ts
  src/utilities/graphql/directives.ts
Labels: :bulb: idea, :racehorse: performance, 🧞‍♂️ enhancement

#5956 Mutate update function DataProxy/ApolloCache changes
  CHANGELOG.md
  src/cache/core/cache.ts
  src/cache/core/types/common.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/helpers.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/readFromStore.ts
  src/cache/inmemory/types.ts
  src/cache/inmemory/writeToStore.ts
  src/core/QueryManager.ts
  src/core/watchQueryOptions.ts
  src/utilities/graphql/storeUtils.ts
Labels: ⛑ TypeScript, 👩‍🏭 refactor, 🧞‍♂️ enhancement

#5962 Remove fixPolyfills.ts, except when bundling for React Native.
  package.json
  src/cache/inmemory/fixPolyfills.native.ts
  src/cache/inmemory/fixPolyfills.ts
Labels: :bulb: idea, 📦 bundle size, 🛠 tooling

#5970 Support toReference(obj, true) to persist obj into cache.
  docs/source/caching/cache-field-behavior.md
  src/cache/core/types/common.ts
  src/cache/inmemory/__tests__/entityStore.ts
  src/cache/inmemory/__tests__/writeToStore.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/readFromStore.ts
  src/cache/inmemory/types.ts
  src/cache/inmemory/writeToStore.ts
  src/core/LocalState.ts
Labels: :bulb: idea, 👩‍🏭 refactor, 🧞‍♂️ enhancement, 🧪 tests

#5974 Add default implementation of ApolloCache#gc
  CHANGELOG.md
  src/cache/core/cache.ts
Labels: 👩‍🏭 refactor, 🧞‍♂️ enhancement

#5973 Eliminate needless custom assign utility.
  src/utilities/common/__tests__/assign.ts
  src/utilities/common/assign.ts
  src/utilities/graphql/getFromAST.ts
Labels: 📦 bundle size, 🔠 quick-and-easy, 🧩 implementation-detail

#5976 Make updating cache.makeVar variables broadcast watches.
  CHANGELOG.md
  src/cache/index.ts
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/inMemoryCache.ts
Labels: 🧞‍♂️ enhancement

#5986 Ensure @client @export variables in watched queries are updated
  CHANGELOG.md
  src/__tests__/local-state/export.ts
  src/core/ObservableQuery.ts
Labels: 🐞 bug

#5982 Prevent `@client` fields from being passed into the Link chain
  CHANGELOG.md
  docs/source/migrating/apollo-client-3-migration.md
  src/ApolloClient.ts
  src/__tests__/ApolloClient.ts
  src/__tests__/__snapshots__/ApolloClient.ts.snap
  src/__tests__/local-state/general.ts
  src/core/LocalState.ts
Labels: :fried_egg: breaking change, 👩‍🏭 refactor
