Repository apollographql/apollo-client, pull requests merged in 2020-05, with the labels that each got.

#6107 Prevent new data re-render attempts during an existing render
  CHANGELOG.md
  package-lock.json
  package.json
  src/react/data/QueryData.ts
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/utils/useBaseQuery.ts
  src/react/types/types.ts
Labels: :christmas_tree: dependencies, ✔ confirmed, 👩‍🏭 refactor, 🧞‍♂️ enhancement

#6160 Add note about `cacheRedirects` being removed
  docs/source/caching/cache-interaction.md
Labels: 📝 documentation

#6143 Add GraphQL to installation instructions + Minor formatting
  docs/source/data/queries.mdx
  docs/source/get-started.mdx
Labels: 📝 documentation

#6138 Add `return null` to code block per the documentation
  docs/source/data/local-state.mdx
Labels: 📝 documentation

#6128 [Docs] Update info about Ember integration with Apollo
  docs/source/integrations/integrations.md
Labels: 📝 documentation

#6194 Supply TData generic removed in GraphQL v15
  src/core/LocalState.ts
  src/core/QueryManager.ts
  src/core/watchQueryOptions.ts
  src/link/core/types.ts
Labels: :christmas_tree: dependencies, ⛑ TypeScript, 🙃 upstream

#6079 Add missing import in documentation
  docs/source/networking/authentication.mdx
Labels: 📝 documentation

#6115 Strict null and typings in tests
  config/jest.config.js
  package-lock.json
  package.json
  src/__tests__/ApolloClient.ts
  src/__tests__/client.ts
  src/__tests__/fetchMore.ts
  src/__tests__/graphqlSubscriptions.ts
  src/__tests__/local-state/general.ts
  src/__tests__/local-state/resolvers.ts
  src/__tests__/mutationResults.ts
  src/__tests__/optimistic.ts
  src/cache/core/__tests__/cache.ts
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/__tests__/diffAgainstStore.ts
  src/cache/inmemory/__tests__/entityStore.ts
  src/cache/inmemory/__tests__/optimistic.ts
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/__tests__/recordingCache.ts
  src/cache/inmemory/__tests__/writeToStore.ts
  src/core/__tests__/LocalState.ts
  src/core/__tests__/ObservableQuery.ts
  src/core/__tests__/QueryManager/index.ts
  src/core/__tests__/QueryManager/links.ts
  src/core/__tests__/QueryManager/live.ts
  src/core/__tests__/QueryManager/multiple-results.ts
  src/core/__tests__/QueryManager/recycler.ts
  src/core/__tests__/fetchPolicies.ts
  src/core/__tests__/scheduler.ts
  src/errors/__tests__/ApolloError.ts
  src/link/core/ApolloLink.ts
  src/link/core/__tests__/ApolloLink.ts
  src/link/http/__tests__/HttpLink.ts
  src/link/http/__tests__/checkFetcher.ts
  src/link/http/__tests__/selectHttpOptionsAndBody.ts
  src/link/utils/__tests__/fromError.ts
  src/link/utils/__tests__/fromPromise.ts
  src/link/utils/__tests__/toPromise.ts
  src/link/utils/__tests__/validateOperation.ts
  src/react/context/__tests__/ApolloProvider.test.tsx
  src/react/hooks/__tests__/useMutation.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/utilities/common/__tests__/cloneDeep.ts
  src/utilities/common/__tests__/mergeDeep.ts
  src/utilities/graphql/__tests__/transform.ts
  src/utilities/testing/mocking/mockLink.ts
Labels: ⛑ TypeScript

#6221 Refactor QueryManager to make better use of observables and enforce fetchPolicy more reliably
  CHANGELOG.md
  src/__tests__/fetchMore.ts
  src/__tests__/mutationResults.ts
  src/__tests__/optimistic.ts
  src/__tests__/subscribeToMore.ts
  src/core/ObservableQuery.ts
  src/core/QueryInfo.ts
  src/core/QueryManager.ts
  src/core/Reobserver.ts
  src/core/__tests__/ObservableQuery.ts
  src/core/__tests__/QueryManager/index.ts
  src/core/__tests__/QueryManager/live.ts
  src/core/__tests__/QueryManager/recycler.ts
  src/core/__tests__/fetchPolicies.ts
  src/core/__tests__/scheduler.ts
  src/core/types.ts
  src/react/hooks/__tests__/useQuery.test.tsx
  src/utilities/observables/Concast.ts
  src/utilities/observables/asyncMap.ts
  src/utilities/observables/iteration.ts
  src/utilities/observables/observables.ts
  src/utilities/testing/mocking/mockLink.ts
  src/utilities/testing/subscribeAndCount.ts
Labels: :bulb: idea, 👩‍🏭 refactor, 🧞‍♂️ enhancement

#6259 Avoid clobbering existing keyFields with undefined value.
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/policies.ts
Labels: 🐞 bug, 🧪 tests

#6265 Remove codecov.io integration
  .circleci/config.yml
  config/codecov.yml
  package-lock.json
  package.json
Labels: :christmas_tree: dependencies, 🛠 tooling, 🧪 tests

#6257 Avoid creating throwaway ObservableQuery for single queries.
  src/ApolloClient.ts
  src/core/ObservableQuery.ts
  src/core/QueryManager.ts
  src/core/__tests__/QueryManager/index.ts
Labels: :bulb: idea, 📦 bundle size, 🧩 implementation-detail

#6119 Changes for read-only cache
  docs/source/caching/cache-interaction.md
Labels: 📝 documentation

#6276 Avoid mutating incoming data in Policies#applyMerges.
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/helpers.ts
  src/cache/inmemory/policies.ts
Labels: 🐞 bug, 🧩 implementation-detail, 🧪 has-tests

#6274 Optimization: skip writing still-fresh result objects back into the EntityStore.
  package-lock.json
  package.json
  src/cache/inmemory/__tests__/writeToStore.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/readFromStore.ts
  src/cache/inmemory/writeToStore.ts
Labels: :bulb: idea, :racehorse: performance, 🧞‍♂️ enhancement, 🧩 implementation-detail

#6015 Add TData generic in MockedResponse
  src/utilities/testing/mocking/mockLink.ts
Labels: ⛑ TypeScript

#6286 [Docs] Added changes to be specific about GraphQL Operations.
  docs/source/api/link/apollo-link-rest.md
  docs/source/api/react/hoc.mdx
  docs/source/api/react/hooks.mdx
  docs/source/caching/cache-configuration.md
  docs/source/caching/cache-interaction.md
  docs/source/data/local-state.mdx
  docs/source/data/queries.mdx
  docs/source/data/subscriptions.mdx
  docs/source/get-started.mdx
  docs/source/why-apollo.mdx
Labels: 📝 documentation

#6287 Adjust defaultDataIdFromObject to set context.keyObject.
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/__tests__/entityStore.ts
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/policies.ts
Labels: 🧞‍♂️ enhancement, 🧩 implementation-detail

#6306 Allow calling readField with ReadFieldOptions.
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/readFromStore.ts
  src/cache/inmemory/writeToStore.ts
  src/utilities/graphql/storeUtils.ts
Labels: :bulb: idea, ⛑ TypeScript, 🧞‍♂️ enhancement

#6288 Allow silencing broadcast for cache update methods.
  CHANGELOG.md
  src/cache/core/__tests__/cache.ts
  src/cache/core/cache.ts
  src/cache/core/types/Cache.ts
  src/cache/core/types/DataProxy.ts
  src/cache/inmemory/__tests__/entityStore.ts
  src/cache/inmemory/__tests__/writeToStore.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/inMemoryCache.ts
Labels: ⛑ TypeScript, 🛫 in-progress, 🧞‍♂️ enhancement, 🧪 has-tests

#6289 Remove experimental cache.modify method.
  CHANGELOG.md
  src/__tests__/client.ts
  src/__tests__/local-state/resolvers.ts
  src/cache/core/cache.ts
  src/cache/core/types/common.ts
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/__tests__/entityStore.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/helpers.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/types.ts
Labels: :fried_egg: breaking change, 💬 discussion

#6280 Replace unfetch/node-fetch recommendation with cross-fetch
  docs/source/api/link/apollo-link-batch-http.mdx
  docs/source/api/link/apollo-link-rest.md
  docs/source/data/fragments.md
  docs/source/networking/advanced-http-networking.md
  package-lock.json
  package.json
  src/link/http/checkFetcher.ts
Labels: :christmas_tree: dependencies, ⛑ TypeScript, 🐞 bug, 📝 documentation

#6350 Reinstate cache.modify.
  CHANGELOG.md
  docs/source/data/local-state.mdx
  src/ApolloClient.ts
  src/__tests__/client.ts
  src/__tests__/local-state/resolvers.ts
  src/cache/core/__tests__/cache.ts
  src/cache/core/cache.ts
  src/cache/core/types/Cache.ts
  src/cache/core/types/DataProxy.ts
  src/cache/core/types/common.ts
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/__tests__/diffAgainstStore.ts
  src/cache/inmemory/__tests__/entityStore.ts
  src/cache/inmemory/__tests__/helpers.ts
  src/cache/inmemory/__tests__/readFromStore.ts
  src/cache/inmemory/__tests__/recordingCache.ts
  src/cache/inmemory/__tests__/roundtrip.ts
  src/cache/inmemory/__tests__/writeToStore.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/readFromStore.ts
  src/cache/inmemory/types.ts
  src/cache/inmemory/writeToStore.ts
Labels: :fried_egg: breaking change, 🧞‍♂️ enhancement

#6353 Fall back to cache-first after cache-and-network or network-only.
  src/core/QueryManager.ts
  src/core/__tests__/ObservableQuery.ts
Labels: 📟 regression, 🧞‍♂️ enhancement

#6362 Hoist cache.modify method declaration to ApolloCache.
  src/cache/core/cache.ts
  src/cache/core/types/Cache.ts
  src/cache/core/types/common.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/types.ts
Labels: ⛑ TypeScript, 👩‍🏭 refactor, 🧞‍♂️ enhancement

#6364 Require Cache.EvictOptions when calling cache.evict.
  CHANGELOG.md
  src/__tests__/client.ts
  src/cache/core/cache.ts
  src/cache/core/types/Cache.ts
  src/cache/inmemory/__tests__/entityStore.ts
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/inMemoryCache.ts
Labels: :fried_egg: breaking change, ⛑ TypeScript

#6365 Stop treating dangling references differently from empty objects.
  src/cache/inmemory/__tests__/entityStore.ts
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/readFromStore.ts
Labels: 🧞‍♂️ enhancement, 🧩 implementation-detail
