Repository apollographql/apollo-client, pull requests merged in 2020-11, with the labels that each got.

#7279 Prevent reactive variables from retaining unwatched caches.
  package.json
  src/__tests__/client.ts
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/reactiveVars.ts
Labels: 🐞 bug, 💸 caching, 🧞‍♂️ enhancement, 🧩 implementation-detail

#7289 Update useMutation docs
  docs/shared/mutation-options.mdx
Labels: 📝 documentation

#7260 Edits to Pagination Core API article
  docs/source/pagination/core-api.mdx
  docs/source/pagination/cursor-based.mdx
  docs/source/pagination/offset-based.mdx
Labels: 💸 caching, 📝 documentation

#7333 Always consider ROOT_{QUERY,MUTATION,...} IDs to be GC roots.
  CHANGELOG.md
  src/cache/inmemory/__tests__/__snapshots__/entityStore.ts.snap
  src/cache/inmemory/__tests__/entityStore.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/writeToStore.ts
Labels: 🐞 bug, 💸 caching, 🛫 in-progress, 🧪 has-tests

#7340 Revert "chore(deps): update dependency symbol-observable to v3 (#7299)"
  CHANGELOG.md
  package-lock.json
  package.json
Labels: :christmas_tree: dependencies, 📟 regression

#7278 Fix query info cache leak
  src/core/QueryInfo.ts
  src/core/QueryManager.ts
Labels: 🏓 awaiting-response, 🐞 bug

#7347 Cancel queryInfo.notifyTimeout when marking final results.
  CHANGELOG.md
  src/core/QueryInfo.ts
  src/react/hooks/__tests__/useQuery.test.tsx
Labels: 🐞 bug, 🧪 has-tests

#7350 Allow manually associating caches with reactive variables.
  CHANGELOG.md
  package.json
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/reactiveVars.ts
Labels: :bulb: idea, 💸 caching, 🧞‍♂️ enhancement, 🧪 has-tests

#7351 Restrict field name over-invalidation to fields without keyArgs.
  CHANGELOG.md
  src/cache/inmemory/__tests__/entityStore.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/policies.ts
Labels: :bulb: idea, 💸 caching, 🧪 has-tests
