Repository apollographql/apollo-client, pull requests merged in 2020-10, with the labels that each got.

#7103 Undo TEdgeWrapper approach for relayStylePagination.
  CHANGELOG.md
  src/cache/inmemory/__tests__/__snapshots__/policies.ts.snap
  src/cache/inmemory/__tests__/policies.ts
  src/utilities/policies/pagination.ts
Labels: 🐞 bug, 📟 regression

#7108 Update @wry/equality to improve undefined property handling.
  package-lock.json
  package.json
Labels: :christmas_tree: dependencies, 📟 regression

#7094 Fix schema link to return errors for unknown queries
  src/link/schema/__tests__/schemaLink.ts
  src/link/schema/index.ts
Labels: 🔗 apollo-link, 🧞‍♂️ enhancement

#7109 Make keyArgs tolerant of optional arguments.
  CHANGELOG.md
  src/cache/inmemory/__tests__/__snapshots__/policies.ts.snap
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/policies.ts
Labels: :bulb: idea, 🍪 feature-request, 💸 caching, 🧞‍♂️ enhancement, 🧪 has-tests

#7127 Support includeUnusedVariables option for HttpLink.
  src/link/http/__tests__/HttpLink.ts
  src/link/http/createHttpLink.ts
  src/link/http/selectHttpOptionsAndBody.ts
Labels: :fried_egg: breaking change, 🧞‍♂️ enhancement, 🧪 has-tests

#7090 docs: Add missing closing brace to WebSocketLink example
  docs/source/data/subscriptions.mdx
Labels: 📝 documentation

#7110 MockLink tweaks to avoid uncaught exceptions
  CHANGELOG.md
  src/__tests__/client.ts
  src/__tests__/fetchMore.ts
  src/__tests__/mutationResults.ts
  src/__tests__/optimistic.ts
  src/core/__tests__/fetchPolicies.ts
  src/link/core/ApolloLink.ts
  src/utilities/testing/mocking/__tests__/MockedProvider.test.tsx
  src/utilities/testing/mocking/__tests__/__snapshots__/MockedProvider.test.tsx.snap
  src/utilities/testing/mocking/mockLink.ts
  src/utilities/testing/mocking/mockQueryManager.ts
Labels: 🐞 bug, 👩‍🏭 refactor

#7141 Default args.offset to 0 in offsetLimitPagination.
  CHANGELOG.md
  src/utilities/policies/pagination.ts
Labels: 🔠 quick-and-easy, 🧞‍♂️ enhancement

#7150 Consider cache.reset a destructive method
  src/core/QueryInfo.ts
Labels: 💸 caching, 🧞‍♂️ enhancement

#7146 reFetchObservableQueries should not refetch skipped queries
  src/core/ObservableQuery.ts
  src/core/QueryManager.ts
  src/core/__tests__/QueryManager/index.ts
Labels: 🐞 bug, 🧞‍♂️ enhancement, 🧪 has-tests

#7157 Update optimism and fix potential cache.watch memory leak.
  CHANGELOG.md
  package-lock.json
  package.json
  src/cache/inmemory/inMemoryCache.ts
Labels: 🐞 bug, 💸 caching, 🧞‍♂️ enhancement

#7107 Update react-native.md install and examples
  docs/source/integrations/react-native.md
Labels: 📝 documentation

#7185 Avoid all sub-package imports from graphql npm package.
  src/__tests__/local-state/export.ts
  src/__tests__/local-state/general.ts
  src/cache/inmemory/policies.ts
  src/core/LocalState.ts
  src/link/batch/__tests__/batchLink.ts
  src/link/core/__tests__/ApolloLink.ts
  src/link/core/types.ts
  src/link/http/selectHttpOptionsAndBody.ts
  src/link/persisted-queries/index.ts
  src/link/schema/index.ts
  src/utilities/graphql/__tests__/fragments.ts
  src/utilities/graphql/__tests__/getFromAST.ts
  src/utilities/graphql/__tests__/transform.ts
  src/utilities/graphql/directives.ts
  src/utilities/graphql/transform.ts
  src/utilities/testing/mocking/mockLink.ts
Labels: :christmas_tree: dependencies, 📦 bundle size, 🙃 upstream, 🛠 tooling, 🧞‍♂️ enhancement, 🧩 implementation-detail

#7174 Update references to apollo-cache-persist to apollo3-cache-persist.
  docs/source/caching/advanced-topics.mdx
  docs/source/why-apollo.mdx
Labels: 📝 documentation, 🔠 quick-and-easy

#7175 Rewrite documentation for custom pagination with field policies
  docs/gatsby-config.js
  docs/source/api/react/hoc.mdx
  docs/source/caching/cache-field-behavior.md
  docs/source/data/pagination.mdx
  docs/source/data/queries.mdx
  docs/source/pagination/core-api.mdx
  docs/source/pagination/cursor-based.mdx
  docs/source/pagination/key-args.mdx
  docs/source/pagination/offset-based.mdx
  docs/source/pagination/overview.mdx
  docs/static/_redirects
Labels: 💸 caching, 📝 documentation, 🧞‍♂️ enhancement

#7256 Simplify the useLazyQuery example of the Queries section
  docs/source/data/queries.mdx
Labels: 📝 documentation

#7259 Call this.currentObservable.tearDownQuery more consistently.
  src/react/data/QueryData.ts
Labels: 🐞 bug, 🧩 implementation-detail
