Repository apollographql/apollo-client, pull requests merged in 2020-08, with the labels that each got.

#6752 Avoid making network requests when skip is true
  CHANGELOG.md
  src/react/data/QueryData.ts
  src/react/hoc/__tests__/queries/skip.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
Labels: ⚛️ React-related, 🐞 bug, 🧪 has-tests

#6486 Add jscodeshift transform for v2->v3 migration
  codemods/ac2-to-ac3/README.md
  codemods/ac2-to-ac3/examples/client-and-cache.ts
  codemods/ac2-to-ac3/examples/link-packages.js
  codemods/ac2-to-ac3/examples/react-packages.tsx
  codemods/ac2-to-ac3/imports.js
  codemods/ac2-to-ac3/package.json
  codemods/misc/mockLinkRejection.ts
Labels: :bulb: idea, 🛠 tooling, 🧞‍♂️ enhancement

#6720 feature: added support for automatic type inference with `typed-document-node`
  package-lock.json
  package.json
  src/__tests__/ApolloClient.ts
  src/cache/core/cache.ts
  src/cache/core/types/Cache.ts
  src/cache/core/types/DataProxy.ts
  src/cache/inmemory/__tests__/__snapshots__/cache.ts.snap
  src/cache/inmemory/__tests__/cache.ts
  src/core/ApolloClient.ts
  src/core/ObservableQuery.ts
  src/core/QueryManager.ts
  src/core/Reobserver.ts
  src/core/types.ts
  src/core/watchQueryOptions.ts
  src/react/components/types.ts
  src/react/data/QueryData.ts
  src/react/hoc/types.ts
  src/react/hooks/useLazyQuery.ts
  src/react/hooks/useMutation.ts
  src/react/hooks/useQuery.ts
  src/react/hooks/useSubscription.ts
  src/react/hooks/utils/useBaseQuery.ts
  src/react/types/types.ts
Labels: :bulb: idea, ⛑ TypeScript, 🛠 tooling, 🧞‍♂️ enhancement

#6777 Settle Feuds with Data
  src/core/QueryInfo.ts
Labels: 🧞‍♂️ enhancement

#6798 fix(testing): export MockedProviderProps from '@apollo/client/testing'
  src/utilities/testing/index.ts
Labels: ⛑ TypeScript, 🔬 testing-utilities

#6817 Disable feud-stopping logic after any cache eviction.
  CHANGELOG.md
  src/core/QueryInfo.ts
Labels: :bulb: idea, 🧞‍♂️ enhancement

#6849 Adjust wording to stop misleading "errors stored in cache" concept
  docs/source/data/error-handling.mdx
Labels: 💸 caching, 📝 documentation

#6854 Avoid full reobservation for optimistic mutation results.
  CHANGELOG.md
  src/__tests__/optimistic.ts
  src/cache/core/types/DataProxy.ts
  src/cache/inmemory/inMemoryCache.ts
  src/core/ObservableQuery.ts
  src/core/QueryInfo.ts
  src/core/__tests__/ObservableQuery.ts
Labels: 🐞 bug, 📟 regression

#6856 Update terser and rollup-plugin-terser to latest versions.
  examples/bundling/no-tree-shaking/rollup-ac2/package-lock.json
  examples/bundling/no-tree-shaking/rollup-ac2/package.json
  examples/bundling/no-tree-shaking/rollup-ac3-no-react/package-lock.json
  examples/bundling/no-tree-shaking/rollup-ac3-no-react/package.json
  package-lock.json
  package.json
Labels: :christmas_tree: dependencies, 🔠 quick-and-easy

#6867 Implement useReactiveVar hook for consuming reactive variables in React components.
  CHANGELOG.md
  docs/source/local-state/managing-state-with-field-policies.mdx
  src/__tests__/__snapshots__/exports.ts.snap
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/reactiveVars.ts
  src/react/hooks/__tests__/useReactiveVar.test.tsx
  src/react/hooks/index.ts
  src/react/hooks/useReactiveVar.ts
Labels: :bulb: idea, ⚛️ React-related, 🍪 feature-request, 🧞‍♂️ enhancement, 🧪 has-tests

#6891 Check structural equality in QueryInfo#setDiff.
  CHANGELOG.md
  src/__tests__/client.ts
  src/core/QueryInfo.ts
Labels: 🐞 bug, 🔠 quick-and-easy

#6893 Improvements to options.nextFetchPolicy.
  CHANGELOG.md
  src/__tests__/client.ts
  src/core/ObservableQuery.ts
  src/core/QueryManager.ts
  src/core/Reobserver.ts
  src/core/watchQueryOptions.ts
Labels: 🐞 bug, 🧞‍♂️ enhancement, 🧪 has-tests

#6898 Consider cache.modify a destructive method, like cache.evict.
  CHANGELOG.md
  src/core/QueryInfo.ts
  src/core/__tests__/QueryManager/index.ts
Labels: 🧪 has-tests

#6902 Mention useApolloClient hook in caching docs
  docs/source/caching/cache-interaction.md
Labels: 📝 documentation
