Repository apollographql/apollo-client, pull requests merged in 2020-12, with the labels that each got.

#7407 Make ApolloLink#onError observer parameter optional.
  CHANGELOG.md
  src/link/core/ApolloLink.ts
Labels: ⛑ TypeScript, 🔗 apollo-link, 🔠 quick-and-easy

#7414 Update ts-invariant to avoid CSP-violating Function fallback.
  CHANGELOG.md
  package-lock.json
  package.json
Labels: :christmas_tree: dependencies, 🧩 implementation-detail

#7428 Roadmap update
  ROADMAP.md
Labels: 📝 documentation

#7394 Edits to "Testing React components" article
  docs/source/development-testing/testing.mdx
Labels: 📝 documentation

#7441 docs: improve headline hierarchy usage in CHANGELOG.md
  CHANGELOG.md
Labels: 📝 documentation

#7448 Fix client.version to reflect @apollo/client version.
  CHANGELOG.md
  config/version.js
  package.json
Labels: 📟 regression, 🛠 tooling, 🧪 has-tests

#7454 Replace stray console.debug with invariant.log.
  src/core/ApolloClient.ts
  src/core/index.ts
Labels: ⚙️ devtools, 🛠 tooling

#7458 Update cache-interaction.md
  docs/source/caching/cache-interaction.md
Labels: 📝 documentation

#7431 Feature: add ability to refetch certain queries imperatively
  docs/source/api/core/ApolloClient.mdx
  src/__tests__/client.ts
  src/core/ApolloClient.ts
  src/core/QueryManager.ts
  src/core/__tests__/QueryManager/index.ts
Labels: 🧞‍♂️ enhancement

#7461 Suggest Firefox Apollo DevTools as well as Chrome.
  src/core/ApolloClient.ts
Labels: ⚙️ devtools, 🧞‍♂️ enhancement

#7460 Simplify config/jest.config.js to consider only src/ directory.
  config/jest.config.js
Labels: 🔠 quick-and-easy, 🔬 testing-utilities, 🛠 tooling, 🧩 implementation-detail

#7409 Update apollo-link-schema.md
  docs/source/api/link/apollo-link-schema.md
Labels: 📝 documentation

#7434 fix 'window is not defined'
  src/core/ApolloClient.ts
Labels: ⚙️ devtools

#7465 Fix import path for deprecated react libs and misc cleanup
  docs/source/api/react/components.mdx
  docs/source/api/react/hoc.mdx
Labels: 📝 documentation

#7463 Fix queryType:true, mutationType:true, and subscriptionType:true type policies.
  CHANGELOG.md
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/policies.ts
Labels: 🐞 bug, 💸 caching, 📟 regression, 🧪 has-tests

#7439 Efficiently canonicalize InMemoryCache result objects.
  CHANGELOG.md
  package-lock.json
  package.json
  src/__tests__/client.ts
  src/cache/inmemory/__tests__/__snapshots__/readFromStore.ts.snap
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/__tests__/object-canon.ts
  src/cache/inmemory/__tests__/optimistic.ts
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/__tests__/readFromStore.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/helpers.ts
  src/cache/inmemory/object-canon.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/readFromStore.ts
  src/core/__tests__/QueryManager/index.ts
Labels: :bulb: idea, :racehorse: performance, 💸 caching, 🧞‍♂️ enhancement, 🧩 implementation-detail, 🧪 has-tests

#7494 removed unused `useState`
  docs/source/data/queries.mdx
Labels: 📝 documentation
