Repository apollographql/apollo-client, pull requests merged in 2021-01, with the labels that each got.

#7581 Avoid duplicate listeners when using useReactiveVar with React.StrictMode
  CHANGELOG.md
  src/react/hooks/__tests__/useReactiveVar.test.tsx
  src/react/hooks/useReactiveVar.ts
Labels: ⚛️ React-related

#7615 Revive zen-observable-ts wrapper for zen-observable package.
  package-lock.json
  package.json
  src/utilities/observables/Observable.ts
Labels: :christmas_tree: dependencies, ⛑ TypeScript, 🛠 tooling, 🧞‍♂️ enhancement, 🧩 implementation-detail

#7627 Cheapen process.env.NODE_ENV lookups in CommonJS bundles.
  CHANGELOG.md
  config/rollup.config.js
Labels: :racehorse: performance, 🧞‍♂️ enhancement, 🧩 implementation-detail
