Repository apollographql/apollo-client, pull requests merged in 2021-12, with the labels that each got.

#9150 Update `recast` AST transform tool to version 0.21.0
  package-lock.json
  package.json
Labels: :christmas_tree: dependencies, 🛠 tooling, 🙃 upstream, 🧩 implementation-detail, size/medium, 🥚 backwards-compatible, 2021-12

#9113 Correct the type of `error` in "Inspecting error states"
  docs/source/data/queries.mdx
Labels: 📝 documentation

#9164 Obfuscate `Function(...)` fallback to thwart static misanalysis
  package-lock.json
  package.json
  src/utilities/globals/global.ts
Labels: 🧞‍♂️ enhancement, 🙃 upstream, 🧩 implementation-detail, size/small, ⏮ compatibility, 2021-12

#9165 remove documentation on npm run watch since watch is no longer in package.json
  CONTRIBUTING.md
Labels: 📝 documentation

#9168 Remove unnecessary language
  docs/source/api/link/apollo-link-rest.md
Labels: 📝 documentation, 🧞‍♂️ enhancement

#9181 Fix typo "orignal" to "original"
  docs/source/pagination/core-api.mdx
Labels: 📝 documentation, 🔬 typo
