Repository apollographql/apollo-client, pull requests merged in 2021-10, with the labels that each got.

#8875 Some quick features we might shove into 3.5 release
  CHANGELOG.md
  package.json
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/__tests__/useMutation.test.tsx
  src/react/hooks/useLazyQuery.ts
  src/react/hooks/useMutation.ts
  src/react/types/types.ts
Labels: ⚗️ needs-documentation

#8876 Edits for updateQuery/updateFragment docs
  docs/source/api/cache/InMemoryCache.mdx
  docs/source/caching/cache-interaction.mdx
  docs/source/caching/overview.mdx
Labels: 📝 documentation

#8868 docs: Configure custom Algolia filters
  docs/gatsby-config.js
  docs/package-lock.json
  docs/package.json
Labels: 📝 documentation

#8878 Document changes in #8875
  docs/shared/mutation-result.mdx
  docs/source/api/react/hooks.mdx
  docs/source/data/mutations.mdx
Labels: 📝 documentation

#8867 document updateQuery/updateFragment
  docs/source/api/cache/InMemoryCache.mdx
  docs/source/caching/cache-interaction.md
Labels: 📝 documentation

#8890 Add a temporary notice about 3.5 release candidate
  docs/source/index.mdx
Labels: 📝 documentation, ⚠️ warnings

#8891 Avoid unnecessarily importing `isType` from `graphql` package
  CHANGELOG.md
  src/utilities/globals/fix-graphql.ts
Labels: 🛠 tooling, 📦 bundle size, 🧩 implementation-detail, 📟 regression, size/medium, 2021-10

#8873 Make `client.{reset,clear}Store` pass appropriate `discardWatches` option to `cache.reset`
  CHANGELOG.md
  src/core/ApolloClient.ts
  src/core/QueryManager.ts
  src/core/__tests__/ObservableQuery.ts
  src/core/__tests__/QueryManager/index.ts
Labels: 💬 discussion, 👩‍🏭 refactor, 🛫 in-progress, 💸 caching, ⚗️ needs-documentation, 2021-10
