Repository apollographql/apollo-client, pull requests merged in 2021-07, with the labels that each got.

#8449 Normalize user-provided HttpLink headers by lower-casing their names.
  CHANGELOG.md
  src/link/http/__tests__/selectHttpOptionsAndBody.ts
  src/link/http/selectHttpOptionsAndBody.ts
Labels: 🐞 bug, 🔗 apollo-link, 🔠 quick-and-easy, 🤏 small-effort, 🧪 has-tests

#8421 Add options to `cache.gc` to enable deleting nonessential/recomputable result caching data
  CHANGELOG.md
  package.json
  scripts/memory/tests.js
  src/cache/inmemory/__tests__/__snapshots__/cache.ts.snap
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/__tests__/entityStore.ts
  src/cache/inmemory/__tests__/readFromStore.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/readFromStore.ts
Labels: :bulb: idea, :racehorse: performance, 🐘 memory, 💸 caching, 🧞‍♂️ enhancement, 🧪 has-tests

#8460 Update cursor-based.mdx
  docs/source/pagination/cursor-based.mdx
Labels: 📝 documentation, 🧞‍♂️ enhancement

#8469 Update Documentation of execution of subscription example
  docs/source/data/subscriptions.mdx
Labels: 📝 documentation

#8465 Improve processing of options.nextFetchPolicy
  CHANGELOG.md
  src/__tests__/client.ts
  src/core/ObservableQuery.ts
  src/core/__tests__/ObservableQuery.ts
  src/react/data/QueryData.ts
  src/react/hoc/__tests__/queries/skip.test.tsx
Labels: 🐞 bug, 💪 medium-effort, 📟 regression, 🧞‍♂️ enhancement

#8489 Suppress `Missing cache result fields...` warnings unless `setLogVerbosity("debug")` configured
  CHANGELOG.md
  config/processInvariants.ts
  package-lock.json
  package.json
  src/core/QueryManager.ts
  src/core/__tests__/QueryManager/index.ts
Labels: 💸 caching, 🔠 quick-and-easy, 🤏 small-effort, 🧞‍♂️ enhancement, 🧪 has-tests

#8434 chore(docs): Clarify usage of `getDataFromTree`
  docs/source/performance/server-side-rendering.mdx
Labels: ⚛️ React-related, 📝 documentation

#8504 Note that mutate/useMutation with @client is not supported in AC3
  docs/source/local-state/managing-state-with-field-policies.mdx
Labels: 📝 documentation

#8505 Multiple (3) lines of defense against merging `{ __ref }` objects into normalized `StoreObject` entities
  src/cache/inmemory/__tests__/entityStore.ts
  src/cache/inmemory/__tests__/writeToStore.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/writeToStore.ts
Labels: 🐞 bug, 💪 medium-effort, 💸 caching, 🧩 implementation-detail, 🧪 has-tests

#8508 Default to current object for `readField` only when `from` omitted.
  CHANGELOG.md
  src/__tests__/__snapshots__/exports.ts.snap
  src/cache/inmemory/__tests__/__snapshots__/policies.ts.snap
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/policies.ts
  src/utilities/testing/index.ts
  src/utilities/testing/mocking/mockLink.ts
  src/utilities/testing/stringifyForDisplay.ts
  src/utilities/testing/withConsoleSpy.ts
  src/utilities/testing/withErrorSpy.ts
Labels: 💸 caching, 🔬 testing-utilities, 🤏 small-effort, 🧞‍♂️ enhancement, 🧪 has-tests

#8265 Mutations article edits for 3.4
  docs/gatsby-config.js
  docs/shared/mutation-options.mdx
  docs/shared/mutation-result.mdx
  docs/shared/refetchQueries-options.mdx
  docs/source/api/cache/InMemoryCache.mdx
  docs/source/api/react/components.mdx
  docs/source/api/react/hoc.mdx
  docs/source/api/react/hooks.mdx
  docs/source/caching/advanced-topics.mdx
  docs/source/caching/cache-interaction.md
  docs/source/caching/overview.mdx
  docs/source/data/mutations.mdx
  docs/source/data/refetching.mdx
  docs/source/local-state/local-resolvers.mdx
  docs/source/local-state/managing-state-with-field-policies.mdx
  docs/source/performance/optimistic-ui.mdx
  src/core/ApolloClient.ts
  src/core/QueryManager.ts
  src/core/types.ts
Labels: 📝 documentation, 🛫 in-progress, 🦾 large-effort

#8547 Style edits to refetching docs
  docs/shared/refetchQueries-options.mdx
  docs/source/data/refetching.mdx
Labels: 📝 documentation

#8396 Add `"type": "module"` to `@apollo/client/core` and friends
  config/helpers.ts
  config/prepareDist.js
  config/resolveModuleIds.ts
  config/rollup.config.js
  config/version.js
  package.json
Labels: :bulb: idea, :christmas_tree: dependencies, ⛑ TypeScript, 👩‍🏭 refactor, 💪 medium-effort, 💬 discussion, 🛠 tooling, 🛫 in-progress, 🧞‍♂️ enhancement

#8555 Update package-lock.json to "lockfileVersion":2 for npm v7
  package-lock.json
Labels: :christmas_tree: dependencies, 🔠 quick-and-easy, 🙃 upstream, 🛠 tooling, 🤏 small-effort, 🧩 implementation-detail

#8558 Delay initializing `stringifyCanon` until `canonicalStringify` used.
  CHANGELOG.md
  src/cache/inmemory/object-canon.ts
Labels: size/small, 🐞 bug, 🔠 quick-and-easy, 🚨 high-priority, 🧩 implementation-detail
