Repository apollographql/apollo-client, pull requests merged in 2021-11, with the labels that each got.

#9000 Allow `FieldFunctionOptions` to be passed as Type Argument for `FieldPolicy`
  CHANGELOG.md
  src/cache/inmemory/policies.ts
Labels: ⛑ TypeScript, 🧞‍♂️ enhancement, 💸 caching, 🥚 backwards-compatible

#8996 Identify written results using processed `StoreObject` in `StoreWriter#processSelectionSet`
  CHANGELOG.md
  package.json
  src/cache/inmemory/__tests__/__snapshots__/policies.ts.snap
  src/cache/inmemory/__tests__/key-extractor.ts
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/key-extractor.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/writeToStore.ts
Labels: 👩‍🏭 refactor, 🧪 has-tests, 💸 caching, size/large, 🥚 backwards-compatible, 2021-11

#9004 Update Jest-related dependencies to latest version (v27) to address `npm audit` problems
  config/jest.config.js
  package-lock.json
  package.json
  src/__tests__/ApolloClient.ts
  src/__tests__/client.ts
  src/__tests__/graphqlSubscriptions.ts
  src/__tests__/local-state/__snapshots__/export.ts.snap
  src/__tests__/local-state/export.ts
  src/__tests__/local-state/subscriptions.ts
  src/__tests__/optimistic.ts
  src/cache/inmemory/__tests__/fragmentMatcher.ts
  src/cache/inmemory/__tests__/writeToStore.ts
  src/core/__tests__/QueryManager/links.ts
  src/core/__tests__/QueryManager/multiple-results.ts
  src/core/__tests__/QueryManager/recycler.ts
  src/link/batch-http/__tests__/batchHttpLink.ts
  src/link/batch/__tests__/batchLink.ts
  src/link/context/__tests__/index.ts
  src/link/core/__tests__/ApolloLink.ts
  src/link/error/__tests__/index.ts
  src/link/http/__tests__/HttpLink.ts
  src/link/http/__tests__/parseAndCheckHttpResponse.ts
  src/link/persisted-queries/__tests__/index.ts
  src/link/schema/__tests__/schemaLink.ts
  src/link/utils/__tests__/fromError.ts
  src/link/utils/__tests__/fromPromise.ts
  src/link/utils/__tests__/toPromise.ts
  src/link/ws/__tests__/webSocketLink.ts
  src/react/components/__tests__/client/Mutation.test.tsx
  src/react/components/__tests__/client/Query.test.tsx
  src/react/components/__tests__/ssr/getDataFromTree.test.tsx
  src/react/context/__tests__/ApolloConsumer.test.tsx
  src/react/hoc/__tests__/mutations/index.test.tsx
  src/react/hoc/__tests__/mutations/lifecycle.test.tsx
  src/react/hoc/__tests__/queries/skip.test.tsx
  src/react/hoc/__tests__/shared-operations.test.tsx
  src/react/hoc/__tests__/ssr/getDataFromTree.test.tsx
  src/react/hoc/__tests__/subscriptions/subscriptions.test.tsx
Labels: ⛑ TypeScript, :christmas_tree: dependencies, 🛠 tooling, 👩‍🏭 refactor, 🧩 implementation-detail, 🔬 testing-utilities, size/medium, 🔐 security, 2021-11

#9043 Small ROADMAP adjustments
  ROADMAP.md
Labels: size/small, 2021-11

#9052 Update `@testing-library/react` to latest stable version
  package-lock.json
  package.json
  src/react/components/__tests__/client/Mutation.test.tsx
  src/react/components/__tests__/client/Query.test.tsx
  src/react/components/__tests__/client/Subscription.test.tsx
  src/react/hoc/__tests__/client-option.test.tsx
  src/react/hoc/__tests__/fragments.test.tsx
  src/react/hoc/__tests__/mutations/queries.test.tsx
  src/react/hoc/__tests__/mutations/recycled-queries.test.tsx
  src/react/hoc/__tests__/queries/api.test.tsx
  src/react/hoc/__tests__/queries/errors.test.tsx
  src/react/hoc/__tests__/queries/index.test.tsx
  src/react/hoc/__tests__/queries/lifecycle.test.tsx
  src/react/hoc/__tests__/queries/loading.test.tsx
  src/react/hoc/__tests__/queries/observableQuery.test.tsx
  src/react/hoc/__tests__/queries/polling.test.tsx
  src/react/hoc/__tests__/queries/reducer.test.tsx
  src/react/hoc/__tests__/queries/skip.test.tsx
  src/react/hoc/__tests__/queries/updateQuery.test.tsx
  src/react/hoc/__tests__/shared-operations.test.tsx
  src/react/hoc/__tests__/subscriptions/subscriptions.test.tsx
  src/react/hooks/__tests__/useMutation.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/__tests__/useReactiveVar.test.tsx
  src/testing/react/__tests__/MockedProvider.test.tsx
  src/testing/react/__tests__/mockSubscriptionLink.test.tsx
Labels: ⛑ TypeScript, :christmas_tree: dependencies, 🔬 testing-utilities

#9073 Revert `normalizeNonRelativeId` changes in `config/resolveModuleIds.ts`
  CHANGELOG.md
  config/resolveModuleIds.ts
Labels: :christmas_tree: dependencies, 🛫 in-progress, 🧩 implementation-detail, 📟 regression, size/small, 2021-11

#9050 chore: Ensure only current file is run with VSCode debugger
  .vscode/launch.json
  CHANGELOG.md
Labels: 🔬 testing-utilities

#8785 Use `useSyncExternalStore()`
  package-lock.json
  package.json
  src/link/persisted-queries/__tests__/react.tsx
  src/react/components/__tests__/client/Mutation.test.tsx
  src/react/components/__tests__/client/Query.test.tsx
  src/react/components/__tests__/ssr/getDataFromTree.test.tsx
  src/react/components/__tests__/ssr/server.test.tsx
  src/react/hoc/__tests__/queries/errors.test.tsx
  src/react/hoc/__tests__/queries/lifecycle.test.tsx
  src/react/hoc/__tests__/queries/loading.test.tsx
  src/react/hoc/__tests__/queries/observableQuery.test.tsx
  src/react/hoc/__tests__/queries/skip.test.tsx
  src/react/hoc/__tests__/ssr/getDataFromTree.test.tsx
  src/react/hoc/__tests__/ssr/server.test.tsx
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/__tests__/useMutation.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/useLazyQuery.ts
  src/react/hooks/useQuery.ts
  src/react/ssr/RenderPromises.ts
  src/react/ssr/__tests__/useLazyQuery.test.tsx
  src/react/ssr/__tests__/useQuery.test.tsx
Labels: 2021-11

#9083 Resolve `ts-invariant/process` module identifier again in `config/resolveModuleIds.ts`
  CHANGELOG.md
  config/resolveModuleIds.ts
Labels: 🛠 tooling, 📟 regression, size/small, 2021-11

#9103 Undo breaking change to `selectHttpOptionsBody` signature
  CHANGELOG.md
  src/__tests__/__snapshots__/exports.ts.snap
  src/link/batch-http/batchHttpLink.ts
  src/link/http/__tests__/selectHttpOptionsAndBody.ts
  src/link/http/createHttpLink.ts
  src/link/http/index.ts
  src/link/http/selectHttpOptionsAndBody.ts
Labels: 👩‍🏭 refactor, 📟 regression, 🧪 has-tests, 🔗 apollo-link, size/small, ⏮ compatibility, 2021-11
