Repository apollographql/apollo-client, pull requests merged in 2021-02, with the labels that each got.

#6953 Apply new API reference structure to non-generated AC reference
  docs/source/api/cache/InMemoryCache.mdx
  docs/source/api/core/ApolloClient.mdx
  docs/source/caching/cache-interaction.md
Labels: 📝 documentation

#7657 Reactivate reactive variables when InMemoryCache acquires first watcher.
  CHANGELOG.md
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/reactiveVars.ts
Labels: 🐞 bug, 💸 caching, 🚨 high-priority, 🧩 implementation-detail

#7660 Backport v3.4 Symbol.species fix for Concast and ObservableQuery.
  CHANGELOG.md
  package.json
  src/__tests__/__snapshots__/exports.ts.snap
  src/core/ObservableQuery.ts
  src/core/__tests__/ObservableQuery.ts
  src/utilities/index.ts
  src/utilities/observables/Concast.ts
  src/utilities/observables/Observable.ts
  src/utilities/observables/__tests__/subclassing.ts
  src/utilities/observables/subclassing.ts
Labels: 🐞 bug, 🧞‍♂️ enhancement, 🧪 has-tests

#7583 doc: Fix Typo in Testing React components document(Shibe is Shiba)
  docs/source/development-testing/testing.mdx
Labels: 📝 documentation, 🔬 typo

#7597 Change example to use forEach instead of map
  docs/source/data/error-handling.mdx
Labels: 📝 documentation

#7534 Fix broken url in docs
  docs/shared/query-result.mdx
Labels: 📝 documentation

#7671 Attempt to remove ink dependency from docs/package.json.
  docs/package-lock.json
  docs/package.json
Labels: 📝 documentation, 🛠 tooling

#7661 Prevent reactive variables from retaining otherwise unreachable InMemoryCache objects.
  .circleci/config.yml
  CHANGELOG.md
  package.json
  scripts/memory/README.md
  scripts/memory/package.json
  scripts/memory/tests.js
  src/cache/inmemory/reactiveVars.ts
  src/core/QueryInfo.ts
Labels: 🐞 bug, 💸 caching, 🧪 has-tests

#7651 Update graphql-tag to v2.12.0
  CHANGELOG.md
  examples/bundling/no-tree-shaking/rollup-ac2/package-lock.json
  examples/bundling/no-tree-shaking/rollup-ac2/package.json
  examples/bundling/tree-shaking/rollup-ac2/package-lock.json
  examples/bundling/tree-shaking/rollup-ac2/package.json
  package-lock.json
  package.json
Labels: :christmas_tree: dependencies, ⛑ TypeScript, 🧩 implementation-detail

#7672 WebSocketLink edits
  docs/source/api/link/apollo-link-ws.md
Labels: 📝 documentation

#7675 Move codemods/ into scripts/, to declutter top-level directories.
  CHANGELOG.md
  docs/source/migrating/apollo-client-3-migration.mdx
  scripts/codemods/ac2-to-ac3/README.md
  scripts/codemods/ac2-to-ac3/examples/client-and-cache.ts
  scripts/codemods/ac2-to-ac3/examples/link-packages.js
  scripts/codemods/ac2-to-ac3/examples/react-packages.tsx
  scripts/codemods/ac2-to-ac3/imports.js
  scripts/codemods/ac2-to-ac3/package.json
  scripts/codemods/misc/mockLinkRejection.ts
Labels: 🔠 quick-and-easy, 🧩 implementation-detail

#7456 Ensure POST request when sending full query with persisted queries link.
  CHANGELOG.md
  src/link/persisted-queries/__tests__/index.ts
  src/link/persisted-queries/index.ts
Labels: 🔗 apollo-link, 🧪 has-tests

#7476 Use Partial<TVariables> typing for fetchMore variables, rather than Pick<TVariables, K>
  CHANGELOG.md
  src/core/ObservableQuery.ts
  src/core/watchQueryOptions.ts
  src/react/data/QueryData.ts
  src/react/hoc/__tests__/queries/api.test.tsx
  src/react/hoc/types.ts
  src/react/types/types.ts
Labels: ⛑ TypeScript

#7121 Add /graphql query path to all URIs in subscriptions docs.
  docs/source/data/subscriptions.mdx
Labels: 📝 documentation

#6027 Fix typos in comments in src/utilities/graphql/transform.ts
  src/utilities/graphql/transform.ts
Labels: 📝 documentation, 🔬 typo

#5545 Fix broken link in error message about fragments
  packages/apollo-cache-inmemory/src/fragmentMatcher.ts
Labels: 📝 documentation

#7603 Respect pageInfo.hasNextPage in Relay pagination example
  docs/source/pagination/cursor-based.mdx
Labels: 📝 documentation

#7695 Revert #7276, but test garbage collection of ObservableQuery.
  CHANGELOG.md
  scripts/memory/tests.js
  src/core/ObservableQuery.ts
Labels: 🐞 bug, 🧪 has-tests

#7715 Fix useLazyQuery forceUpdate loop regression.
  CHANGELOG.md
  src/react/hooks/utils/useBaseQuery.ts
Labels: ⚛️ React-related, 🐞 bug, 📟 regression, 🛫 in-progress

#7716 February 2021 roadmap update
  ROADMAP.md
Labels: 📝 documentation

#7751 Update ts-invariant to version 0.6.1.
  package-lock.json
  package.json
Labels: :christmas_tree: dependencies, ⛑ TypeScript
