Repository apollographql/apollo-client, pull requests merged in 2022-09, with the labels that each got.

#10020 Supports "no-cache" fetchPolicy with pollInterval
  src/core/ObservableQuery.ts
  src/react/hoc/__tests__/queries/polling.test.tsx
Labels: 🛫 in-progress

#10062 updates local resolver warning
  docs/source/local-state/local-resolvers.mdx
Labels: 📝 documentation

#10049 GitHub Workflows security hardening
  .github/workflows/docs-publish.yml
Labels: 🏓 awaiting-team-response

#10052 Pass mutation options to handlers
  CHANGELOG.md
  docs/shared/mutation-options.mdx
  src/react/components/__tests__/client/Mutation.test.tsx
  src/react/hooks/__tests__/useMutation.test.tsx
  src/react/hooks/useMutation.ts
  src/react/types/types.ts
Labels: 🛫 in-progress

#10051 MissingFieldError once again extends Error
  package.json
  src/cache/core/types/common.ts
Labels: 🛫 in-progress

#10045 Fix typos
  docs/source/api/react/hooks.mdx
Labels: 📝 documentation

#10066 docs: Update "Using Apollo with TypeScript" with a description of fetchMore and subscribeToMore
  docs/source/development-testing/static-typing.md
Labels: 📝 documentation

#9933 fix: make `react-dom` an optional peer dependency
  package.json
Labels: 🛫 in-progress

#10018 Adds @defer support
  .gitignore
  .vscode/settings.json
  CHANGELOG.md
  package-lock.json
  package.json
  src/__tests__/__snapshots__/exports.ts.snap
  src/core/ObservableQuery.ts
  src/core/QueryInfo.ts
  src/core/QueryManager.ts
  src/link/core/types.ts
  src/link/http/__tests__/HttpLink.ts
  src/link/http/__tests__/responseIterator.ts
  src/link/http/__tests__/responseIteratorNoAsyncIterator.ts
  src/link/http/createHttpLink.ts
  src/link/http/iterators/LICENSE
  src/link/http/iterators/async.ts
  src/link/http/iterators/nodeStream.ts
  src/link/http/iterators/promise.ts
  src/link/http/iterators/reader.ts
  src/link/http/parseAndCheckHttpResponse.ts
  src/link/http/responseIterator.ts
  src/react/hooks/__tests__/useQuery.test.tsx
  src/testing/core/subscribeAndCount.ts
  src/utilities/common/canUse.ts
  src/utilities/common/incrementalResult.ts
  src/utilities/common/responseIterator.ts
  src/utilities/graphql/directives.ts
Labels: 🛫 in-progress

#10082 Improvements to the `hasDirectives` utility function
  src/__tests__/__snapshots__/exports.ts.snap
  src/utilities/graphql/__tests__/directives.ts
  src/utilities/graphql/directives.ts
  src/utilities/index.ts
Labels: 🧞‍♂️ enhancement, 🔠 quick-and-easy, 🧪 has-tests

#8973 Export `Modifier` and `Modifiers`
  src/cache/index.ts
Labels: 🏓 awaiting-team-response

#10099 chore(docs): add useFragment_experimental documentation
  docs/shared/useFragment-options.mdx
  docs/shared/useFragment-result.mdx
  docs/source/api/react/hooks-experimental.mdx
  docs/source/caching/cache-interaction.mdx
  docs/source/config.json
  docs/source/data/defer.mdx
  docs/source/data/fragments.md
Labels: 📝 documentation

#10097 Bump up timeout time for batchLink, query and polling tests
  src/link/batch/__tests__/batchLink.ts
  src/react/hoc/__tests__/queries/index.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
Labels: 🔬 testing-utilities

#9940 Moves the React hooks entrypoint from @apollo/client to @apollo/client/react
  config/entryPoints.js
  docs/source/api/react/hooks.mdx
  docs/source/api/react/testing.md
  docs/source/data/mutations.mdx
  docs/source/data/queries.mdx
  docs/source/development-testing/static-typing.md
  docs/source/development-testing/testing.mdx
  docs/source/get-started.mdx
  docs/source/integrations/react-native.md
  docs/source/local-state/local-resolvers.mdx
  docs/source/local-state/managing-state-with-field-policies.mdx
  docs/source/migrating/apollo-client-4-migration.mdx
  docs/source/migrating/hooks-migration.md
  docs/source/performance/server-side-rendering.mdx
  scripts/memory/tests.js
  src/__tests__/__snapshots__/exports.ts.snap
  src/__tests__/exports.ts
  src/index.ts
  src/react/components/__tests__/client/Mutation.test.tsx
  src/react/components/__tests__/client/Query.test.tsx
  src/react/hoc/__tests__/mutations/index.test.tsx
  src/react/hooks/__tests__/useFragment.test.tsx
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/__tests__/useMutation.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/index.ts
  src/react/ssr/__tests__/useQuery.test.tsx
  src/testing/index.ts
  src/testing/react/index.ts
Labels: 🛫 in-progress

#10044 remove obsolete displayName query option
  docs/shared/query-options.mdx
  src/react/hooks/useQuery.ts
  src/react/types/types.ts
Labels: 📝 documentation, 🔍 investigate, 🏓 awaiting-team-response

#10047 docs: fixup onResetStore docs, convert to hooks
  docs/source/caching/advanced-topics.mdx
Labels: 📝 documentation, 🏓 awaiting-team-response

#9919 Cascade out type parameters for TypeScript 4.8
  src/cache/inmemory/inMemoryCache.ts
  src/core/ApolloClient.ts
  src/core/ObservableQuery.ts
  src/core/QueryManager.ts
  src/core/watchQueryOptions.ts
  src/react/components/Query.tsx
  src/react/components/Subscription.tsx
  src/react/components/types.ts
  src/react/hoc/graphql.tsx
  src/react/hoc/mutation-hoc.tsx
  src/react/hoc/query-hoc.tsx
  src/react/hoc/subscription-hoc.tsx
  src/react/hoc/types.ts
  src/react/hooks/useLazyQuery.ts
  src/react/hooks/useQuery.ts
  src/react/hooks/useSubscription.ts
  src/react/ssr/RenderPromises.ts
  src/react/types/types.ts
  src/testing/core/subscribeAndCount.ts
  src/utilities/common/cloneDeep.ts
  src/utilities/common/mergeOptions.ts
  src/utilities/policies/pagination.ts
Labels: ⛑ TypeScript

#9495 Add onError option to useSubscription hook
  src/react/hooks/__tests__/useSubscription.test.tsx
  src/react/hooks/useSubscription.ts
  src/react/types/types.ts
Labels: 🧞‍♂️ enhancement, 🛎 subscriptions

#9764 Allow registering named fragments with `InMemoryCache` to support using `...FragmentName` in queries without redeclaring `FragmentName` in every query
  package.json
  src/__tests__/__snapshots__/exports.ts.snap
  src/cache/core/cache.ts
  src/cache/index.ts
  src/cache/inmemory/__tests__/fragmentRegistry.ts
  src/cache/inmemory/__tests__/writeToStore.ts
  src/cache/inmemory/fragmentRegistry.ts
  src/cache/inmemory/helpers.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/readFromStore.ts
  src/cache/inmemory/types.ts
  src/cache/inmemory/writeToStore.ts
  src/core/QueryInfo.ts
  src/core/QueryManager.ts
  src/utilities/graphql/fragments.ts
  src/utilities/graphql/transform.ts
  src/utilities/index.ts
Labels: :bulb: idea, 🧞‍♂️ enhancement, 👩‍🔬 needs-more-tests, 💸 caching, ⚗️ needs-documentation

#10112 local-state-management AC2 LocalState side note
  docs/source/local-state/local-state-management.mdx
Labels: 📝 documentation

#9997 Fix for ServerError obscured by ServerParseError
  package.json
  src/link/http/__tests__/HttpLink.ts
  src/link/http/__tests__/parseAndCheckHttpResponse.ts
  src/link/http/parseAndCheckHttpResponse.ts
Labels: 🛫 in-progress

#10128 docs: Fix typo
  docs/source/development-testing/testing.mdx
Labels: 📝 documentation
