Repository apollographql/apollo-client, pull requests merged in 2022-10, with the labels that each got.

#10175 Small updates for AS4
  docs/source/api/link/apollo-link-rest.md
  src/link/persisted-queries/index.ts
Labels: 📝 documentation

#9984 Various edits to caching docs
  docs/source/caching/advanced-topics.mdx
  docs/source/caching/cache-configuration.mdx
  docs/source/caching/cache-field-behavior.mdx
  docs/source/caching/cache-interaction.mdx
  docs/source/caching/garbage-collection.mdx
  docs/source/caching/overview.mdx
Labels: 📝 documentation

#10204 Fix typo in `NetworkError`
  src/link/batch-http/batchHttpLink.ts
  src/link/http/parseAndCheckHttpResponse.ts
Labels: 🏓 awaiting-contributor-response

#10138 Update apollo-link-rest.md - Add graphql-anywhere to install list
  docs/source/api/link/apollo-link-rest.md
Labels: 📝 documentation, ⁉️ question

#10209 Experiment with not caching the `~/.npm` directory during Filesize/Tests CircleCI jobs
  .circleci/config.yml
Labels: :racehorse: performance, 🛠 tooling, 🧞‍♂️ enhancement, 🔠 quick-and-easy

#10031 docs: add TypedDocumentNode example
  docs/source/development-testing/static-typing.md
Labels: 📝 documentation

#10211 Update Local Resolvers docs
  docs/source/local-state/local-resolvers.mdx
Labels: 📝 documentation

#10237 Implement `compareResultsUsingQuery` helper function
  src/react/hooks/__tests__/compareResults.test.tsx
  src/react/hooks/compareResults.ts
Labels: 💬 discussion, :bulb: idea, 🧞‍♂️ enhancement, 🧩 implementation-detail, 🧪 has-tests
