Repository apollographql/apollo-client, pull requests merged in 2022-05, with the labels that each got.

#9634 Fix code snippets for SubscriptionClient
  docs/source/api/link/apollo-link-ws.md
  docs/source/data/subscriptions.mdx
Labels: 📝 documentation

#9665 Drastically simplify `useQuery` default options processing
  CHANGELOG.md
  src/react/hooks/useQuery.ts
  src/utilities/common/mergeOptions.ts
Labels: 🐞 bug, 🚨 high-priority, 👩‍🏭 refactor, 🧞‍♂️ enhancement, 📟 regression, ⚛️ React-related, 🥚 backwards-compatible

#9663 Docs: fix typo in subscriptions.mdx
  docs/source/data/subscriptions.mdx
Labels: 📝 documentation, 🔬 typo

#9672 Update `ts-invariant` to version 0.10.2 to fix source map warnings
  CHANGELOG.md
  package-lock.json
  package.json
Labels: :christmas_tree: dependencies, 🛠 tooling, 🔠 quick-and-easy, ⚠️ warnings

#5466 Update queries.mdx
  docs/source/data/queries.mdx
Labels: 📝 documentation, ⚛️ React-related

#9677 Fix failing regression test for skipped SSR `useQuery` stuck in standby
  CHANGELOG.md
  src/react/hooks/useQuery.ts
  src/react/ssr/__tests__/useQuery.test.tsx
Labels: 📟 regression, 🧪 has-tests, ⚛️ React-related, 🥓 Server-side rendering (SSR)

#9683 Add a comment about a new use of the content-type header
  src/link/http/selectHttpOptionsAndBody.ts
Labels: 📝 documentation, 🔗 apollo-link

#9680 Add missing assumeImmutableResults documentation
  docs/source/api/core/ApolloClient.mdx
  src/core/ApolloClient.ts
Labels: 📝 documentation, :racehorse: performance, 💸 caching

#9684 Prevent `useLazyQuery` from making duplicate requests when execution function first called
  CHANGELOG.md
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/useLazyQuery.ts
  src/react/hooks/useQuery.ts
Labels: 🐞 bug, 📟 regression, 🧪 has-tests, ⚛️ React-related

#9679 Fix issue with `useQuery` returning `loading: true` state during server-side rendering with `skip: true`
  CHANGELOG.md
  src/react/hooks/useQuery.ts
  src/react/ssr/__tests__/useQuery.test.tsx
Labels: ⚛️ React-related, 🥓 Server-side rendering (SSR)

#6755 Add description & example of how to handle multiple parameters in read() when declaring typePolicies.
  docs/source/caching/cache-field-behavior.mdx
Labels: 📝 documentation, ⁉️ question

#5608 Add link to ts-transform-graphql-tag in the performance docs
  docs/source/performance/babel.md
Labels: 📝 documentation, ⁉️ question

#9687 Poll interval docs update
  docs/source/data/queries.mdx
Labels: 📝 documentation

#9675 Internalize `useSyncExternalStore` shim, for more control than `use-sync-external-store` provides
  CHANGELOG.md
  package-lock.json
  package.json
  src/__tests__/__snapshots__/exports.ts.snap
  src/react/hooks/useQuery.ts
  src/react/hooks/useSyncExternalStore.ts
  src/utilities/common/__tests__/canUse.ts
  src/utilities/common/canUse.ts
Labels: :christmas_tree: dependencies, 📦 bundle size, 🧞‍♂️ enhancement, ⚛️ React-related, 🥚 backwards-compatible, ⚠️ warnings

#9701 Guarantee `Concast` cleanup without `Observable cancelled prematurely` rejection
  CHANGELOG.md
  src/utilities/observables/Concast.ts
  src/utilities/observables/__tests__/Concast.ts
Labels: 🐞 bug, 🧪 has-tests

#9621 Update example headers with authentication
  docs/source/api/link/apollo-link-http.md
Labels: 📝 documentation

#9498 Fix a misplaced semicolon
  docs/source/api/link/persisted-queries.md
Labels: 📝 documentation

#9529 Correct GraphQL variable name "text" to "type"
  docs/source/data/mutations.mdx
Labels: 📝 documentation

#8630 Update authentication.mdx
  docs/source/networking/authentication.mdx
Labels: 📝 documentation

#8234 Add apollo-link-observable to community links
  docs/source/api/link/community-links.md
Labels: 📝 documentation

#7517 apollo-codegen is deprecated, but the tooling documentation still suggests it
  docs/source/development-testing/developer-tooling.md
Labels: 📝 documentation, ⁉️ question

#9711 chore: corrected body params
  docs/source/api/link/apollo-link-rest.md
Labels: 📝 documentation

#9709 `useSyncExternalStore` refinements
  package-lock.json
  package.json
  src/react/hooks/useSyncExternalStore.ts
Labels: 🙃 upstream, 🧩 implementation-detail, 🔠 quick-and-easy, ⚛️ React-related

#9716 Help React Native import `@apollo/client/main.cjs` and other CommonJS bundles
  CHANGELOG.md
  config/helpers.ts
  config/rollup.config.js
  package-lock.json
  package.json
Labels: :christmas_tree: dependencies, 🧞‍♂️ enhancement, 🙃 upstream, 🧩 implementation-detail, ⚛️ React-related

#9718 Replace `concast.cleanup` method with simpler `concast.beforeNext` API
  package.json
  src/core/ObservableQuery.ts
  src/core/QueryManager.ts
  src/utilities/observables/Concast.ts
  src/utilities/observables/__tests__/Concast.ts
Labels: :bulb: idea, 🛫 in-progress, 🧩 implementation-detail, 👩‍🔬 needs-more-tests

#9719 Revamping the "Why Apollo Client" article
  docs/source/why-apollo.mdx
Labels: 📝 documentation

#9707 Fix useSubscription bug in React v18 StrictMode (#9664)
  CHANGELOG.md
  package.json
  src/react/hooks/useSubscription.ts
Labels: 🛫 in-progress, 📏 React.StrictMode

#9734 Preserve `previousData` even when different client or query passed to `useQuery`
  CHANGELOG.md
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/useQuery.ts
Labels: 📟 regression, 🧪 has-tests, ⚛️ React-related

#9741 Restore pre-v3.6 `variables` replacement behavior of `ObservableQuery#reobserve` method
  CHANGELOG.md
  src/core/ObservableQuery.ts
  src/react/hooks/__tests__/useQuery.test.tsx
Labels: 📟 regression, 🧪 has-tests

#9430 Clarify modifying response data in link docs
  docs/source/networking/advanced-http-networking.md
Labels: 📝 documentation

#9744 adds documentation on file uploads
  docs/source/data/file-uploads.md
Labels: 📝 documentation

#9441 Fix improper syntax with spread operator
  docs/source/development-testing/testing.mdx
Labels: 📝 documentation

#9747 Reduce confusion about the query component
  docs/source/data/queries.mdx
Labels: 📝 documentation

#9758 Merge `variables` from original `useLazyQuery(query, { variables })` with `variables` passed to execution function
  CHANGELOG.md
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/useLazyQuery.ts
Labels: 🔠 quick-and-easy, 🧪 has-tests, ⚛️ React-related

#9762 Allow `useLazyQuery(query, { defaultOptions })` to benefit from `defaultOptions.variables`
  CHANGELOG.md
  package.json
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/useQuery.ts
Labels: 🐞 bug, 🧪 has-tests, ⚛️ React-related
