Repository apollographql/apollo-client, pull requests merged in 2022-06, with the labels that each got.

#9776 fixes pr 9600
  docs/source/api/link/apollo-link-rest.md
Labels: 📝 documentation

#9708 Update mutations.mdx
  docs/source/data/mutations.mdx
Labels: 📝 documentation

#9793 Fix `BatchHttpLink` regression that silently discarded some pending queries
  package-lock.json
  package.json
  src/link/batch/batching.ts
  src/react/hooks/__tests__/useMutation.test.tsx
Labels: 🛫 in-progress, 📟 regression, 🧪 has-tests, 🔗 apollo-link, ♾ Infinite

#9777 fixes expansion panel
  docs/source/data/error-handling.mdx
Labels: 📝 documentation

#9808 fix: fixes FieldFunctionOptions return incorrect variables
  CHANGELOG.md
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/policies.ts
Labels: 🐞 bug, 🧪 has-tests, 💸 caching

#9805 Fix build config to work on Windows
  CHANGELOG.md
  config/helpers.ts
  config/rewriteSourceMaps.ts
  config/rollup.config.js
Labels: 🛠 tooling

#9798 Fix: useQuery returns called value based on skip option.
  CHANGELOG.md
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/useQuery.ts
Labels: 🧪 has-tests, ⚛️ React-related

#9791 fix: abort stale connection on reobserve (#9532)
  CHANGELOG.md
  src/core/ObservableQuery.ts
  src/core/__tests__/QueryManager/index.ts
Labels: 🧞 fixed-by-contributor

#9823 Leave `fetchPolicy` unchanged when `skip: true` (or in standby) and `nextFetchPolicy` is available
  CHANGELOG.md
  src/core/ObservableQuery.ts
  src/core/QueryManager.ts
  src/core/__tests__/ObservableQuery.ts
  src/core/__tests__/fetchPolicies.ts
  src/react/hoc/__tests__/queries/loading.test.tsx
  src/react/hoc/__tests__/queries/skip.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/utilities/observables/Concast.ts
Labels: 🐞 bug, 🧪 has-tests, ⚛️ React-related

#9809 adds a prettier ignore file
  .prettierignore
Labels: 📝 documentation

#9820 Fix documentation code snippets for SubscriptionClient
  docs/source/api/link/apollo-link-ws.md
  docs/source/data/subscriptions.mdx
Labels: 📝 documentation, 🏓 awaiting-contributor-response

#9801 Delay execution of callback functions to fix React errors
  CHANGELOG.md
  package.json
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/useQuery.ts
Labels: 🧗‍♀️ rebase, 🧞‍♂️ enhancement, 🧪 has-tests, ⚛️ React-related, 🧞 fixed-by-contributor
