Repository apollographql/apollo-client, pull requests merged in 2022-11, with the labels that each got.

#10268 chore(tests): warn on ts-jest diagnostics error outside of CI test runs
  config/jest.config.js
  package.json
Labels: 🔬 testing-utilities

#10275 docs: displays the error correctly
  docs/source/get-started.mdx
Labels: 📝 documentation, 🧞 fixed-by-contributor

#10173 doc(static-typing): rewrite with GraphQL Code Generator setup
  docs/source/development-testing/static-typing.md
Labels: 📝 documentation

#10294 Further update the TypeGen article for style
  docs/source/development-testing/static-typing.md
Labels: 📝 documentation

#9323 Add name property to ApolloError
  CHANGELOG.md
  src/__tests__/__snapshots__/graphqlSubscriptions.ts.snap
  src/errors/index.ts
  src/testing/react/__tests__/__snapshots__/MockedProvider.test.tsx.snap
Labels: 🛫 in-progress

#10235 Add array examples to reactive variable documentation
  docs/source/local-state/reactive-variables.mdx
Labels: 📝 documentation

#10111 Changelog and docs for preserveHeaderCase
  CHANGELOG.md
  docs/source/api/link/apollo-link-batch-http.mdx
  docs/source/api/link/apollo-link-http.md
  docs/source/networking/advanced-http-networking.md
Labels: 📝 documentation
