Repository apollographql/apollo-client, pull requests merged in 2022-12, with the labels that each got.

#10144 Exclude "cursor" argument to prevent separate cache instance
  docs/source/pagination/cursor-based.mdx
Labels: 📝 documentation

#10337 Introduce Changesets
  .changeset/README.md
  .changeset/config.json
  .circleci/config.yml
  .github/workflows/check-prerelease.yml
  .github/workflows/exit-prerelease.yml
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: 🛠 tooling, 🧞‍♂️ enhancement

#10368 Fixes support for defer in mutations
  .changeset/tough-ghosts-itch.md
  config/bundlesize.ts
  src/__tests__/__snapshots__/exports.ts.snap
  src/core/QueryInfo.ts
  src/core/QueryManager.ts
  src/react/hooks/__tests__/useMutation.test.tsx
  src/utilities/common/errorHandling.ts
  src/utilities/common/incrementalResult.ts
Labels: 🐞 bug, 🥚 backwards-compatible
