Repository apollographql/apollo-client, pull requests merged in 2023-08, with the labels that each got.

#11098 Add Suspense page to docs
  docs/source/api/react/hooks.mdx
  docs/source/config.json
  docs/source/data/defer.mdx
  docs/source/data/error-handling.mdx
  docs/source/data/queries.mdx
  docs/source/data/suspense.mdx
  docs/source/development-testing/testing.mdx
  docs/source/local-state/reactive-variables.mdx
  docs/source/migrating/apollo-client-3-migration.mdx
Labels: 📝 documentation

#11102 3.8 Docs
  .prettierignore
  docs/shared/document-transform-options.mdx
  docs/shared/useBackgroundQuery-options.mdx
  docs/shared/useSuspenseQuery-options.mdx
  docs/shared/useSuspenseQuery-result.mdx
  docs/source/api/link/apollo-link-remove-typename.mdx
  docs/source/api/react/hooks-experimental.mdx
  docs/source/api/react/hooks.mdx
  docs/source/caching/cache-interaction.mdx
  docs/source/config.json
  docs/source/data/defer.mdx
  docs/source/data/directives.mdx
  docs/source/data/document-transforms.mdx
  docs/source/data/error-handling.mdx
  docs/source/data/fragments.md
  docs/source/data/mutations.mdx
  docs/source/data/queries.mdx
  docs/source/data/suspense.mdx
  docs/source/development-testing/reducing-bundle-size.mdx
  docs/source/development-testing/testing.mdx
  docs/source/get-started.mdx
  docs/source/local-state/local-resolvers.mdx
  docs/source/local-state/reactive-variables.mdx
  docs/source/migrating/apollo-client-3-migration.mdx
  docs/source/why-apollo.mdx
Labels: 📝 documentation

#11136 [docs] make docs edits from @Meschreiber's PR review
  docs/source/api/link/apollo-link-remove-typename.mdx
  docs/source/api/react/hooks-experimental.mdx
  docs/source/data/fragments.md
  docs/source/data/suspense.mdx
Labels: 📝 documentation

#11137 [docs] Update persisted queries link page
  docs/source/api/link/persisted-queries.md
  docs/source/api/link/persisted-queries.mdx
Labels: 📝 documentation

#11162 Ensure subscriptions adhere to the `errorPolicy`
  .changeset/fast-candles-trade.md
  .size-limit.cjs
  src/__tests__/graphqlSubscriptions.ts
  src/core/QueryManager.ts
Labels: 🐞 bug

#11169 Add note about readQuery and ROOT_QUERY to `readQuery` documentation
  docs/source/caching/cache-interaction.mdx
Labels: 📝 documentation

#11180 Fixes issue where refetching an error after an error was returned would hang on loading state
  .changeset/wise-clouds-approve.md
  .size-limit.cjs
  src/core/ObservableQuery.ts
  src/react/cache/QueryReference.ts
  src/react/hooks/__tests__/useBackgroundQuery.test.tsx
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/react/hooks/useQuery.ts
Labels: 🐞 bug, ⏲️ react-suspense

#10072 Fixes #10065: fix race condition in useReactiveVar.
  .changeset/angry-llamas-walk.md
  src/react/hooks/__tests__/useReactiveVar.test.tsx
  src/react/hooks/useReactiveVar.ts
Labels: 🐞 bug
