Repository apollographql/apollo-client, pull requests merged in 2023-12, with the labels that each got.

#11345 `QueryManager.inFlightLinkObservables`: use a strong `Trie`
  .api-reports/api-report-core.md
  .api-reports/api-report-react.md
  .api-reports/api-report-react_components.md
  .api-reports/api-report-react_context.md
  .api-reports/api-report-react_hoc.md
  .api-reports/api-report-react_hooks.md
  .api-reports/api-report-react_ssr.md
  .api-reports/api-report-testing.md
  .api-reports/api-report-testing_core.md
  .api-reports/api-report-utilities.md
  .api-reports/api-report.md
  .changeset/sixty-boxes-rest.md
  .size-limits.json
  src/core/QueryManager.ts
  src/core/__tests__/QueryManager/index.ts
Labels: auto-cleanup

#11363 `useSuspenseQuery`: remove `promiseCache`
  .api-reports/api-report-react.md
  .api-reports/api-report-react_hooks.md
  .api-reports/api-report.md
  .size-limits.json
  src/react/cache/QueryReference.ts
  src/react/cache/SuspenseCache.ts
  src/react/cache/types.ts
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/react/hooks/useSuspenseQuery.ts
Labels: auto-cleanup

#11366 `useBackgroundQuery`: remove `promiseCache`, work around race condition
  .api-reports/api-report-react.md
  .api-reports/api-report-react_hooks.md
  .api-reports/api-report-utilities.md
  .api-reports/api-report.md
  .size-limits.json
  src/react/cache/QueryReference.ts
  src/react/hooks/__tests__/useBackgroundQuery.test.tsx
  src/react/hooks/__tests__/useLoadableQuery.test.tsx
  src/react/hooks/useBackgroundQuery.ts
  src/react/hooks/useLoadableQuery.ts
  src/react/hooks/useReadQuery.ts
  src/testing/internal/profile/profile.tsx
  src/utilities/index.ts
Labels: auto-cleanup

#11416 copy ApiDoc folder from docs repo
  .prettierignore
  docs/shared/ApiDoc/Context.js
  docs/shared/ApiDoc/DocBlock.js
  docs/shared/ApiDoc/Function.js
  docs/shared/ApiDoc/Heading.js
  docs/shared/ApiDoc/InterfaceDetails.js
  docs/shared/ApiDoc/ParameterTable.js
  docs/shared/ApiDoc/PropertySignatureTable.js
  docs/shared/ApiDoc/ResponsiveGrid.js
  docs/shared/ApiDoc/index.js
  docs/shared/ApiDoc/mdToReact.js
  docs/source/api/core/ApolloClient.mdx
  netlify.toml
Labels: auto-cleanup

#10804 Allow usage of WeakMap in React Native Hermes
  .changeset/unlucky-rats-decide.md
  .size-limits.json
  src/utilities/common/canUse.ts
Labels: auto-cleanup

#11369 Persisted Query Link: improve memory management
  .api-reports/api-report-link_persisted-queries.md
  .changeset/thick-tips-cry.md
  .size-limits.json
  src/link/persisted-queries/__tests__/persisted-queries.test.ts
  src/link/persisted-queries/__tests__/react.test.tsx
  src/link/persisted-queries/index.ts
Labels: auto-cleanup

#11408 add central configuration for Apollo Client cache sizes
  .api-reports/api-report-cache.md
  .api-reports/api-report-core.md
  .api-reports/api-report-react.md
  .api-reports/api-report-react_components.md
  .api-reports/api-report-react_context.md
  .api-reports/api-report-react_hoc.md
  .api-reports/api-report-react_hooks.md
  .api-reports/api-report-react_ssr.md
  .api-reports/api-report-testing.md
  .api-reports/api-report-testing_core.md
  .api-reports/api-report-utilities.md
  .api-reports/api-report.md
  .size-limits.json
  api-extractor.json
  src/__tests__/__snapshots__/exports.ts.snap
  src/cache/core/cache.ts
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/__tests__/readFromStore.ts
  src/cache/inmemory/fragmentRegistry.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/readFromStore.ts
  src/cache/inmemory/types.ts
  src/core/QueryManager.ts
  src/link/persisted-queries/index.ts
  src/link/remove-typename/removeTypenameFromVariables.ts
  src/react/parser/index.ts
  src/utilities/caching/__tests__/sizes.test.ts
  src/utilities/caching/caches.ts
  src/utilities/caching/index.ts
  src/utilities/caching/sizes.ts
  src/utilities/common/canonicalStringify.ts
  src/utilities/graphql/DocumentTransform.ts
  src/utilities/graphql/print.ts
  src/utilities/index.ts
Labels: auto-cleanup

#11409 experimental `ApolloClient.getMemoryInternals` helper
  .api-reports/api-report-cache.md
  .api-reports/api-report-core.md
  .api-reports/api-report-link_batch-http.md
  .api-reports/api-report-link_batch.md
  .api-reports/api-report-link_context.md
  .api-reports/api-report-link_core.md
  .api-reports/api-report-link_error.md
  .api-reports/api-report-link_http.md
  .api-reports/api-report-link_persisted-queries.md
  .api-reports/api-report-link_remove-typename.md
  .api-reports/api-report-link_retry.md
  .api-reports/api-report-link_schema.md
  .api-reports/api-report-link_subscriptions.md
  .api-reports/api-report-link_ws.md
  .api-reports/api-report-react.md
  .api-reports/api-report-react_components.md
  .api-reports/api-report-react_context.md
  .api-reports/api-report-react_hoc.md
  .api-reports/api-report-react_hooks.md
  .api-reports/api-report-react_ssr.md
  .api-reports/api-report-testing.md
  .api-reports/api-report-testing_core.md
  .api-reports/api-report-utilities.md
  .api-reports/api-report.md
  .changeset/wet-forks-rhyme.md
  .size-limits.json
  src/cache/core/cache.ts
  src/cache/inmemory/inMemoryCache.ts
  src/core/ApolloClient.ts
  src/core/QueryInfo.ts
  src/link/core/ApolloLink.ts
  src/link/persisted-queries/index.ts
  src/link/remove-typename/removeTypenameFromVariables.ts
  src/react/parser/index.ts
  src/utilities/caching/__tests__/getMemoryInternals.ts
  src/utilities/caching/getMemoryInternals.ts
  src/utilities/common/canonicalStringify.ts
  src/utilities/graphql/DocumentTransform.ts
  src/utilities/graphql/print.ts
Labels: auto-cleanup

#11410 feat: Allow returning `IGNORE` sentinel from `optimisticResponse` functions to support bailing-out from the optimistic update
  .api-reports/api-report-core.md
  .api-reports/api-report-react.md
  .api-reports/api-report-react_components.md
  .api-reports/api-report-react_context.md
  .api-reports/api-report-react_hoc.md
  .api-reports/api-report-react_hooks.md
  .api-reports/api-report-react_ssr.md
  .api-reports/api-report-testing.md
  .api-reports/api-report-testing_core.md
  .api-reports/api-report-utilities.md
  .api-reports/api-report.md
  .changeset/mighty-coats-check.md
  .size-limits.json
  docs/shared/mutation-options.mdx
  src/__tests__/optimistic.ts
  src/cache/core/types/common.ts
  src/core/QueryManager.ts
  src/core/watchQueryOptions.ts
Labels: 🧞‍♂️ enhancement, 🧶 minor-release, 🥚 backwards-compatible

#11412 Add the ability to preload a query outside of React
  .api-reports/api-report-core.md
  .api-reports/api-report-react.md
  .api-reports/api-report-react_components.md
  .api-reports/api-report-react_context.md
  .api-reports/api-report-react_hoc.md
  .api-reports/api-report-react_hooks.md
  .api-reports/api-report-react_ssr.md
  .api-reports/api-report-testing.md
  .api-reports/api-report-testing_core.md
  .api-reports/api-report-utilities.md
  .api-reports/api-report.md
  .changeset/dirty-tigers-matter.md
  .changeset/rare-snakes-melt.md
  .size-limits.json
  config/inlineInheritDoc.ts
  config/jest.config.js
  src/__tests__/__snapshots__/exports.ts.snap
  src/core/ObservableQuery.ts
  src/core/QueryInfo.ts
  src/react/cache/QueryReference.ts
  src/react/cache/__tests__/QueryReference.test.ts
  src/react/hooks/__tests__/useBackgroundQuery.test.tsx
  src/react/hooks/__tests__/useQueryRefHandlers.test.tsx
  src/react/hooks/index.ts
  src/react/hooks/useBackgroundQuery.ts
  src/react/hooks/useLoadableQuery.ts
  src/react/hooks/useQueryRefHandlers.ts
  src/react/hooks/useReadQuery.ts
  src/react/index.ts
  src/react/query-preloader/__tests__/createQueryPreloader.test.tsx
  src/react/query-preloader/createQueryPreloader.ts
  src/testing/internal/index.ts
  src/testing/internal/renderHelpers.tsx
  src/testing/internal/scenarios/index.ts
  src/testing/matchers/index.d.ts
  src/testing/matchers/index.ts
  src/testing/matchers/toBeDisposed.ts
Labels: 🥚 backwards-compatible, ⏲️ react-suspense, auto-cleanup

#11435 deprecate `canonizeResults`
  .api-reports/api-report-cache.md
  .api-reports/api-report-core.md
  .api-reports/api-report-react.md
  .api-reports/api-report-react_components.md
  .api-reports/api-report-react_context.md
  .api-reports/api-report-react_hoc.md
  .api-reports/api-report-react_hooks.md
  .api-reports/api-report-react_ssr.md
  .api-reports/api-report-testing.md
  .api-reports/api-report-testing_core.md
  .api-reports/api-report-utilities.md
  .api-reports/api-report.md
  .changeset/tough-timers-begin.md
  docs/shared/useBackgroundQuery-options.mdx
  docs/shared/useFragment-options.mdx
  docs/shared/useSuspenseQuery-options.mdx
  docs/source/api/cache/InMemoryCache.mdx
  docs/source/api/react/hooks.mdx
  docs/source/caching/garbage-collection.mdx
  src/cache/core/types/Cache.ts
  src/cache/core/types/DataProxy.ts
  src/cache/inmemory/types.ts
  src/core/watchQueryOptions.ts
  src/react/types/types.ts
Labels: auto-cleanup

#11436 Remove docs changeset to avoid patch change
  .changeset/fuzzy-eyes-lick.md
Labels: auto-cleanup

#11437 Rewrite `useBackgroundQuery` tests to use Profiler
  .size-limits.json
  src/react/hooks/__tests__/useBackgroundQuery.test.tsx
  src/react/hooks/__tests__/useQueryRefHandlers.test.tsx
  src/testing/internal/scenarios/index.ts
Labels: 🥚 backwards-compatible, auto-cleanup

#11438 Remove `retain` call from `useBackgroundQuery` to allow for auto disposal
  .changeset/wise-news-grab.md
  .size-limits.json
  src/react/hooks/__tests__/useBackgroundQuery.test.tsx
  src/react/hooks/useBackgroundQuery.ts
Labels: auto-cleanup

#11078 ObservableQuery: only report results for the current variables
  .changeset/smooth-plums-shout.md
  .size-limits.json
  src/__tests__/mutationResults.ts
  src/core/ObservableQuery.ts
  src/core/__tests__/ObservableQuery.ts
  src/react/hooks/__tests__/useQuery.test.tsx
  src/testing/internal/ObservableStream.ts
Labels: auto-cleanup

#11443 add deprecation warnings for HOC and Render Prop docblocks
  .api-reports/api-report-react_components.md
  .api-reports/api-report-react_hoc.md
  .changeset/chatty-comics-yawn.md
  src/react/components/Mutation.tsx
  src/react/components/Query.tsx
  src/react/components/Subscription.tsx
  src/react/hoc/graphql.tsx
  src/react/hoc/mutation-hoc.tsx
  src/react/hoc/query-hoc.tsx
  src/react/hoc/subscription-hoc.tsx
  src/react/hoc/withApollo.tsx
Labels: auto-cleanup

#11415 add a "memory management" documentation page
  .api-reports/api-report-core.md
  .api-reports/api-report-react.md
  .api-reports/api-report-react_components.md
  .api-reports/api-report-react_context.md
  .api-reports/api-report-react_hoc.md
  .api-reports/api-report-react_hooks.md
  .api-reports/api-report-react_internal.md
  .api-reports/api-report-react_ssr.md
  .api-reports/api-report-testing.md
  .api-reports/api-report-testing_core.md
  .api-reports/api-report-utilities.md
  .api-reports/api-report.md
  config/apiExtractor.ts
  docs/shared/ApiDoc/DocBlock.js
  docs/shared/ApiDoc/PropertySignatureTable.js
  docs/source/caching/memory-management.mdx
  docs/source/config.json
  src/core/ApolloClient.ts
  src/utilities/caching/sizes.ts
Labels: auto-cleanup

#11442 Remove `retain` from `useLoadableQuery` to allow for auto disposal
  .changeset/late-rabbits-protect.md
  .size-limits.json
  src/react/hooks/__tests__/useLoadableQuery.test.tsx
  src/react/hooks/useLoadableQuery.ts
Labels: auto-cleanup
