Repository apollographql/apollo-client, pull requests merged in 2023-05, with the labels that each got.

#10829 fix: throw errors when errors are returned after calling `refetch`
  config/bundlesize.ts
  src/__tests__/__snapshots__/exports.ts.snap
  src/react/cache/QuerySubscription.ts
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
Labels: ⏲️ react-suspense

#10766 Better `TData` types when using `returnPartialData` or a different `errorPolicy`
  .changeset/sharp-trees-cough.md
  .prettierignore
  package-lock.json
  package.json
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/react/hooks/useSuspenseQuery.ts
  src/react/types/types.ts
  src/utilities/index.ts
  src/utilities/types/DeepOmit.ts
  src/utilities/types/DeepPartial.ts
  src/utilities/types/Primitive.ts
Labels: ⏲️ react-suspense

#10833 chore: make tests more resilient to intermittent failures
  src/react/components/__tests__/client/Mutation.test.tsx
  src/react/components/__tests__/client/Query.test.tsx
  src/react/hoc/__tests__/queries/lifecycle.test.tsx
  src/react/hoc/__tests__/queries/skip.test.tsx
Labels: 🔬 testing-utilities

#10755 feat: add `useBackgroundQuery` and `useReadQuery` Suspense hooks
  .changeset/seven-onions-burn.md
  .prettierignore
  .size-limit.cjs
  config/bundlesize.ts
  config/jest.config.js
  src/__tests__/__snapshots__/exports.ts.snap
  src/react/cache/QueryReference.ts
  src/react/cache/SuspenseCache.ts
  src/react/hooks/__tests__/useBackgroundQuery.test.tsx
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/react/hooks/index.ts
  src/react/hooks/useBackgroundQuery.ts
  src/react/hooks/useSuspenseQuery.ts
Labels: 🧞‍♂️ enhancement, 🧶 minor-release, ⏲️ react-suspense

#10885 docs: add directives page and update docs nav
  docs/source/api/react/hooks-experimental.mdx
  docs/source/config.json
  docs/source/data/defer.mdx
  docs/source/data/directives.mdx
Labels: 📝 documentation

#10888 Use `optimism` 0.17.4
  .changeset/small-pots-applaud.md
  package-lock.json
  package.json
Labels: 🐞 bug, :christmas_tree: dependencies

#10890 More efficient implementation when conditionally stripping typename from variables
  src/link/remove-typename/__tests__/removeTypenameFromVariables.ts
  src/link/remove-typename/removeTypenameFromVariables.ts
  src/utilities/common/__tests__/omitDeep.ts
  src/utilities/common/__tests__/stripTypename.ts
  src/utilities/common/omitDeep.ts
  src/utilities/common/stripTypename.ts
  src/utilities/index.ts
Labels: :racehorse: performance

#10509 Custom document transforms
  .changeset/warm-pandas-cry.md
  .git-blame-ignore-revs
  .prettierignore
  .size-limit.cjs
  src/__tests__/__snapshots__/exports.ts.snap
  src/__tests__/client.ts
  src/cache/inmemory/__tests__/fragmentRegistry.ts
  src/cache/inmemory/inMemoryCache.ts
  src/config/jest/setup.ts
  src/core/ApolloClient.ts
  src/core/DocumentTransform.ts
  src/core/LocalState.ts
  src/core/ObservableQuery.ts
  src/core/QueryManager.ts
  src/core/__tests__/DocumentTransform.ts
  src/core/__tests__/ObservableQuery.ts
  src/core/__tests__/QueryManager/links.ts
  src/core/index.ts
  src/core/types.ts
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/testing/matchers/index.d.ts
  src/testing/matchers/index.ts
  src/testing/matchers/toMatchDocument.ts
  src/utilities/graphql/operations.ts
  src/utilities/index.ts
Labels: 🧞‍♂️ enhancement
