Repository apollographql/apollo-client, pull requests merged in 2023-04, with the labels that each got.

#10714 chore: document change in cache-and-network behavior in v3
  docs/source/migrating/apollo-client-3-migration.mdx
Labels: 📝 documentation

#10716 chore: update Retry Link docs with reference to onError link
  docs/source/api/link/apollo-link-retry.md
Labels: 📝 documentation

#10729 chore: run remaining skipped tests with React 18
  config/jest.config.js
  src/react/components/__tests__/client/Query.test.tsx
  src/react/hoc/__tests__/mutations/queries.test.tsx
  src/react/hoc/__tests__/mutations/recycled-queries.test.tsx
  src/react/hoc/__tests__/queries/errors.test.tsx
  src/react/hoc/__tests__/queries/lifecycle.test.tsx
  src/react/hoc/__tests__/queries/loading.test.tsx
  src/react/hoc/__tests__/queries/skip.test.tsx
Labels: 🔬 testing-utilities

#10722 Implement a `@nonreactive` directive for selectively skipping reactive comparisons of query result subtrees
  .changeset/modern-peaches-marry.md
  .eslintrc
  .prettierignore
  config/bundlesize.ts
  src/core/ObservableQuery.ts
  src/core/QueryManager.ts
  src/core/__tests__/equalByQuery.ts
  src/core/equalByQuery.ts
  src/react/hooks/__tests__/compareResults.test.tsx
  src/react/hooks/__tests__/useFragment.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/utilities/graphql/storeUtils.ts
  src/utilities/graphql/transform.ts
Labels: :bulb: idea, 🧞‍♂️ enhancement, 🧪 has-tests, 🥚 backwards-compatible, 🎬 directives

#10735 fix: bug where query is stuck on loading if final chunk contains only `hasNext: false`
  .changeset/serious-feet-sparkle.md
  src/link/http/__tests__/HttpLink.ts
  src/link/http/parseAndCheckHttpResponse.ts
Labels: 🐞 bug, ⏩ @defer

#10700 Add a `queryKey` option for `useSuspenseQuery`
  .changeset/curvy-monkeys-kneel.md
  config/bundlesize.ts
  docs/shared/useSuspenseQuery-options.mdx
  src/react/cache/SuspenseCache.ts
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/react/hooks/useSuspenseQuery.ts
  src/react/types/types.ts
Labels: 🧞‍♂️ enhancement, ⏲️ react-suspense

#10724 Automatically strip `__typename` for input data in `variables`
  .changeset/cyan-insects-love.md
  .prettierignore
  config/bundlesize.ts
  src/__tests__/__snapshots__/exports.ts.snap
  src/link/http/__tests__/HttpLink.ts
  src/link/http/__tests__/selectHttpOptionsAndBody.ts
  src/link/http/selectHttpOptionsAndBody.ts
  src/link/subscriptions/index.ts
  src/utilities/common/__tests__/omitDeep.ts
  src/utilities/common/__tests__/stripTypename.ts
  src/utilities/common/objects.ts
  src/utilities/common/omitDeep.ts
  src/utilities/common/stripTypename.ts
  src/utilities/index.ts
  src/utilities/types/DeepOmit.ts
Labels: 🧞‍♂️ enhancement

#10780 docs: adds `createFragmentRegistry` docs
  docs/source/data/fragments.md
Labels: 📝 documentation

#10790 Remove note about `setVariables` being an internal API
  src/core/ObservableQuery.ts
Labels: 📝 documentation

#10814 chore: generate npm provenance statements
  .github/workflows/release.yml
  .npmrc
Labels: 🧹maintenance

#10815 fix: add permissions contents: read in release workflow
  .github/workflows/release.yml
Labels: 🧹maintenance

#10817 chore: npm provenance for prereleases and snapshot releases
  .github/workflows/prerelease.yml
  .github/workflows/snapshot-release.yml
Labels: 🧹maintenance
