Repository apollographql/apollo-client, pull requests merged in 2023-02, with the labels that each got.

#10500 chore: adds GHA workflow to lock closed + dormant issues
  .github/workflows/lock.yml
Labels: 🧹maintenance

#10362 fix: error when server throws and we are also querying for a local field
  .changeset/small-lemons-grow.md
  src/__tests__/local-state/general.ts
  src/core/LocalState.ts
Labels: 🐞 bug

#7555 Add generic request variables in MockedProvider
  .changeset/gorgeous-buses-laugh.md
  src/link/core/types.ts
  src/testing/core/mocking/mockLink.ts
Labels: 🏓 awaiting-team-response

#10523 fix: unblock snapshot releases on branches in prerelease mode
  .github/workflows/snapshot-release.yml
Labels: 🧹maintenance

#10526 Tolerate undefined `concast.sources` if `complete` called earlier than `concast.start`
  .changeset/shaggy-bees-attack.md
  src/utilities/observables/Concast.ts
  src/utilities/observables/__tests__/Concast.ts
Labels: 🐞 bug, :rose: has-reproduction, 🧪 has-tests

#10521 Simplify `__DEV__` polyfill to use imports instead of global scope
  .changeset/lazy-teachers-sell.md
  config/bundlesize.ts
  config/distSpotFixes.ts
  config/postprocessDist.ts
  config/processInvariants.ts
  src/__tests__/__snapshots__/exports.ts.snap
  src/cache/inmemory/__tests__/roundtrip.ts
  src/cache/inmemory/object-canon.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/readFromStore.ts
  src/cache/inmemory/writeToStore.ts
  src/core/ApolloClient.ts
  src/core/ObservableQuery.ts
  src/core/QueryInfo.ts
  src/core/QueryManager.ts
  src/core/index.ts
  src/link/http/createHttpLink.ts
  src/link/http/responseIterator.ts
  src/react/hoc/__tests__/queries/recomposeWithState.ts
  src/react/hooks/internal/useIsomorphicLayoutEffect.ts
  src/react/hooks/useSubscription.ts
  src/react/hooks/useSuspenseQuery.ts
  src/react/hooks/useSyncExternalStore.ts
  src/utilities/common/maybeDeepFreeze.ts
  src/utilities/globals/DEV.ts
  src/utilities/globals/global.ts
  src/utilities/globals/index.ts
  src/utilities/index.ts
Labels: :bulb: idea, 🛠 tooling, 👩‍🏭 refactor, 🛫 in-progress, 📦 bundle size, 🧩 implementation-detail

#10536 chore: filter issues to lock by created at date
  .github/workflows/lock.yml
Labels: 🧹maintenance

#10541 chore: log output and only process issues in lock workflow
  .github/workflows/lock.yml
Labels: 🧹maintenance

#10538 `useSuspenseQuery` docs
  docs/shared/useSuspenseQuery-options.mdx
  docs/shared/useSuspenseQuery-result.mdx
  docs/source/api/react/hooks-experimental.mdx
Labels: 📝 documentation, ⚛️ React-related, ⏲️ react-suspense

#10557 chore: debug lock action
  .github/workflows/lock.yml
Labels: 🧹maintenance

#10560 Refactor `removeDirectivesFromDocument` to fix AST ordering sensitivities and avoid 1/3 AST traversals
  .changeset/dry-radios-help.md
  .changeset/warm-rivers-develop.md
  config/bundlesize.ts
  src/__tests__/__snapshots__/exports.ts.snap
  src/__tests__/local-state/resolvers.ts
  src/cache/inmemory/helpers.ts
  src/utilities/common/arrays.ts
  src/utilities/graphql/__tests__/transform.ts
  src/utilities/graphql/transform.ts
Labels: :racehorse: performance, 🧞‍♂️ enhancement, 🧩 implementation-detail, 🧪 has-tests, 🥚 backwards-compatible

#10565 Remove prerelease check workflow, update release workflow
  .github/workflows/check-prerelease.yml
  .github/workflows/release.yml
Labels: 🧹maintenance

#10568 chore: specify owner and head repo in snapshot release action
  .github/workflows/snapshot-release.yml
Labels: 🧹maintenance

#10584 chore: run lock workflow daily
  .github/workflows/lock.yml
Labels: 🧹maintenance

#9124 Make client writeFragment and writeQuery behaviour consistent with cache
  .changeset/swift-points-mate.md
  src/cache/core/types/DataProxy.ts
  src/core/ApolloClient.ts
Labels: 🛫 in-progress

#9330 write a test for a change in ApolloClient.refetchQueries error handling
  src/__tests__/ApolloClient.ts
Labels: 🏓 awaiting-team-response

#9438 Fix: Support useMutation client param passed to execute function
  .changeset/curly-countries-beg.md
  docs/shared/mutation-result.mdx
  src/react/hooks/__tests__/useMutation.test.tsx
  src/react/hooks/useMutation.ts
Labels: 🏓 awaiting-team-response

#10589 chore: fix link to `CONTRIBUTING.md`
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🧹maintenance

#10591 chore: add ApolloLink.split example
  docs/source/api/link/introduction.mdx
Labels: 📝 documentation

#10588 chore: narrow types of `getFromAST.ts` with type predicates
  src/utilities/graphql/getFromAST.ts
Labels: ⛑ TypeScript, 🧞‍♂️ enhancement, 🏓 awaiting-team-response

#10594 `useSuspenseCache`: add `suspenseCache` option
  .changeset/curvy-dragons-talk.md
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/react/hooks/useSuspenseCache.ts
  src/react/hooks/useSuspenseQuery.ts
  src/react/types/types.ts
Labels: ⏲️ react-suspense
