Repository apollographql/apollo-client, pull requests merged in 2023-01, with the labels that each got.

#10412 chore: update PR template with link to CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🧞‍♂️ enhancement

#10415 Migrate away from `@testing-library/react-hooks`
  config/jest.config.js
  package-lock.json
  package.json
  patches/@testing-library+react-12+12.1.5.patch
  src/react/components/__tests__/client/Mutation.test.tsx
  src/react/hooks/__tests__/useFragment.test.tsx
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/__tests__/useMutation.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/__tests__/useReactiveVar.test.tsx
  src/react/hooks/__tests__/useSubscription.test.tsx
  src/testing/react/__tests__/mockSubscriptionLink.test.tsx
Labels: 🛠 tooling, 🔬 testing-utilities

#10424 chore: fix flaky tests on CI
  .circleci/config.yml
  .eslintrc
  package-lock.json
  package.json
  src/__tests__/client.ts
  src/cache/inmemory/__tests__/cache.ts
  src/core/__tests__/ObservableQuery.ts
  src/link/persisted-queries/__tests__/persisted-queries.test.ts
  src/link/persisted-queries/__tests__/react.test.tsx
  src/react/components/__tests__/client/Mutation.test.tsx
  src/react/components/__tests__/client/Query.test.tsx
  src/react/context/__tests__/ApolloConsumer.test.tsx
  src/react/context/__tests__/ApolloProvider.test.tsx
  src/react/hoc/__tests__/mutations/index.test.tsx
  src/react/hoc/__tests__/mutations/queries.test.tsx
  src/react/hoc/__tests__/queries/errors.test.tsx
  src/react/hoc/__tests__/queries/index.test.tsx
  src/react/hoc/__tests__/queries/lifecycle.test.tsx
  src/react/hoc/__tests__/queries/loading.test.tsx
  src/react/hoc/__tests__/queries/observableQuery.test.tsx
  src/react/hoc/__tests__/subscriptions/subscriptions.test.tsx
  src/react/hooks/__tests__/useApolloClient.test.tsx
  src/react/hooks/__tests__/useFragment.test.tsx
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/__tests__/useMutation.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/__tests__/useReactiveVar.test.tsx
  src/react/hooks/__tests__/useSubscription.test.tsx
  src/react/ssr/__tests__/useQuery.test.tsx
  src/testing/react/__tests__/MockedProvider.test.tsx
  src/testing/react/__tests__/mockSubscriptionLink.test.tsx
Labels: 🔬 testing-utilities

#10435 chore: fix prerelease notification and upgrade to rich markdown
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
Labels: 🧹maintenance

#10402 Improve context types
  .changeset/spotty-kings-unite.md
  src/__tests__/ApolloClient.ts
  src/core/types.ts
  src/core/watchQueryOptions.ts
  src/link/context/index.ts
  src/link/core/types.ts
Labels: 🏓 awaiting-team-response

#10468 chore: fix netlify ignore script
  netlify.toml
Labels: 🧹maintenance

#10467 chore: prevent actions from running on forks
  .github/workflows/close-stale-issues.yml
  .github/workflows/release.yml
Labels: 🧹maintenance

#10471 Fix headers type (extends #9042)
  .changeset/proud-months-dance.md
  src/link/batch-http/__tests__/batchHttpLink.ts
  src/link/http/createHttpLink.ts
  src/link/http/selectHttpOptionsAndBody.ts
Labels: ⛑ TypeScript, 🛫 in-progress

#10470 Upgrades to TypeScript 4.9.4
  .changeset/fuzzy-items-hunt.md
  package-lock.json
  package.json
  src/cache/inmemory/inMemoryCache.ts
  src/core/ApolloClient.ts
  src/core/ObservableQuery.ts
  src/core/QueryManager.ts
  src/core/__tests__/QueryManager/index.ts
  src/core/__tests__/fetchPolicies.ts
  src/core/watchQueryOptions.ts
  src/link/http/iterators/reader.ts
  src/link/http/parseAndCheckHttpResponse.ts
  src/react/components/Query.tsx
  src/react/components/Subscription.tsx
  src/react/components/types.ts
  src/react/hoc/__tests__/ssr/getDataFromTree.test.tsx
  src/react/hoc/graphql.tsx
  src/react/hoc/mutation-hoc.tsx
  src/react/hoc/query-hoc.tsx
  src/react/hoc/subscription-hoc.tsx
  src/react/hoc/types.ts
  src/react/hooks/useLazyQuery.ts
  src/react/hooks/useQuery.ts
  src/react/hooks/useSubscription.ts
  src/react/ssr/RenderPromises.ts
  src/react/types/types.ts
  src/utilities/common/cloneDeep.ts
  src/utilities/common/errorHandling.ts
  src/utilities/common/incrementalResult.ts
  src/utilities/common/mergeOptions.ts
  src/utilities/policies/pagination.ts
Labels: ⛑ TypeScript

#10480 chore: adds changeset snapshot action
  .github/workflows/snapshot-release.yml
Labels: 🧹maintenance

#9573 Fields without `@client` directive should not be resolved locally
  .changeset/twenty-lemons-cover.md
  config/bundlesize.ts
  src/__tests__/local-state/resolvers.ts
  src/core/LocalState.ts
Labels: 🏓 awaiting-team-response
