Repository apollographql/apollo-client, pull requests merged in 2023-09, with the labels that each got.

#11186 Fixes race condition when changing back to initial variables before request finishes
  .changeset/odd-beers-perform.md
  src/core/QueryInfo.ts
  src/core/QueryManager.ts
  src/core/__tests__/ObservableQuery.ts
Labels: 🐞 bug

#11187 chore: add documentation about polyfills needed to use text streaming in RN
  docs/source/data/defer.mdx
  docs/source/data/directives.mdx
  docs/source/data/subscriptions.mdx
  docs/source/integrations/react-native.md
Labels: 📝 documentation

#10967 Added 'Customizing Type Policies' Segment in cache-configuration.mdx #10933
  docs/source/caching/cache-configuration.mdx
Labels: 📝 documentation

#10792 Handle non-src dirs for TypeScript documents
  docs/source/development-testing/static-typing.md
Labels: 📝 documentation

#11202 Prevent `QueryInfo#markResult` mutation of `result.data` and return cache data consistently whether complete or incomplete
  .changeset/shaggy-ears-scream.md
  .size-limit.cjs
  src/__tests__/client.ts
  src/cache/inmemory/__tests__/client.ts
  src/core/QueryInfo.ts
  src/core/QueryManager.ts
  src/core/__tests__/QueryManager/index.ts
  src/react/hooks/__tests__/useQuery.test.tsx
Labels: 🐞 bug, 🧪 has-tests, 💸 caching

#11178 Feature request 241: reuse mocks in MockLink / MockedProvider
  .api-reports/api-report-testing.md
  .api-reports/api-report-testing_core.md
  .changeset/yellow-flies-repeat.md
  .github/workflows/api-extractor.yml
  .size-limit.cjs
  docs/source/development-testing/testing.mdx
  package-lock.json
  package.json
  src/testing/core/mocking/mockLink.ts
  src/testing/react/__tests__/MockedProvider.test.tsx
Labels: 🔬 testing-utilities
