Repository apollographql/apollo-client, pull requests merged in 2023-07, with the labels that each got.

#11032 Throw errors returned from incremental chunks when error policy is `none`
  .changeset/sour-weeks-suffer.md
  src/react/cache/QueryReference.ts
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/utilities/promises/decoration.ts
Labels: ⏲️ react-suspense

#11025 Handle changed suspense query options
  .changeset/ten-cherries-clap.md
  .size-limit.cjs
  src/core/ObservableQuery.ts
  src/react/cache/QueryReference.ts
  src/react/hooks/__tests__/useBackgroundQuery.test.tsx
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/react/hooks/useBackgroundQuery.ts
  src/react/hooks/useSuspenseQuery.ts
Labels: ⏲️ react-suspense

#11035 Incrementally re-render results after `refetch` or `skip` when using `@defer` with `useSuspenseQuery`
  .changeset/orange-suns-check.md
  .prettierignore
  .size-limit.cjs
  src/react/cache/QueryReference.ts
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/react/hooks/useBackgroundQuery.ts
  src/react/hooks/useSuspenseQuery.ts
Labels: ⏲️ react-suspense

#11045 Dispose of the `queryRef` when changing to previously used variables to allow the `InMemoryCache` to determine cached behavior
  .changeset/nice-eyes-return.md
  .size-limit.cjs
  src/react/cache/QueryReference.ts
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/react/hooks/internal/index.ts
  src/react/hooks/internal/useStrictModeSafeCleanupEffect.ts
  src/react/hooks/useBackgroundQuery.ts
  src/react/hooks/useSuspenseQuery.ts
Labels: ⏲️ react-suspense

#11071 Update operation helpers to use raw strings instead of OperationTypeNode
  .changeset/seven-needles-remember.md
  src/utilities/graphql/operations.ts
Labels: 🐞 bug

#11072 chore: add note about React 18 automatic batching to useSubscription docs
  docs/source/api/react/hooks.mdx
Labels: 📝 documentation, 🛎 subscriptions

#11086 Fix stuck pending state when refetching a query that returns a result that is deeply equal to data in the cache
  .changeset/calm-bears-buy.md
  .size-limit.cjs
  src/react/cache/QueryReference.ts
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
Labels: 🐞 bug, ⏲️ react-suspense

#11100 Update `useFragment` docs
  docs/source/api/react/hooks-experimental.mdx
  docs/source/api/react/hooks.mdx
  docs/source/data/fragments.md
Labels: 📝 documentation

#11107 docs: change old links to react lagacy docs into the new docs
  docs/source/api/react/hooks.mdx
  docs/source/data/mutations.mdx
  docs/source/data/queries.mdx
  docs/source/development-testing/testing.mdx
  docs/source/get-started.mdx
  docs/source/local-state/local-resolvers.mdx
  docs/source/why-apollo.mdx
Labels: 📝 documentation

#11104 Add docs for `removeTypenameFromVariables` link
  docs/source/api/link/apollo-link-remove-typename.mdx
  docs/source/config.json
Labels: 📝 documentation

#11092 document `globalThis.__DEV__`
  .prettierignore
  docs/source/config.json
  docs/source/development-testing/reducing-bundle-size.mdx
Labels: 📝 documentation
