Repository apollographql/apollo-client, pull requests merged in 2024-08, with the labels that each got.

#11974 Fix `fetchMore` for queries with `no-cache` fetch policies
  .changeset/nice-worms-juggle.md
  .changeset/pink-horses-pay.md
  .changeset/short-scissors-speak.md
  .size-limits.json
  docs/source/pagination/core-api.mdx
  src/core/ObservableQuery.ts
  src/react/hooks/__tests__/useQuery.test.tsx
  src/testing/internal/scenarios/index.ts
Labels: auto-cleanup

#11984 Fix issue where multiple fetches might report `data` if result contained errors
  .changeset/fluffy-impalas-cross.md
  .size-limits.json
  src/core/QueryManager.ts
  src/react/hooks/__tests__/useQuery.test.tsx
Labels: 🐞 bug

#11989 Fix a potential crash when calling `clearStore` while a query was running.
  .changeset/pink-guests-vanish.md
  .size-limits.json
  src/core/ObservableQuery.ts
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/utilities/observables/Concast.ts
Labels: auto-cleanup

#11992 renovate: don't request reviewers
  renovate.json
Labels: auto-cleanup

#11994 Fix issue returning arrays from cache.modify modifier functions when the array contains a union type
  .api-reports/api-report-cache.api.md
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/grumpy-pandas-pump.md
  .changeset/shaggy-lions-brake.md
  src/cache/core/__tests__/cache.ts
  src/cache/core/types/common.ts
  src/cache/inmemory/entityStore.ts
Labels: auto-cleanup

#11998 docs: Update suspense.mdx
  docs/source/data/suspense.mdx
Labels: auto-cleanup

#12005 Add Summit callout
  docs/source/get-started.mdx
  docs/source/index.mdx
Labels: auto-cleanup

#12016 Always retain `__typename` during data masking
  src/core/__tests__/masking.test.ts
  src/core/masking.ts
Labels: auto-cleanup

#12014 [Data masking] Fix bug where masked field could be returned in parent query
  .size-limits.json
  src/core/__tests__/masking.test.ts
  src/core/masking.ts
Labels: 🐞 bug, 🎭 data-masking

#12015 Add some tests for `watchFragment` for nested fragments and the fragment registry
  src/__tests__/ApolloClient.ts
Labels: 🧪 has-tests, auto-cleanup

#12027 Type `MutationResult.reset` as an arrow function
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report.api.md
  .changeset/modern-cows-tease.md
  src/react/types/types.ts
Labels: auto-cleanup

#12020 Remove double initialization and unneeded useLazyRef from useFragment to avoid write to ref in render
  .changeset/tough-geese-sing.md
  .size-limits.json
  src/react/hooks/internal/index.ts
  src/react/hooks/internal/useLazyRef.ts
  src/react/hooks/useFragment.ts
Labels: 🧞‍♂️ enhancement, auto-cleanup

#12029 [Data masking] Ensure `@unmask` can be used with the fragment registry
  .api-reports/api-report-cache.api.md
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .size-limits.json
  src/__tests__/dataMasking.ts
  src/cache/core/__tests__/cache.ts
  src/cache/core/cache.ts
  src/cache/index.ts
  src/cache/inmemory/inMemoryCache.ts
  src/core/ApolloClient.ts
  src/core/ObservableQuery.ts
  src/core/QueryManager.ts
  src/core/__tests__/masking.test.ts
  src/core/masking.ts
Labels: 🐞 bug, auto-cleanup, 🎭 data-masking

#12034 [Data masking] Ensure masking algorithm properly handles nulls
  .size-limits.json
  src/core/__tests__/masking.test.ts
  src/core/masking.ts
Labels: 🐞 bug, auto-cleanup, 🎭 data-masking

#12033 [Data masking] Add support for masking `client.query` calls
  .size-limits.json
  src/__tests__/dataMasking.ts
  src/core/QueryManager.ts
Labels: auto-cleanup, 🎭 data-masking

#12038 [Data masking] Mask data returned from subscriptions
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .size-limits.json
  src/__tests__/dataMasking.ts
  src/core/ObservableQuery.ts
  src/core/QueryManager.ts
  src/react/hooks/__tests__/useSubscription.test.tsx
Labels: auto-cleanup, 🎭 data-masking
