Repository apollographql/apollo-client, pull requests merged in 2024-05, with the labels that each got.

#11823 Update API extractor and regenerate the API report
  .api-reports/api-report-react.md
  .api-reports/api-report-react_hooks.md
  .api-reports/api-report-react_internal.md
  .api-reports/api-report.md
  package-lock.json
  package.json
Labels: auto-cleanup

#11821 Fix issue where `queryRef` is recreated unnecessarily in strict mode
  .changeset/lazy-parents-thank.md
  .changeset/seven-forks-own.md
  .size-limits.json
  src/react/hooks/__tests__/useBackgroundQuery.test.tsx
  src/react/hooks/useBackgroundQuery.ts
  src/react/hooks/useReadQuery.ts
  src/react/hooks/useSuspenseQuery.ts
  src/react/internal/cache/QueryReference.ts
Labels: 🐞 bug, ⏲️ react-suspense, auto-cleanup

#11791 [docs] Update explainer around reducing-bundle-size
  docs/source/development-testing/reducing-bundle-size.mdx
Labels: auto-cleanup

#11824 create branded `QueryRef` type without exposed properties
  .api-reports/api-report-react.md
  .api-reports/api-report-react_hooks.md
  .api-reports/api-report-react_internal.md
  .api-reports/api-report.md
  .changeset/late-planets-argue.md
  .circleci/config.yml
  .size-limits.json
  config/inlineInheritDoc.ts
  docs/shared/Overrides/UseLoadableQueryResult.js
  docs/shared/useBackgroundQuery-result.mdx
  docs/source/api/react/hooks.mdx
  docs/source/data/suspense.mdx
  integration-tests/next/package.json
  integration-tests/next/src/app/cc/ApolloWrapper.tsx
  integration-tests/next/src/libs/apolloClient.ts
  src/__tests__/__snapshots__/exports.ts.snap
  src/react/hooks/__tests__/useBackgroundQuery.test.tsx
  src/react/hooks/__tests__/useLoadableQuery.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/__tests__/useQueryRefHandlers.test.tsx
  src/react/hooks/useBackgroundQuery.ts
  src/react/hooks/useLoadableQuery.ts
  src/react/hooks/useQueryRefHandlers.ts
  src/react/hooks/useReadQuery.ts
  src/react/internal/cache/QueryReference.ts
  src/react/internal/cache/__tests__/QueryReference.test.ts
  src/react/internal/cache/__tests__/QueryReference.test.tsx
  src/react/internal/index.ts
  src/react/query-preloader/__tests__/createQueryPreloader.test.tsx
  src/react/query-preloader/createQueryPreloader.ts
  src/react/types/types.ts
  src/testing/matchers/index.d.ts
  src/testing/matchers/toBeDisposed.ts
Labels: auto-cleanup

#11837 Fix issue where a query may not stop polling after unmount when in Strict mode with `cache-and-network` fetch policy
  .changeset/smooth-spoons-cough.md
  .size-limits.json
  src/core/ObservableQuery.ts
  src/react/hooks/__tests__/useQuery.test.tsx
Labels: 🐞 bug, auto-cleanup

#11844 Honor `@nonreactive` with `useFragment` and `cache.watchFragment`
  .changeset/kind-donkeys-clap.md
  src/__tests__/ApolloClient.ts
  src/cache/core/cache.ts
  src/react/hooks/__tests__/useFragment.test.tsx
Labels: auto-cleanup

#11839 Fix issue where a merge function that returns an incomplete result would not allow the client to refetch from network
  .changeset/itchy-dodos-approve.md
  .size-limits.json
  src/core/QueryInfo.ts
  src/react/hooks/__tests__/useQuery.test.tsx
Labels: 🐞 bug, auto-cleanup

#11686 [Data masking] Core data masking algorithm
  src/core/__tests__/masking.test.ts
  src/core/masking.ts
  src/utilities/common/maybeDeepFreeze.ts
  src/utilities/index.ts
Labels: auto-cleanup, 🎭 data-masking

#11848 Ensure covariant behavior: `MockedResponses<X,Y>` should be assignable to `MockedResponse`
  .api-reports/api-report-testing.md
  .api-reports/api-report-testing_core.md
  .changeset/nasty-pens-dress.md
  .size-limits.json
  src/testing/core/mocking/__tests__/mockLink.ts
  src/testing/core/mocking/mockLink.ts
Labels: auto-cleanup

#11860 Fixes #11849, `BatchHttpLink` not monitoring friendly
  .changeset/late-days-give.md
  src/link/batch-http/__tests__/batchHttpLink.ts
  src/link/batch-http/batchHttpLink.ts
Labels: auto-cleanup

#11851 useLazyQuery: fix rules of React violations
  .changeset/shaggy-mirrors-judge.md
  .changeset/stupid-planes-nail.md
  .size-limits.json
  src/react/hooks/useLazyQuery.ts
  src/react/hooks/useQuery.ts
Labels: auto-cleanup

#11852 useMutation: fix rules of React violations
  .changeset/loud-hairs-think.md
  .changeset/mighty-monkeys-explain.md
  .size-limits.json
  src/react/components/__tests__/client/Mutation.test.tsx
  src/react/hoc/__tests__/mutations/lifecycle.test.tsx
  src/react/hooks/useMutation.ts
Labels: auto-cleanup
