Repository apollographql/apollo-client, pull requests merged in 2024-04, with the labels that each got.

#11741 chore: use delimiter in accorance with docs to handle strings with newlines in snapshot release action
  .github/workflows/snapshot-release.yml
Labels: auto-cleanup

#11738 Allow queryRefs to be disposed of synchronously
  .api-reports/api-report-react_internal.md
  .changeset/fuzzy-grapes-pump.md
  .changeset/lovely-mayflies-grab.md
  .size-limits.json
  src/react/hooks/__tests__/useBackgroundQuery.test.tsx
  src/react/hooks/useBackgroundQuery.ts
  src/react/hooks/useReadQuery.ts
  src/react/hooks/useSuspenseQuery.ts
  src/react/internal/cache/QueryReference.ts
  src/react/internal/cache/SuspenseCache.ts
Labels: auto-cleanup

#11745 Devtools - Trigger Error Code PR after npm Release
  .github/workflows/devtools-errorcodes.yml
Labels: auto-cleanup

#11743 Remove alpha designation for query preloading
  .api-reports/api-report-react.md
  .api-reports/api-report-react_hooks.md
  .api-reports/api-report-react_internal.md
  .api-reports/api-report.md
  .changeset/tiny-bugs-tap.md
  .changeset/twelve-apples-vanish.md
  docs/source/data/suspense.mdx
  src/react/internal/cache/QueryReference.ts
  src/react/query-preloader/createQueryPreloader.ts
Labels: auto-cleanup

#11605 Schema-driven testing utilities
  .api-reports/api-report-testing.md
  .api-reports/api-report-testing_core.md
  .changeset/chatty-llamas-switch.md
  .changeset/stupid-bears-cheat.md
  .size-limits.json
  .vscode/launch.json
  config/jest.config.js
  package-lock.json
  package.json
  patches/jest-environment-jsdom+29.7.0.patch
  src/__tests__/__snapshots__/exports.ts.snap
  src/testing/core/__tests__/createProxiedSchema.test.tsx
  src/testing/core/createMockFetch.ts
  src/testing/core/createProxiedSchema.ts
  src/testing/core/index.ts
  src/testing/graphql-tools/LICENSE
  src/testing/graphql-tools/utils.test.ts
  src/testing/graphql-tools/utils.ts
  src/testing/index.ts
Labels: 🔬 testing-utilities, auto-cleanup

#11753 use native AbortController
  config/FixJSDOMEnvironment.js
  src/link/persisted-queries/__tests__/persisted-queries.test.ts
Labels: auto-cleanup

#11751 Use custom jsdom environment instead of patch package to set Response in the environemt
  .size-limits.json
  config/FixJSDOMEnvironment.js
  config/jest.config.js
  patches/jest-environment-jsdom+29.7.0.patch
  src/link/persisted-queries/__tests__/persisted-queries.test.ts
Labels: auto-cleanup

#11754 `watchFragment` fixes
  .api-reports/api-report-cache.md
  .api-reports/api-report-core.md
  .api-reports/api-report.md
  .changeset/old-onions-sleep.md
  .size-limits.json
  src/cache/index.ts
  src/core/ApolloClient.ts
  src/core/index.ts
Labels: auto-cleanup

#11757 Adjust useReadQuery wrapper logic to work with transported objects.
  .changeset/hungry-bobcats-battle.md
  .size-limits.json
  src/react/hooks/useReadQuery.ts
Labels: auto-cleanup

#11769 Fix issue where a network request is made when using `skip`/`skipToken` with `useSuspenseQuery` in strict mode
  .changeset/thick-buttons-juggle.md
  .size-limits.json
  src/react/hooks/__tests__/useBackgroundQuery.test.tsx
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/react/internal/cache/QueryReference.ts
Labels: 🐞 bug, ⏲️ react-suspense, auto-cleanup

#11764 chore: rename `createProxiedSchema` to `createTestSchema`
  .api-reports/api-report-testing.md
  .api-reports/api-report-testing_core.md
  .changeset/green-garlics-protect.md
  config/jest.config.js
  src/__tests__/__snapshots__/exports.ts.snap
  src/testing/core/__tests__/createTestSchema.test.tsx
  src/testing/core/createSchemaFetch.ts
  src/testing/core/createTestSchema.ts
  src/testing/core/index.ts
Labels: 🔬 testing-utilities, auto-cleanup

#11777 Call `createMockSchema` inside `createTestSchema`
  .api-reports/api-report-testing.md
  .api-reports/api-report-testing_core.md
  .changeset/spotty-garlics-knock.md
  src/__tests__/__snapshots__/exports.ts.snap
  src/testing/core/__tests__/createTestSchema.test.tsx
  src/testing/core/createTestSchema.ts
  src/testing/index.ts
Labels: 🔬 testing-utilities, auto-cleanup

#11779 suggestion: mock global `fetch` explicitly
  .api-reports/api-report-testing.md
  .api-reports/api-report-testing_core.md
  .size-limits.json
  src/testing/core/__tests__/__snapshots__/createTestSchema.test.tsx.snap
  src/testing/core/__tests__/createTestSchema.test.tsx
  src/testing/core/createSchemaFetch.ts
Labels: 🔬 testing-utilities, auto-cleanup

#11783 Move new testing utilities to their own entrypoint
  .api-reports/api-report-testing.md
  .api-reports/api-report-testing_core.md
  .api-reports/api-report-testing_experimental.md
  .changeset/wet-plants-admire.md
  config/entryPoints.js
  src/__tests__/__snapshots__/exports.ts.snap
  src/__tests__/exports.ts
  src/testing/core/index.ts
  src/testing/experimental/__tests__/createTestSchema.test.tsx
  src/testing/experimental/createSchemaFetch.ts
  src/testing/experimental/createTestSchema.ts
  src/testing/experimental/graphql-tools/LICENSE
  src/testing/experimental/graphql-tools/utils.test.ts
  src/testing/experimental/graphql-tools/utils.ts
  src/testing/experimental/index.ts
Labels: 🔬 testing-utilities, auto-cleanup

#11774 Accept min and max delay in `createSchemaFetch` options
  .api-reports/api-report-testing_experimental.md
  .changeset/strong-paws-kneel.md
  config/jest.config.js
  src/testing/experimental/__tests__/createTestSchema.test.tsx
  src/testing/experimental/createSchemaFetch.ts
  src/testing/internal/profile/profile.tsx
Labels: 🔬 testing-utilities, auto-cleanup

#11760 feat: deep merge resolvers
  .changeset/cold-dancers-call.md
  package-lock.json
  package.json
  src/link/persisted-queries/__tests__/persisted-queries.test.ts
  src/testing/experimental/__tests__/createTestSchema.test.tsx
  src/testing/experimental/createTestSchema.ts
Labels: 🔬 testing-utilities, auto-cleanup

#11788 chore: update alessbell/pull-request-comment-branch to v2.1.0
  .github/workflows/snapshot-release.yml
Labels: 🧹maintenance, auto-cleanup

#11794 Require sha when creating snapshot releases on forks
  .github/workflows/snapshot-release.yml
Labels: auto-cleanup

#11802 add return type to `withinDOM` implementation
  src/testing/internal/profile/Render.tsx
Labels: auto-cleanup

#11805 Testing utility docs
  .prettierignore
  docs/source/api/react/hooks-experimental.mdx
  docs/source/config.json
  docs/source/development-testing/schema-driven-testing.mdx
Labels: 🔬 testing-utilities

#11803 Update the `rehackt` dependency to `^0.1.0`
  .changeset/healthy-chairs-sleep.md
  .size-limits.json
  package-lock.json
  package.json
  src/react/hooks/internal/__tests__/useRenderGuard.test.tsx
Labels: auto-cleanup

#11792 AutoCleanedCache: only schedule batched cache cleanup if the cache is full
  .changeset/cuddly-emus-fail.md
  .size-limits.json
  src/utilities/caching/caches.ts
Labels: auto-cleanup

#11756 Fix operation.setContext() type
  .api-reports/api-report-core.md
  .api-reports/api-report-link_batch-http.md
  .api-reports/api-report-link_batch.md
  .api-reports/api-report-link_context.md
  .api-reports/api-report-link_core.md
  .api-reports/api-report-link_error.md
  .api-reports/api-report-link_http.md
  .api-reports/api-report-link_persisted-queries.md
  .api-reports/api-report-link_remove-typename.md
  .api-reports/api-report-link_retry.md
  .api-reports/api-report-link_schema.md
  .api-reports/api-report-link_subscriptions.md
  .api-reports/api-report-link_utils.md
  .api-reports/api-report-link_ws.md
  .api-reports/api-report-react.md
  .api-reports/api-report-react_components.md
  .api-reports/api-report-react_context.md
  .api-reports/api-report-react_hoc.md
  .api-reports/api-report-react_hooks.md
  .api-reports/api-report-react_internal.md
  .api-reports/api-report-react_ssr.md
  .api-reports/api-report-testing.md
  .api-reports/api-report-testing_core.md
  .api-reports/api-report-utilities.md
  .api-reports/api-report.md
  .changeset/strange-needles-suffer.md
  src/link/core/types.ts
  src/link/utils/createOperation.ts
Labels: auto-cleanup

#11799 `RenderPromises`: use `canonicalStringify` to serialize data, use `Trie`
  .changeset/early-pots-rule.md
  src/react/ssr/RenderPromises.ts
  src/react/ssr/__tests__/useQuery.test.tsx
Labels: auto-cleanup

#11820 fix: update link to sandbox in schema-driven testing docs page
  docs/source/development-testing/schema-driven-testing.mdx
Labels: auto-cleanup
