Repository apollographql/apollo-client, pull requests merged in 2024-06, with the labels that each got.

#11877 Add missing name to tuple member (fix TS5084)
  .api-reports/api-report-react.md
  .api-reports/api-report-react_hooks.md
  .api-reports/api-report.md
  .changeset/sharp-cats-taste.md
  src/react/hooks/useLoadableQuery.ts
Labels: auto-cleanup

#11880 [Data masking] Add function to mask fragment data
  src/cache/core/cache.ts
  src/core/__tests__/masking.test.ts
  src/core/masking.ts
Labels: auto-cleanup, 🎭 data-masking

#11511 enable `react-hooks` lint rules
  .changeset/famous-camels-rescue.md
  .eslintrc
  package-lock.json
  package.json
  patches/eslint-plugin-react-hooks+4.6.2.patch
  src/react/hooks/internal/useRenderGuard.ts
  src/react/hooks/useLoadableQuery.ts
  src/react/hooks/useQuery.ts
  src/react/hooks/useQueryRefHandlers.ts
  src/react/hooks/useReadQuery.ts
  src/react/hooks/useSubscription.ts
  src/react/hooks/useSuspenseQuery.ts
  src/react/hooks/useSyncExternalStore.ts
Labels: auto-cleanup

#11888 switch `useRenderGuard` to an approach not accessing React's internals
  .changeset/brown-bikes-divide.md
  .size-limits.json
  src/react/hooks/internal/__tests__/useRenderGuard.test.tsx
  src/react/hooks/internal/useRenderGuard.ts
Labels: auto-cleanup

#11885 Update router terminology
  docs/source/api/link/persisted-queries.mdx
  docs/source/data/defer.mdx
Labels: auto-cleanup

#11329 fix: graphQLErrors in Error Link if networkError.result is an empty string
  .changeset/loud-hounds-heal.md
  src/link/error/__tests__/index.ts
  src/link/error/index.ts
Labels: 🏓 awaiting-team-response

#11900 `useMutation`: use `useIsomorphicLayoutEffect` instead of `useLayoutEffect`
  .changeset/clean-icons-sparkle.md
  .size-limits.json
  src/react/hooks/useMutation.ts
Labels: auto-cleanup

#11906 chore: update TypeScript to 5.5
  .api-reports/api-report-cache.api.md
  .api-reports/api-report-core.api.md
  .api-reports/api-report-dev.api.md
  .api-reports/api-report-errors.api.md
  .api-reports/api-report-link_batch-http.api.md
  .api-reports/api-report-link_batch.api.md
  .api-reports/api-report-link_context.api.md
  .api-reports/api-report-link_core.api.md
  .api-reports/api-report-link_error.api.md
  .api-reports/api-report-link_http.api.md
  .api-reports/api-report-link_persisted-queries.api.md
  .api-reports/api-report-link_remove-typename.api.md
  .api-reports/api-report-link_retry.api.md
  .api-reports/api-report-link_schema.api.md
  .api-reports/api-report-link_subscriptions.api.md
  .api-reports/api-report-link_utils.api.md
  .api-reports/api-report-link_ws.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_parser.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-testing_experimental.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report-utilities_globals.api.md
  .api-reports/api-report-utilities_subscriptions_relay.api.md
  .api-reports/api-report-utilities_subscriptions_urql.api.md
  .api-reports/api-report.api.md
  .changeset/proud-swans-attend.md
  .size-limits.json
  config/apiExtractor.ts
  package-lock.json
  package.json
  src/testing/internal/profile/Render.tsx
Labels: auto-cleanup

#11908 renovate: ignore eslint-plugin-react-compiler
  renovate.json
Labels: auto-cleanup

#11905 Add `.d.cts` files for cjs bundles
  .changeset/nine-icons-destroy.md
  config/prepareDist.js
  package.json
Labels: auto-cleanup

#11911 Allow `undefined` as return value from `cache.modify` modifier function
  .api-reports/api-report-cache.api.md
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/breezy-points-carry.md
  .size-limits.json
  src/cache/core/__tests__/cache.ts
  src/cache/core/types/common.ts
Labels: ⛑ TypeScript
