Repository apollographql/apollo-client, pull requests merged in 2024-03, with the labels that each got.

#11617 Allow QueryManager to intercept hook functionality
  .api-reports/api-report-react_internal.md
  .changeset/curvy-maps-give.md
  .size-limits.json
  config/rollup.config.js
  src/react/hooks/internal/index.ts
  src/react/hooks/internal/wrapHook.ts
  src/react/hooks/useBackgroundQuery.ts
  src/react/hooks/useFragment.ts
  src/react/hooks/useQuery.ts
  src/react/hooks/useReadQuery.ts
  src/react/hooks/useSuspenseQuery.ts
  src/react/internal/index.ts
Labels: auto-cleanup

#11638 Fix additional re-render when calling `fetchMore` from `useSuspenseQuery` when using `startTransition`.
  .changeset/rich-hotels-sniff.md
  .size-limits.json
  src/react/hooks/__tests__/useBackgroundQuery.test.tsx
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/react/internal/cache/QueryReference.ts
  src/testing/internal/scenarios/index.ts
Labels: 🐞 bug, ⏲️ react-suspense

#11636 docs: minor 3.9 docs copyedits
  docs/source/data/suspense.mdx
Labels: auto-cleanup

#11594 fix(workaround): multipart subscriptions that terminate with payload: null
  .changeset/little-squids-watch.md
  .size-limits.json
  src/link/http/__tests__/HttpLink.ts
  src/link/http/parseAndCheckHttpResponse.ts
Labels: auto-cleanup

#11659 Make `useRenderGuard` more resilient to changes in React internals.
  .changeset/early-pens-kick.md
  .size-limits.json
  src/react/hooks/internal/__tests__/useRenderGuard.test.tsx
  src/react/hooks/internal/useRenderGuard.ts
Labels: auto-cleanup

#11653 Update snapshot message format in GitHub comment to make it easier to copy the version
  .github/workflows/snapshot-release.yml
Labels: auto-cleanup

#11663 chore: add minVersion to docs for bailing out of optimistic updates
  docs/source/performance/optimistic-ui.mdx
Labels: 📝 documentation, auto-cleanup

#11693 fix: options links and remove @ link syntax
  .api-reports/api-report-core.md
  .api-reports/api-report-react.md
  .api-reports/api-report-react_components.md
  .api-reports/api-report-react_context.md
  .api-reports/api-report-react_hoc.md
  .api-reports/api-report-react_hooks.md
  .api-reports/api-report-react_internal.md
  .api-reports/api-report-react_ssr.md
  .api-reports/api-report-testing.md
  .api-reports/api-report-testing_core.md
  .api-reports/api-report-utilities.md
  .api-reports/api-report.md
  .size-limits.json
  docs/shared/ApiDoc/PropertySignatureTable.js
  docs/source/api/react/components.mdx
  docs/source/caching/memory-management.mdx
  docs/source/data/mutations.mdx
  docs/source/data/queries.mdx
  docs/source/data/subscriptions.mdx
  src/core/ApolloClient.ts
  src/react/hooks/useFragment.ts
  src/react/internal/cache/QueryReference.ts
  src/react/query-preloader/createQueryPreloader.ts
  src/react/types/types.documentation.ts
Labels: auto-cleanup

#11689 Fix issue with `useFragment` where it returned wrong data when changing the `from` option
  .changeset/flat-singers-kiss.md
  .size-limits.json
  src/react/hooks/__tests__/useFragment.test.tsx
  src/react/hooks/useFragment.ts
Labels: 🐞 bug

#11465 feat: extract watchFragment into separate method on ApolloCache
  .api-reports/api-report-cache.md
  .api-reports/api-report-core.md
  .api-reports/api-report-react.md
  .api-reports/api-report-react_components.md
  .api-reports/api-report-react_context.md
  .api-reports/api-report-react_hoc.md
  .api-reports/api-report-react_hooks.md
  .api-reports/api-report-react_internal.md
  .api-reports/api-report-react_ssr.md
  .api-reports/api-report-testing.md
  .api-reports/api-report-testing_core.md
  .api-reports/api-report-utilities.md
  .api-reports/api-report.md
  .changeset/tasty-pillows-ring.md
  .size-limits.json
  config/inlineInheritDoc.ts
  docs/README.md
  docs/source/api/cache/InMemoryCache.mdx
  docs/source/api/core/ApolloClient.mdx
  docs/source/api/core/ObservableQuery.mdx
  docs/source/caching/cache-interaction.mdx
  netlify.toml
  src/__tests__/ApolloClient.ts
  src/cache/core/cache.ts
  src/core/ApolloClient.ts
  src/react/hooks/useFragment.ts
Labels: 🧞‍♂️ enhancement, 🥚 backwards-compatible, auto-cleanup

#11697 chore: remove NODE_VERSION from netlify.toml to unblock preview deploys
  netlify.toml
Labels: auto-cleanup

#11694 expose `setErrorMessageHandler`
  .api-reports/api-report-dev.md
  .changeset/eleven-doors-rescue.md
  src/__tests__/__snapshots__/exports.ts.snap
  src/dev/index.ts
  src/dev/loadErrorMessageHandler.ts
  src/dev/setErrorMessageHandler.ts
  src/utilities/globals/__tests__/invariantWrappers.test.ts
  src/utilities/globals/invariantWrappers.ts
Labels: auto-cleanup

#11713 Fix issue where setting `defaultOptions` would sometimes break `startTransition` for suspense hooks
  .changeset/tasty-hotels-press.md
  .size-limits.json
  src/react/hooks/__tests__/useBackgroundQuery.test.tsx
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/react/internal/cache/QueryReference.ts
Labels: 🐞 bug, ⏲️ react-suspense, auto-cleanup

#11670 potential optimization - bail out of `executeSubSelectedArray` calls
  .changeset/mean-singers-cheer.md
  .size-limits.json
  src/cache/inmemory/__tests__/readFromStore.ts
  src/cache/inmemory/readFromStore.ts
Labels: auto-cleanup
