Repository apollographql/apollo-client, pull requests merged in 2024-07, with the labels that each got.

#11913 Move check for whether data masking is enabled to `ObservableQuery`
  .api-reports/api-report-cache.api.md
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .size-limits.json
  src/cache/core/__tests__/cache.ts
  src/cache/core/cache.ts
  src/core/ApolloClient.ts
  src/core/ObservableQuery.ts
  src/core/QueryManager.ts
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
Labels: auto-cleanup

#11890 stabilize `useQuery` tests
  .size-limits.json
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
Labels: auto-cleanup

#11863 useSubscription: fix rules of React violations
  .changeset/little-suits-return.md
  .size-limits.json
  src/react/components/__tests__/client/Subscription.test.tsx
  src/react/hoc/__tests__/subscriptions/subscriptions.test.tsx
  src/react/hooks/useSubscription.ts
  src/testing/react/__tests__/mockSubscriptionLink.test.tsx
Labels: auto-cleanup

#11923 Add `subscribeToMore` function to `useBackgroundQuery`, `useQueryRefHandlers`, and `useLoadableQuery`
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report.api.md
  .changeset/angry-ravens-mate.md
  .changeset/chilly-dots-shake.md
  .changeset/slimy-balloons-cheat.md
  .size-limits.json
  src/core/ObservableQuery.ts
  src/react/hooks/__tests__/useBackgroundQuery.test.tsx
  src/react/hooks/__tests__/useLoadableQuery.test.tsx
  src/react/hooks/__tests__/useQueryRefHandlers.test.tsx
  src/react/hooks/useBackgroundQuery.ts
  src/react/hooks/useLoadableQuery.ts
  src/react/hooks/useQueryRefHandlers.ts
  src/react/hooks/useSuspenseQuery.ts
Labels: auto-cleanup

#11806 MockLink: add query default variables if not specified in mock request
  .changeset/fluffy-badgers-rush.md
  src/testing/core/mocking/__tests__/mockLink.ts
  src/testing/core/mocking/mockLink.ts
  src/testing/internal/disposables/enableFakeTimers.ts
  src/testing/internal/disposables/index.ts
Labels: auto-cleanup

#11902 Add `cause` field to `ApolloError`.
  .api-reports/api-report-core.api.md
  .api-reports/api-report-errors.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/flat-onions-guess.md
  .size-limits.json
  src/errors/index.ts
Labels: auto-cleanup

#11626 Call `nextFetchPolicy` with "variables-changed" even if there is a `fetchPolicy` option specified.
  .changeset/tasty-chairs-dress.md
  .size-limits.json
  src/core/ObservableQuery.ts
  src/react/hooks/__tests__/useQuery.test.tsx
  src/tsconfig.json
Labels: auto-cleanup

#11927 Add `restart` function to `useSubscription`
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report.api.md
  .changeset/clever-bikes-admire.md
  .size-limits.json
  src/react/hooks/__tests__/useSubscription.test.tsx
  src/react/hooks/useSubscription.ts
Labels: auto-cleanup

#11936 Add ability to configure a name for the client for use with devtools
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/pink-ants-remember.md
  .size-limits.json
  src/core/ApolloClient.ts
Labels: ⚙️ devtools

#11789 Change usages of the `GraphQLError` type to `GraphQLFormattedError`.
  .api-reports/api-report-core.api.md
  .api-reports/api-report-errors.api.md
  .api-reports/api-report-link_batch-http.api.md
  .api-reports/api-report-link_batch.api.md
  .api-reports/api-report-link_context.api.md
  .api-reports/api-report-link_core.api.md
  .api-reports/api-report-link_error.api.md
  .api-reports/api-report-link_http.api.md
  .api-reports/api-report-link_persisted-queries.api.md
  .api-reports/api-report-link_remove-typename.api.md
  .api-reports/api-report-link_retry.api.md
  .api-reports/api-report-link_schema.api.md
  .api-reports/api-report-link_subscriptions.api.md
  .api-reports/api-report-link_ws.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/slimy-berries-yawn.md
  .eslintrc
  src/__tests__/client.ts
  src/core/ApolloClient.ts
  src/core/QueryInfo.ts
  src/core/types.ts
  src/errors/__tests__/ApolloError.ts
  src/errors/index.ts
  src/link/core/types.ts
  src/link/error/index.ts
  src/link/persisted-queries/index.ts
  src/link/subscriptions/index.ts
  src/react/components/__tests__/client/Mutation.test.tsx
  src/testing/experimental/createSchemaFetch.ts
Labels: auto-cleanup

#11930 Deprecate experimental testing utilities
  .api-reports/api-report-testing_experimental.api.md
  .changeset/weak-ads-develop.md
  src/testing/experimental/createSchemaFetch.ts
  src/testing/experimental/createTestSchema.ts
Labels: auto-cleanup

#11942 Revert "Add back "fix: skip PR creation if no prerelease changesets exist"""
  .github/workflows/prerelease.yml
Labels: auto-cleanup

#11943 Update router terminology
  docs/source/api/link/persisted-queries.mdx
  docs/source/data/defer.mdx
Labels: auto-cleanup

#11926 `watchFragment`: forward additional options to `diffOptions`
  .changeset/good-suns-happen.md
  .size-limits.json
  src/__tests__/ApolloClient.ts
  src/cache/core/cache.ts
Labels: auto-cleanup

#11949 remove deprecated `watchFragment` option, `canonizeResults`
  .api-reports/api-report-cache.api.md
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/curly-vans-draw.md
  src/cache/core/cache.ts
Labels: auto-cleanup

#11948 Update "Who is Apollo"
  README.md
Labels: auto-cleanup

#11937 correctly test for error equality on jest
  .changeset/early-tips-vanish.md
  package-lock.json
  package.json
  patches/pretty-format+29.7.0.patch
  src/__tests__/ApolloClient.ts
  src/__tests__/__snapshots__/graphqlSubscriptions.ts.snap
  src/__tests__/client.ts
  src/config/jest/areApolloErrorsEqual.ts
  src/config/jest/areGraphQlErrorsEqual.ts
  src/config/jest/setup.ts
  src/core/__tests__/ObservableQuery.ts
  src/react/components/__tests__/client/Mutation.test.tsx
  src/react/components/__tests__/client/Query.test.tsx
  src/react/components/__tests__/client/Subscription.test.tsx
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/__tests__/useMutation.test.tsx
  src/testing/experimental/__tests__/createTestSchema.test.tsx
  src/testing/experimental/createSchemaFetch.ts
  src/testing/react/__tests__/MockedProvider.test.tsx
  src/testing/react/__tests__/__snapshots__/MockedProvider.test.tsx.snap
Labels: auto-cleanup

#11951 add React 19 RC to `peerDependencies`
  .changeset/breezy-deers-dream.md
  package-lock.json
  package.json
Labels: auto-cleanup

#11954 optimize `useQuery` result handling
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/proud-humans-begin.md
  .size-limits.json
  src/react/hooks/useQuery.ts
  src/react/types/types.ts
Labels: auto-cleanup

#11920 QueryManager: require all options
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .size-limits.json
  src/__tests__/graphqlSubscriptions.ts
  src/core/QueryManager.ts
  src/core/__tests__/ObservableQuery.ts
  src/core/__tests__/QueryManager/index.ts
  src/core/__tests__/QueryManager/links.ts
  src/core/__tests__/QueryManager/multiple-results.ts
  src/core/__tests__/QueryManager/recycler.ts
  src/testing/core/mocking/mockQueryManager.ts
Labels: auto-cleanup

#11963 patch React 19 for tests to make FALLBACK_THROTTLE_MS configurable
  patches/react-dom-19+19.0.0-rc-378b305958-20240710.patch
  src/config/jest/setup.ts
Labels: auto-cleanup

#11969 Fix incorrect default devtools config
  .changeset/early-spoons-attack.md
  .size-limits.json
  src/core/ApolloClient.ts
Labels: auto-cleanup

#11971 Don't attempt to connect to devtools in non-browser environments
  .changeset/famous-berries-remember.md
  src/core/ApolloClient.ts
Labels: auto-cleanup

#11919 [Data masking] Add `@unmask` directive with field access warnings
  .api-reports/api-report-cache.api.md
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .github/workflows/compare-build-output.yml
  .size-limits.json
  src/__tests__/__snapshots__/exports.ts.snap
  src/__tests__/client.ts
  src/cache/core/__tests__/cache.ts
  src/cache/core/cache.ts
  src/core/ApolloClient.ts
  src/core/ObservableQuery.ts
  src/core/QueryManager.ts
  src/core/__tests__/masking.test.ts
  src/core/masking.ts
  src/testing/core/mocking/mockLink.ts
  src/testing/internal/disposables/index.ts
  src/testing/internal/disposables/withProdMode.ts
  src/utilities/graphql/__tests__/directives.ts
  src/utilities/graphql/directives.ts
  src/utilities/index.ts
Labels: auto-cleanup, 🎭 data-masking

#11975 chore: mark snapshot releases as deprecated in npm registry
  .github/workflows/snapshot-release.yml
Labels: 🧹maintenance, auto-cleanup

#11977 Add TypeScript examples to all subscriptions page code blocks
  .semgrepignore
  docs/source/data/subscriptions.mdx
Labels: 📝 documentation, auto-cleanup

#11980 Fix missing `getServerSnapshot` function for useSubscription
  .changeset/wet-shirts-juggle.md
  .size-limits.json
  src/react/hooks/useSubscription.ts
Labels: auto-cleanup
