Repository apollographql/apollo-client, pull requests merged in 2024-01, with the labels that each got.

#11450 fix `reportErrors` link example in docs
  docs/source/api/link/introduction.mdx
Labels: auto-cleanup

#11460 chore: add docs for relay and urql network adapters
  docs/source/data/subscriptions.mdx
Labels: auto-cleanup

#11461 chore: add docs for skipping an optimistic update via optimisticResponse
  docs/source/performance/optimistic-ui.mdx
Labels: 📝 documentation, auto-cleanup

#11464 Avoid excessive `cache.watch` / unsubscribe on every render in `useFragment`
  .changeset/great-badgers-jog.md
  .size-limits.json
  src/react/hooks/__tests__/useFragment.test.tsx
  src/react/hooks/internal/index.ts
  src/react/hooks/internal/useLazyRef.ts
  src/react/hooks/useFragment.ts
Labels: :racehorse: performance, 👩‍🏭 refactor, ⚛️ React-related, 🥚 backwards-compatible, auto-cleanup

#11470 remove unnecessary check from parseAndCheckHttpResponse
  .changeset/short-badgers-exist.md
  .size-limits.json
  src/link/http/parseAndCheckHttpResponse.ts
Labels: auto-cleanup

#11472 fix: behavior of delay: Infinity in a mock response
  .changeset/fresh-jeans-retire.md
  src/testing/core/mocking/mockLink.ts
  src/testing/react/__tests__/MockedProvider.test.tsx
Labels: 🔬 testing-utilities, auto-cleanup

#11479 ci: SECOPS-2525 - add semgrep job
  .circleci/config.yml
Labels: auto-cleanup

#11495 Increase default memory limits
  .api-reports/api-report-utilities.md
  .changeset/pink-apricots-yawn.md
  .size-limits.json
  src/utilities/caching/sizes.ts
Labels: auto-cleanup

#11489 fix: `networkStatus` update Issue in `useSuspenseQuery` with `cache-and-network` policy
  .changeset/soft-roses-sit.md
  .size-limits.json
  src/react/cache/QueryReference.ts
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
Labels: 🐞 bug, 🥚 backwards-compatible, ⏲️ react-suspense

#11501 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: auto-cleanup

#11507 Add field asking for `@apollo/client` version to our bug issue template
  .github/ISSUE_TEMPLATE/bug.yml
Labels: auto-cleanup

#11508 Add doc comment for `headers` property on ApolloClient
  src/core/ApolloClient.ts
Labels: auto-cleanup

#11152 - Documentation: added some details about cache updates
  docs/source/api/cache/InMemoryCache.mdx
  docs/source/caching/cache-interaction.mdx
Labels: 📝 documentation

#11518 chore: adds user survey link in README and issue close workflow
  .github/workflows/issue-close-user-survey.yml
  .size-limits.json
  README.md
Labels: auto-cleanup

#11523 Document new React APIs in code - Part 2 of 2
  .api-reports/api-report-react.md
  .api-reports/api-report-react_hooks.md
  .api-reports/api-report-react_internal.md
  .api-reports/api-report.md
  .prettierignore
  docs/shared/Overrides/UseLoadableQueryResult.js
  docs/source/api/react/hooks.mdx
  docs/source/api/react/preloading.mdx
  docs/source/config.json
  src/react/hooks/useLoadableQuery.ts
  src/react/hooks/useQueryRefHandlers.ts
  src/react/internal/cache/QueryReference.ts
  src/react/query-preloader/createQueryPreloader.ts
Labels: auto-cleanup

#11529 Add component for API members that are marked as alpha/beta
  docs/shared/ApiDoc/DocBlock.js
  docs/shared/ApiDoc/Function.js
  docs/shared/ApiDoc/PropertySignatureTable.js
  docs/shared/ApiDoc/index.js
Labels: auto-cleanup

#11534 chore: add client-typescript team to CODEOWNERS
  .github/CODEOWNERS
Labels: auto-cleanup

#11512 Document new React APIs in 3.9 - Part 1 of 2
  .size-limits.json
  docs/source/data/suspense.mdx
Labels: auto-cleanup

#11539 chore: only open a prerelease version packages PR when still in prerelease mode
  .github/workflows/prerelease.yml
Labels: auto-cleanup

#11537 3.9 Documentation
  .size-limits.json
  docs/source/data/suspense.mdx
Labels: 📝 documentation, auto-cleanup

#11516 Fix an incorrect string substitution in a warning message.
  .changeset/mighty-seals-perform.md
  src/core/QueryManager.ts
Labels: auto-cleanup

#11545 fix: remove error thrown by inFlightLinkObservables
  .api-reports/api-report-core.md
  .api-reports/api-report-react.md
  .api-reports/api-report-react_components.md
  .api-reports/api-report-react_context.md
  .api-reports/api-report-react_hoc.md
  .api-reports/api-report-react_hooks.md
  .api-reports/api-report-react_internal.md
  .api-reports/api-report-react_ssr.md
  .api-reports/api-report-testing.md
  .api-reports/api-report-testing_core.md
  .api-reports/api-report-utilities.md
  .api-reports/api-report.md
  .changeset/wet-jars-laugh.md
  .size-limits.json
  src/core/QueryManager.ts
Labels: auto-cleanup
