Repository apollographql/apollo-client, pull requests merged in 2024-12, with the labels that each got.

#12156 chore: Update readme for GraphQL spec compability
  README.md
Labels: auto-cleanup

#12165 Add documentation on using TypeScript with data masking
  .size-limits.json
  docs/source/data/fragments.mdx
  docs/source/development-testing/static-typing.md
Labels: 📝 documentation, auto-cleanup, 🎭 data-masking

#12171 Fix import extension
  .changeset/giant-pears-learn.md
  .size-limits.json
  src/masking/types.ts
Labels: auto-cleanup

#12163 Rewrite tests that use `subscribeAndCount` with `ObservableStream`
  .vscode/settings.json
  src/__tests__/client.ts
  src/__tests__/fetchMore.ts
  src/__tests__/mutationResults.ts
  src/cache/inmemory/__tests__/fragmentRegistry.ts
  src/cache/inmemory/__tests__/policies.ts
  src/core/__tests__/ObservableQuery.ts
  src/core/__tests__/QueryManager/index.ts
  src/core/__tests__/fetchPolicies.ts
  src/link/http/__tests__/responseIterator.ts
  src/link/http/__tests__/responseIteratorNoAsyncIterator.ts
  src/react/hooks/__tests__/useMutation.test.tsx
  src/testing/internal/ObservableStream.ts
  src/testing/matchers/index.d.ts
  src/testing/matchers/index.ts
  src/testing/matchers/toComplete.ts
  src/testing/matchers/toEmitAnything.ts
  src/testing/matchers/toEmitError.ts
  src/testing/matchers/toEmitMatchedValue.ts
  src/testing/matchers/toEmitNext.ts
  src/testing/matchers/toEmitValue.ts
  src/testing/matchers/toEmitValueStrict.ts
Labels: auto-cleanup

#12175 Bump React deps to v19 stable release
  .changeset/light-carpets-double.md
  .circleci/config.yml
  package-lock.json
  package.json
Labels: auto-cleanup

#12177 Make React 19 the default version for development
  .size-limits.json
  config/jest.config.js
  config/jest/react-dom-17-client.js
  package-lock.json
  package.json
  patches/@testing-library+react+16.1.0.patch
  src/react/components/__tests__/client/Query.test.tsx
  src/react/components/__tests__/ssr/getDataFromTree.test.tsx
  src/react/hoc/__tests__/queries/recomposeWithState.tsx
  src/react/hoc/__tests__/ssr/getDataFromTree.test.tsx
  src/react/hoc/mutation-hoc.tsx
  src/react/hooks/internal/useDeepMemo.ts
  src/react/hooks/useLazyQuery.ts
  src/testing/internal/rtl/renderHookAsync.tsx
Labels: auto-cleanup

#12174 Don't call `onError` if errors are thrown in `onCompleted`
  .changeset/fluffy-worms-fail.md
  .changeset/sharp-windows-switch.md
  .size-limits.json
  src/react/hooks/__tests__/useMutation.test.tsx
  src/react/hooks/useMutation.ts
Labels: auto-cleanup

#12178 docs: adjust screenshot size
  docs/source/development-testing/developer-tooling.md
Labels: auto-cleanup

#12205 add documentation for vscode devtools
  .semgrepignore
  docs/source/assets/devtools/vscode-panel.png
  docs/source/assets/devtools/vscode-setting.png
  docs/source/development-testing/developer-tooling.mdx
Labels: auto-cleanup

#12204 Ensure `MaybeMasked` doesn't unwrap if it contains `any`
  .api-reports/api-report-cache.api.md
  .api-reports/api-report-core.api.md
  .api-reports/api-report-masking.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/friendly-papayas-breathe.md
  .changeset/happy-weeks-buy.md
  .changeset/three-pandas-smash.md
  src/masking/__benches__/types.bench.ts
  src/masking/internal/types.ts
  src/utilities/index.ts
  src/utilities/types/RemoveIndexSignature.ts
Labels: auto-cleanup, 🎭 data-masking

#12214 prevent infinite recursion of ContainsFragmentsRefs type
  .api-reports/api-report-cache.api.md
  .api-reports/api-report-core.api.md
  .api-reports/api-report-masking.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/chilly-icons-shave.md
  src/masking/__benches__/types.bench.ts
  src/masking/internal/types.ts
Labels: auto-cleanup

#12182 Remove `itAsync` part 1
  src/__tests__/ApolloClient.ts
  src/__tests__/client.ts
  src/__tests__/local-state/general.ts
  src/__tests__/local-state/resolvers.ts
  src/cache/inmemory/__tests__/fragmentMatcher.ts
  src/cache/inmemory/__tests__/writeToStore.ts
  src/core/__tests__/QueryManager/links.ts
  src/core/__tests__/fetchPolicies.ts
  src/link/batch-http/__tests__/batchHttpLink.ts
  src/link/batch/__tests__/batchLink.ts
  src/link/context/__tests__/index.ts
  src/link/error/__tests__/index.ts
  src/link/http/__tests__/HttpLink.ts
  src/link/persisted-queries/__tests__/persisted-queries.test.ts
  src/link/ws/__tests__/webSocketLink.ts
  src/react/context/__tests__/ApolloConsumer.test.tsx
  src/react/hoc/__tests__/ssr/getDataFromTree.test.tsx
  src/react/hooks/__tests__/useMutation.test.tsx
  src/react/hooks/__tests__/useReactiveVar.test.tsx
  src/testing/internal/ObservableStream.ts
  src/testing/matchers/toEmitError.ts
  src/utilities/observables/__tests__/asyncMap.ts
Labels: auto-cleanup

#12217 docs: move redirects
  docs/source/_redirects
Labels: auto-cleanup

#12211 Remove the deprecated hoc and query components
  .changeset/hot-cycles-notice.md
  .changeset/young-turtles-explode.md
  .size-limit.cjs
  .size-limits.json
  config/entryPoints.js
  config/jest.config.js
  docs/source/api/react/components.mdx
  docs/source/api/react/hoc.mdx
  package-lock.json
  package.json
  src/__tests__/__snapshots__/exports.ts.snap
  src/__tests__/exports.ts
  src/link/persisted-queries/__tests__/react.test.tsx
  src/react/components/Mutation.tsx
  src/react/components/Query.tsx
  src/react/components/Subscription.tsx
  src/react/components/__tests__/client/Mutation.test.tsx
  src/react/components/__tests__/client/Query.test.tsx
  src/react/components/__tests__/client/Subscription.test.tsx
  src/react/components/__tests__/ssr/getDataFromTree.test.tsx
  src/react/components/__tests__/ssr/server.test.tsx
  src/react/components/index.ts
  src/react/components/types.ts
  src/react/hoc/__tests__/client-option.test.tsx
  src/react/hoc/__tests__/fragments.test.tsx
  src/react/hoc/__tests__/mutations/index.test.tsx
  src/react/hoc/__tests__/mutations/lifecycle.test.tsx
  src/react/hoc/__tests__/mutations/queries.test.tsx
  src/react/hoc/__tests__/mutations/recycled-queries.test.tsx
  src/react/hoc/__tests__/queries/__snapshots__/lifecycle.test.tsx.snap
  src/react/hoc/__tests__/queries/api.test.tsx
  src/react/hoc/__tests__/queries/errors.test.tsx
  src/react/hoc/__tests__/queries/index.test.tsx
  src/react/hoc/__tests__/queries/lifecycle.test.tsx
  src/react/hoc/__tests__/queries/loading.test.tsx
  src/react/hoc/__tests__/queries/observableQuery.test.tsx
  src/react/hoc/__tests__/queries/polling.test.tsx
  src/react/hoc/__tests__/queries/recomposeWithState.tsx
  src/react/hoc/__tests__/queries/reducer.test.tsx
  src/react/hoc/__tests__/queries/skip.test.tsx
  src/react/hoc/__tests__/queries/updateQuery.test.tsx
  src/react/hoc/__tests__/shared-operations.test.tsx
  src/react/hoc/__tests__/ssr/getDataFromTree.test.tsx
  src/react/hoc/__tests__/ssr/server.test.tsx
  src/react/hoc/__tests__/statics.test.tsx
  src/react/hoc/__tests__/subscriptions/subscriptions.test.tsx
  src/react/hoc/graphql.tsx
  src/react/hoc/hoc-utils.tsx
  src/react/hoc/index.ts
  src/react/hoc/mutation-hoc.tsx
  src/react/hoc/query-hoc.tsx
  src/react/hoc/subscription-hoc.tsx
  src/react/hoc/types.ts
  src/react/hoc/withApollo.tsx
  src/react/ssr/__tests__/getDataFromTree.test.tsx
  src/testing/internal/messageChannelPolyfill.ts
Labels: :fried_egg: breaking change, ⚛️ React-related

#12222 Drop support for React 16
  .changeset/clever-zebras-mate.md
  .circleci/config.yml
  package-lock.json
  package.json
Labels: :fried_egg: breaking change, ⚛️ React-related

#12220 link to the VSCode devtools from the react native page
  docs/source/integrations/react-native.md
Labels: auto-cleanup

#12223 Remove `subscribeAndCount` testing utility
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .changeset/shiny-carrots-invent.md
  src/__tests__/__snapshots__/exports.ts.snap
  src/testing/core/index.ts
  src/testing/core/subscribeAndCount.ts
Labels: :fried_egg: breaking change, 🔬 testing-utilities, auto-cleanup

#12224 Remove deprecated `partialRefetch` option
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/fluffy-shoes-applaud.md
  .size-limits.json
  src/__tests__/ApolloClient.ts
  src/core/ObservableQuery.ts
  src/core/__tests__/QueryManager/index.ts
  src/core/watchQueryOptions.ts
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/useQuery.ts
  src/react/types/types.documentation.ts
Labels: :fried_egg: breaking change, auto-cleanup

#12233 canary test adjustments
  .github/workflows/scheduled-test-canary.yml
Labels: auto-cleanup

#12238 Replace Discord with Discourse links
  .github/ISSUE_TEMPLATE/question-discussion.md
  .github/workflows/lock.yml
  README.md
Labels: auto-cleanup

#12239 docs: add meta descriptions to top-level pages
  docs/source/get-started.mdx
  docs/source/index.mdx
  docs/source/why-apollo.mdx
Labels: auto-cleanup
