Repository apollographql/apollo-client, pull requests merged in 2025-02, with the labels that each got.

#12318 Allow protocol errors to be retryable in `RetryLink`
  .changeset/thin-oranges-laugh.md
  src/link/retry/__tests__/retryLink.ts
  src/link/retry/retryLink.ts
Labels: auto-cleanup

#12066 Feature: `useSuspenseFragment`
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report.api.md
  .changeset/blue-comics-train.md
  .size-limits.json
  config/jest.config.js
  src/__tests__/__snapshots__/exports.ts.snap
  src/react/hooks/__tests__/useSuspenseFragment.test.tsx
  src/react/hooks/index.ts
  src/react/hooks/internal/wrapHook.ts
  src/react/hooks/useSuspenseFragment.ts
  src/react/internal/cache/FragmentReference.ts
  src/react/internal/cache/SuspenseCache.ts
  src/react/internal/cache/types.ts
Labels: auto-cleanup

#12342 Add `graphql-ws` `^6.0.3` as a valid `peerDependency`
  .changeset/lazy-clocks-sip.md
  package-lock.json
  package.json
Labels: auto-cleanup

#12341 `useReadQuery`/`useQueryRefHandlers`: Fix a "hook order" warning that might be emitted in React 19 dev mode.
  .changeset/large-timers-lay.md
  .size-limits.json
  src/react/hooks/useQueryRefHandlers.ts
  src/react/hooks/useReadQuery.ts
Labels: auto-cleanup

#12333 Deprecate `partial` and ensure its correctness. Fix type of `data` in `ApolloQueryResult`
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-testing_experimental.api.md
  .api-reports/api-report-testing_react.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/rich-kids-carry.md
  .changeset/rude-fans-study.md
  .size-limits.json
  src/__tests__/ApolloClient.ts
  src/__tests__/client.ts
  src/__tests__/dataMasking.ts
  src/__tests__/fetchMore.ts
  src/__tests__/local-state/general.ts
  src/__tests__/local-state/resolvers.ts
  src/__tests__/refetchQueries.ts
  src/__tests__/subscribeToMore.ts
  src/cache/inmemory/__tests__/fragmentRegistry.ts
  src/cache/inmemory/__tests__/policies.ts
  src/core/ObservableQuery.ts
  src/core/QueryManager.ts
  src/core/__tests__/ApolloClient/general.test.ts
  src/core/__tests__/ApolloClient/multiple-results.test.ts
  src/core/__tests__/ObservableQuery.ts
  src/core/__tests__/fetchPolicies.ts
  src/core/types.ts
  src/react/hooks/__tests__/useBackgroundQuery.test.tsx
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/__tests__/useMutation.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/react/hooks/useQuery.ts
  src/react/hooks/useReadQuery.ts
  src/react/hooks/useSuspenseQuery.ts
  src/react/internal/cache/QueryReference.ts
Labels: auto-cleanup

#12338 keep deferred inFlightLinkObservables until the response is finished
  .changeset/quiet-apricots-reply.md
  .size-limits.json
  src/config/jest/setup.ts
  src/core/QueryManager.ts
  src/core/__tests__/ApolloClient/general.test.ts
Labels: auto-cleanup

#12339 remove cci-based security scans
  .circleci/config.yml
  .size-limits.json
Labels: auto-cleanup

#12340 deprecate `use(Lazy)Query` `on(Error|Completed)` callbacks
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report.api.md
  .changeset/heavy-pumas-boil.md
  src/react/types/types.ts
Labels: auto-cleanup

#12353 Remove `addTypename` setting in testing docs
  docs/source/development-testing/testing.mdx
Labels: auto-cleanup

#12351 Fix emitted `fetchMore` result from `observableQuery` for no-cache queries
  .changeset/curvy-ads-matter.md
  .size-limits.json
  src/__tests__/fetchMore.ts
  src/core/ObservableQuery.ts
Labels: auto-cleanup

#12358 Fix failing `fetchMore` test added in 3.12.11
  .size-limits.json
  src/__tests__/fetchMore.ts
Labels: auto-cleanup

#12359 Remove `onCompleted` and `onError` callbacks from `useQuery` and `useLazyQuery`
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .changeset/tough-taxis-smoke.md
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/useQuery.ts
  src/react/types/types.documentation.ts
  src/react/types/types.ts
Labels: :fried_egg: breaking change, auto-cleanup

#12356 Add documentation for `useSuspenseFragment`
  docs/source/data/fragments.mdx
Labels: auto-cleanup

#12363 Require `variables` option in `useSuspenseFragment` when there are required variables
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report.api.md
  .size-limits.json
  src/react/hooks/__tests__/useSuspenseFragment.test.tsx
  src/react/hooks/useSuspenseFragment.ts
  src/react/query-preloader/createQueryPreloader.ts
  src/react/types/types.ts
Labels: 🐞 bug, auto-cleanup

#12369 `ObervableQuery.refetch`: don't refetch with `cache-and-network`, swich to `network-only` instead
  .changeset/fresh-spies-burn.md
  .size-limits.json
  src/__tests__/client.ts
  src/core/ObservableQuery.ts
  src/core/__tests__/ApolloClient/general.test.ts
  src/core/__tests__/ObservableQuery.ts
Labels: auto-cleanup

#12376 Remove deprecated `ignoreResults` option from `useMutation`
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_hooks.api.md
  .changeset/curvy-pianos-count.md
  src/react/hooks/useMutation.ts
  src/react/types/types.ts
Labels: :fried_egg: breaking change, auto-cleanup

#12375 Export `UseSuspenseFragmentOptions`
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report.api.md
  .changeset/shiny-sheep-behave.md
  .size-limits.json
  src/react/hooks/index.ts
Labels: auto-cleanup

#12374 Remove deprecated `UpdateQueryFn` type
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-testing_react.api.md
  .api-reports/api-report-utilities.api.md
  src/core/watchQueryOptions.ts
Labels: auto-cleanup

#12379 Remove `addTypename` option from `InMemoryCache` and `MockedProvider`
  .api-reports/api-report-cache.api.md
  .api-reports/api-report-core.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-testing_react.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/calm-frogs-remain.md
  .size-limits.json
  src/__tests__/ApolloClient.ts
  src/__tests__/client.ts
  src/__tests__/graphqlSubscriptions.ts
  src/__tests__/local-state/export.ts
  src/__tests__/local-state/resolvers.ts
  src/__tests__/mutationResults.ts
  src/__tests__/subscribeToMore.ts
  src/cache/inmemory/__tests__/__snapshots__/policies.ts.snap
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/__tests__/fragmentMatcher.ts
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/readFromStore.ts
  src/cache/inmemory/types.ts
  src/core/__tests__/ApolloClient/general.test.ts
  src/core/__tests__/ApolloClient/links.test.ts
  src/core/__tests__/ApolloClient/multiple-results.test.ts
  src/core/__tests__/ObservableQuery.ts
  src/core/__tests__/fetchPolicies.ts
  src/link/persisted-queries/__tests__/react.test.tsx
  src/react/hooks/__tests__/useSubscription.test.tsx
  src/react/ssr/__tests__/getDataFromTree.test.tsx
  src/react/ssr/__tests__/useQuery.test.tsx
  src/testing/core/mocking/__tests__/mockLink.ts
  src/testing/core/mocking/mockClient.ts
  src/testing/core/mocking/mockLink.ts
  src/testing/react/MockedProvider.tsx
  src/testing/react/__tests__/MockedProvider.test.tsx
  src/testing/react/__tests__/mockSubscriptionLink.test.tsx
Labels: :fried_egg: breaking change, auto-cleanup

#12382 Rework build process 2/?: add babel transform
  .size-limits.json
  config/babel.ts
  config/build.ts
  config/helpers.ts
  package-lock.json
  package.json
Labels: auto-cleanup
