Repository apollographql/apollo-client, pull requests merged in 2025-03, with the labels that each got.

#12381 Docs: simplify subscribeToMore example
  docs/source/data/subscriptions.mdx
Labels: 📝 documentation

#12404 Show `NaN` in `MockLink` debug messages for unmatched variables
  .api-reports/api-report-utilities.api.md
  .changeset/rich-adults-destroy.md
  src/testing/core/mocking/__tests__/__snapshots__/mockLink.ts.snap
  src/testing/core/mocking/__tests__/mockLink.ts
  src/testing/core/mocking/mockLink.ts
Labels: auto-cleanup

#12409 turn queryRef symbols into `Symbol.for` calls
  .changeset/grumpy-dogs-add.md
  .size-limits.json
  src/react/hooks/useLazyQuery.ts
  src/react/hooks/useQuery.ts
  src/react/internal/cache/QueryReference.ts
Labels: auto-cleanup

#12402 Use `{}` instead of `Object.create(null)`
  .changeset/itchy-roses-accept.md
  .size-limits.json
  docs/source/caching/cache-field-behavior.mdx
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/__tests__/entityStore.ts
  src/cache/inmemory/__tests__/writeToStore.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/fragmentRegistry.ts
  src/cache/inmemory/key-extractor.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/writeToStore.ts
  src/core/ApolloClient.ts
  src/core/QueryManager.ts
  src/link/persisted-queries/index.ts
  src/link/remove-typename/removeTypenameFromVariables.ts
  src/masking/maskDefinition.ts
  src/react/hooks/__tests__/useSubscription.test.tsx
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/react/hooks/useBackgroundQuery.ts
  src/react/hooks/useLazyQuery.ts
  src/react/hooks/useLoadableQuery.ts
  src/react/hooks/useQuery.ts
  src/react/hooks/useSubscription.ts
  src/react/hooks/useSuspenseQuery.ts
  src/react/internal/cache/SuspenseCache.ts
  src/react/query-preloader/createQueryPreloader.ts
  src/testing/core/mocking/mockLink.ts
  src/testing/matchers/toHaveSuspenseCacheEntryUsing.ts
  src/utilities/common/__tests__/maybeDeepFeeze.ts
  src/utilities/common/__tests__/mergeDeep.ts
  src/utilities/common/compact.ts
  src/utilities/graphql/DocumentTransform.ts
  src/utilities/graphql/getFromAST.ts
  src/utilities/types/NoInfer.ts
Labels: auto-cleanup

#12362 Fix `networkStatus` incorrectly reported as `ready` when using `errorPolicy: 'all'` with errors
  .changeset/khaki-cheetahs-lick.md
  .size-limits.json
  src/core/ObservableQuery.ts
  src/core/__tests__/ObservableQuery.ts
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
Labels: auto-cleanup

#12390 Minor refactor
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-testing_react.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .size-limits.json
  src/core/QueryManager.ts
Labels: auto-cleanup

#12396 Consolidate error properties
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-testing_experimental.api.md
  .api-reports/api-report-testing_react.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/calm-seals-relate.md
  .changeset/nice-donkeys-reflect.md
  .size-limits.json
  src/__tests__/client.ts
  src/__tests__/dataMasking.ts
  src/__tests__/local-state/general.ts
  src/core/ObservableQuery.ts
  src/core/QueryManager.ts
  src/core/__tests__/ApolloClient/general.test.ts
  src/core/__tests__/ApolloClient/multiple-results.test.ts
  src/core/__tests__/ObservableQuery.ts
  src/core/__tests__/equalByQuery.ts
  src/core/types.ts
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/useQuery.ts
  src/react/hooks/useReadQuery.ts
  src/react/hooks/useSubscription.ts
  src/react/hooks/useSuspenseQuery.ts
  src/react/internal/cache/QueryReference.ts
  src/react/query-preloader/__tests__/createQueryPreloader.test.tsx
  src/react/types/types.ts
  src/testing/matchers/toEqualQueryResult.ts
Labels: :fried_egg: breaking change, auto-cleanup

#12407 [Refactor] Move tracking of `networkStatus` into `ObservableQuery`
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-testing_react.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/forty-hairs-occur.md
  .size-limits.json
  src/__tests__/optimistic.ts
  src/core/ObservableQuery.ts
  src/core/QueryInfo.ts
  src/core/QueryManager.ts
  src/core/__tests__/ObservableQuery.ts
  src/core/__tests__/fetchPolicies.ts
  src/react/hooks/__tests__/useQuery.test.tsx
Labels: 👩‍🏭 refactor, auto-cleanup

#12367 Update `useLazyQuery` with planned breaking changes
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_hooks.api.md
  .changeset/empty-rabbits-move.md
  .changeset/light-dolphins-taste.md
  .changeset/lucky-hats-push.md
  .changeset/nice-waves-work.md
  .changeset/polite-bees-care.md
  .changeset/rich-eagles-cross.md
  .changeset/seven-foxes-melt.md
  .changeset/soft-mails-clean.md
  .changeset/sour-pillows-guess.md
  .changeset/strange-seahorses-impress.md
  .changeset/twenty-snakes-sort.md
  .size-limits.json
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/useLazyQuery.ts
  src/react/hooks/useQuery.ts
  src/react/ssr/__tests__/useLazyQuery.test.tsx
  src/react/types/types.ts
  src/testing/matchers/index.d.ts
  src/testing/matchers/index.ts
  src/testing/matchers/toEqualLazyQueryResult.ts
Labels: :fried_egg: breaking change

#12430 Remove `ObservableQuery.result`
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-testing_react.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/purple-lions-cough.md
  .changeset/tidy-squids-poke.md
  .size-limits.json
  src/__tests__/mutationResults.ts
  src/__tests__/optimistic.ts
  src/core/ObservableQuery.ts
  src/core/__tests__/ObservableQuery.ts
Labels: :fried_egg: breaking change

#12428 Remove the `urql` multipart subscriptions utilities
  .api-reports/api-report-utilities_subscriptions_urql.api.md
  .changeset/silly-knives-exist.md
  docs/source/data/subscriptions.mdx
  package.json
  src/__tests__/__snapshots__/exports.ts.snap
  src/__tests__/exports.ts
  src/utilities/subscriptions/relay/index.ts
  src/utilities/subscriptions/shared.ts
  src/utilities/subscriptions/urql/index.ts
Labels: auto-cleanup

#12388 Remove check for `WeakMap`, `WeakSet` and symbols
  .api-reports/api-report-utilities.api.md
  .changeset/smooth-pens-reply.md
  .size-limits.json
  src/__tests__/__snapshots__/exports.ts.snap
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/object-canon.ts
  src/cache/inmemory/readFromStore.ts
  src/core/QueryInfo.ts
  src/link/http/iterators/nodeStream.ts
  src/link/http/iterators/promise.ts
  src/link/http/iterators/reader.ts
  src/link/http/responseIterator.ts
  src/masking/maskFragment.ts
  src/masking/maskOperation.ts
  src/masking/utils.ts
  src/react/context/ApolloContext.ts
  src/react/internal/cache/SuspenseCache.ts
  src/utilities/common/canUse.ts
  src/utilities/graphql/DocumentTransform.ts
Labels: :fried_egg: breaking change

#12432 ObservableQuery - implement InteropObservable interface
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-testing_react.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/metal-needles-search.md
  .size-limits.json
  src/core/ObservableQuery.ts
  src/core/__tests__/ObservableQuery.ts
Labels: auto-cleanup

#12437 remove React Native polyfills
  .changeset/cool-bikes-shake.md
  .size-limits.json
  package.json
  src/cache/inmemory/fixPolyfills.native.ts
  src/cache/inmemory/fixPolyfills.ts
  src/cache/inmemory/inMemoryCache.ts
  src/utilities/common/maybeDeepFreeze.ts
Labels: auto-cleanup

#12436 some byte shaving for the prod build
  .api-reports/api-report-utilities_internal.api.md
  .size-limit.cjs
  .size-limits.json
  package.json
  src/__tests__/__snapshots__/exports.ts.snap
  src/cache/core/cache.ts
  src/cache/inmemory/inMemoryCache.ts
  src/core/ApolloClient.ts
  src/react/parser/index.ts
  src/utilities/common/canonicalStringify.ts
  src/utilities/graphql/print.ts
  src/utilities/internal/getMemoryInternals.ts
  src/utilities/internal/index.production.ts
  src/utilities/internal/index.ts
Labels: auto-cleanup

#12438 add a react-server entry point, remove `rehackt`
  .changeset/clean-sheep-hide.md
  .changeset/rare-houses-prove.md
  .size-limit.cjs
  .size-limits.json
  config/apiExtractor.ts
  config/listImports.ts
  config/package.json
  knip.config.js
  package-lock.json
  package.json
  src/__tests__/__snapshots__/exports.ts.snap
  src/__tests__/exports.ts
  src/link/batch/batching.ts
  src/react/context/ApolloConsumer.tsx
  src/react/context/ApolloContext.ts
  src/react/context/ApolloProvider.tsx
  src/react/hooks/internal/__tests__/useRenderGuard.test.tsx
  src/react/hooks/internal/__use.ts
  src/react/hooks/internal/useDeepMemo.ts
  src/react/hooks/internal/useIsomorphicLayoutEffect.ts
  src/react/hooks/internal/useRenderGuard.ts
  src/react/hooks/useApolloClient.ts
  src/react/hooks/useBackgroundQuery.ts
  src/react/hooks/useFragment.ts
  src/react/hooks/useLazyQuery.ts
  src/react/hooks/useLoadableQuery.ts
  src/react/hooks/useMutation.ts
  src/react/hooks/useQuery.ts
  src/react/hooks/useQueryRefHandlers.ts
  src/react/hooks/useReactiveVar.ts
  src/react/hooks/useReadQuery.ts
  src/react/hooks/useSubscription.ts
  src/react/hooks/useSuspenseFragment.ts
  src/react/hooks/useSuspenseQuery.ts
  src/react/hooks/useSyncExternalStore.ts
  src/react/index.react-server.ts
  src/react/ssr/getDataFromTree.ts
  src/testing/core/mocking/mockLink.ts
Labels: auto-cleanup

#12441 switch JS syntax to modern JS in a few places
  .api-reports/api-report-cache.api.md
  .api-reports/api-report-core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .size-limits.json
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/policies.ts
  src/cache/inmemory/writeToStore.ts
  src/react/hooks/useLazyQuery.ts
Labels: auto-cleanup

#12442 Remove object canonization
  .api-reports/api-report-cache.api.md
  .api-reports/api-report-core.api.md
  .api-reports/api-report-masking.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-testing_react.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/small-buttons-rhyme.md
  .changeset/tall-bikes-develop.md
  .size-limits.json
  docs/shared/useBackgroundQuery-options.mdx
  docs/shared/useFragment-options.mdx
  docs/source/api/cache/InMemoryCache.mdx
  docs/source/caching/garbage-collection.mdx
  scripts/memory/package-lock.json
  scripts/memory/tests.cts
  src/cache/core/types/Cache.ts
  src/cache/core/types/DataProxy.ts
  src/cache/inmemory/__tests__/__snapshots__/readFromStore.ts.snap
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/__tests__/entityStore.ts
  src/cache/inmemory/__tests__/object-canon.ts
  src/cache/inmemory/__tests__/optimistic.ts
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/__tests__/readFromStore.ts
  src/cache/inmemory/entityStore.ts
  src/cache/inmemory/helpers.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/object-canon.ts
  src/cache/inmemory/readFromStore.ts
  src/cache/inmemory/types.ts
  src/core/QueryInfo.ts
  src/core/__tests__/ApolloClient/general.test.ts
  src/core/__tests__/ObservableQuery.ts
  src/core/watchQueryOptions.ts
  src/react/hooks/__tests__/useBackgroundQuery.test.tsx
  src/react/hooks/__tests__/useFragment.test.tsx
  src/react/hooks/__tests__/useLoadableQuery.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/react/hooks/useLazyQuery.ts
  src/react/internal/cache/QueryReference.ts
  src/react/query-preloader/__tests__/createQueryPreloader.test.tsx
  src/react/query-preloader/createQueryPreloader.ts
  src/react/types/types.documentation.ts
  src/react/types/types.ts
Labels: auto-cleanup

#12454 [4.0] fix commonJS build
  .changeset/slimy-maps-press.md
  .size-limits.json
  config/compileTs.ts
Labels: auto-cleanup

#12446 Remove `defaultOptions` from `useQuery`
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .changeset/nervous-goats-allow.md
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/useQuery.ts
  src/react/types/types.ts
Labels: :fried_egg: breaking change

#12462 doc: add defer to sidebar
  docs/source/_sidebar.yaml
  docs/source/data/defer.mdx
Labels: auto-cleanup

#12461 Fix an issue where incorrect results are returned when changing variables and skipping
  .changeset/little-trainers-compare.md
  .size-limits.json
  src/core/QueryInfo.ts
  src/react/hooks/__tests__/useQuery.test.tsx
Labels: auto-cleanup

#12459 Move typename transform and fragment cache resets to resetResultCache
  .changeset/shy-dragons-tease.md
  .size-limits.json
  src/cache/inmemory/inMemoryCache.ts
Labels: auto-cleanup

#12457 Unify error behavior for queries
  .changeset/four-ghosts-watch.md
  .size-limits.json
  src/__tests__/client.ts
  src/core/QueryManager.ts
  src/core/__tests__/ApolloClient/general.test.ts
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/react/internal/cache/QueryReference.ts
  src/react/query-preloader/__tests__/createQueryPreloader.test.tsx
Labels: :fried_egg: breaking change, auto-cleanup

#12465 Colocate and flatten hook types
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-testing_react.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/khaki-spies-work.md
  .changeset/odd-lemons-relax.md
  .size-limits.json
  src/core/watchQueryOptions.ts
  src/react/hooks/__tests__/useBackgroundQuery.test.tsx
  src/react/hooks/__tests__/useFragment.test.tsx
  src/react/hooks/__tests__/useLoadableQuery.test.tsx
  src/react/hooks/__tests__/useMutation.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/__tests__/useQueryRefHandlers.test.tsx
  src/react/hooks/__tests__/useSubscription.test.tsx
  src/react/hooks/__tests__/useSuspenseFragment.test.tsx
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/react/hooks/index.ts
  src/react/hooks/useBackgroundQuery.ts
  src/react/hooks/useFragment.ts
  src/react/hooks/useLazyQuery.ts
  src/react/hooks/useLoadableQuery.ts
  src/react/hooks/useMutation.ts
  src/react/hooks/useQuery.ts
  src/react/hooks/useQueryRefHandlers.ts
  src/react/hooks/useReadQuery.ts
  src/react/hooks/useSubscription.ts
  src/react/hooks/useSuspenseFragment.ts
  src/react/hooks/useSuspenseQuery.ts
  src/react/index.ts
  src/react/internal/index.ts
  src/react/internal/types.ts
  src/react/query-preloader/__tests__/createQueryPreloader.test.tsx
  src/react/query-preloader/createQueryPreloader.ts
  src/react/ssr/RenderPromises.ts
  src/react/types/deprecated.ts
  src/react/types/types.ts
  src/testing/matchers/index.d.ts
  src/testing/matchers/toEqualLazyQueryResult.ts
  src/testing/matchers/toEqualQueryResult.ts
  src/testing/react/__tests__/MockedProvider.test.tsx
Labels: auto-cleanup

#12470 replace `client.disableNetworkFetches` with `queryManager.prioritizeCacheValues`
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-testing_react.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/funny-jeans-invent.md
  .size-limits.json
  config/apiExtractor.ts
  src/__tests__/ApolloClient.ts
  src/core/ApolloClient.ts
  src/core/ObservableQuery.ts
  src/core/QueryManager.ts
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/useQuery.ts
Labels: auto-cleanup

#12474 Refactor `useMutation` tests to use full result matchers and snapshot streams
  src/core/ApolloClient.ts
  src/react/hooks/__tests__/useMutation.test.tsx
  src/testing/matchers/index.d.ts
  src/testing/matchers/index.ts
  src/testing/matchers/toEqualStrictTyped.ts
Labels: 👩‍🏭 refactor

#12487 Split out SSR-specific code from `useQuery` hook, remove `RenderPromises`
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .changeset/loud-cows-raise.md
  .changeset/thick-books-grin.md
  config/jest.config.ts
  config/listImports.ts
  scripts/memory/tests.cts
  src/__tests__/__snapshots__/exports.ts.snap
  src/react/context/ApolloContext.ts
  src/react/hooks/internal/wrapHook.ts
  src/react/hooks/useQuery.ts
  src/react/internal/index.ts
  src/react/ssr/RenderPromises.ts
  src/react/ssr/__tests__/useQuery.test.tsx
  src/react/ssr/getDataFromTree.ts
  src/react/ssr/getDataFromTree.tsx
  src/react/ssr/index.ts
  src/react/ssr/useSSRQuery.ts
Labels: auto-cleanup

#12489 reduce size of api explorer reports
  .api-reports/api-report-cache.api.md
  .api-reports/api-report-core.api.md
  .api-reports/api-report-errors.api.md
  .api-reports/api-report-link_batch-http.api.md
  .api-reports/api-report-link_batch.api.md
  .api-reports/api-report-link_context.api.md
  .api-reports/api-report-link_core.api.md
  .api-reports/api-report-link_error.api.md
  .api-reports/api-report-link_http.api.md
  .api-reports/api-report-link_persisted-queries.api.md
  .api-reports/api-report-link_remove-typename.api.md
  .api-reports/api-report-link_retry.api.md
  .api-reports/api-report-link_schema.api.md
  .api-reports/api-report-link_subscriptions.api.md
  .api-reports/api-report-link_utils.api.md
  .api-reports/api-report-link_ws.api.md
  .api-reports/api-report-masking.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-testing_experimental.api.md
  .api-reports/api-report-testing_react.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report-utilities_subscriptions_relay.api.md
  config/apiExtractor.ts
  patches/@microsoft+api-extractor+7.49.1.patch
Labels: auto-cleanup

#12494 Refactor away `createMakeWatchQueryOptions`
  src/react/hooks/useQuery.ts
Labels: auto-cleanup

#12495 Refactor away `getObsQueryOptions`
  src/react/hooks/useQuery.ts
  src/testing/react/__tests__/__snapshots__/MockedProvider.test.tsx.snap
Labels: auto-cleanup

#12496 Refactor `useQuery`: Combine hooks
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_hooks.api.md
  package-lock.json
  package.json
  src/react/hooks/useQuery.ts
Labels: auto-cleanup

#12475 Unify error behavior of `client.mutate` and update its type
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report.api.md
  .changeset/grumpy-vans-type.md
  .changeset/little-spoons-kick.md
  .changeset/many-buses-allow.md
  .changeset/poor-eels-punch.md
  .changeset/tough-rockets-allow.md
  .size-limits.json
  src/__tests__/ApolloClient.ts
  src/__tests__/client.ts
  src/__tests__/dataMasking.ts
  src/__tests__/mutationResults.ts
  src/core/ApolloClient.ts
  src/core/QueryManager.ts
  src/core/__tests__/ApolloClient/general.test.ts
  src/core/types.ts
  src/react/hooks/__tests__/useMutation.test.tsx
  src/react/hooks/__tests__/useQuery.test.tsx
  src/react/hooks/useMutation.ts
  src/react/types/types.documentation.ts
Labels: auto-cleanup

#12476 Unify subscription error behavior and update emitted type
  .api-reports/api-report-core.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report.api.md
  .changeset/forty-shrimps-fry.md
  .changeset/real-teachers-peel.md
  .changeset/tricky-tables-shave.md
  .changeset/warm-ties-sit.md
  .size-limits.json
  src/__tests__/client.ts
  src/__tests__/dataMasking.ts
  src/__tests__/graphqlSubscriptions.ts
  src/core/ApolloClient.ts
  src/core/ObservableQuery.ts
  src/core/QueryManager.ts
  src/core/types.ts
  src/react/hooks/__tests__/useSubscription.test.tsx
  src/react/hooks/useSubscription.ts
  src/testing/matchers/index.d.ts
  src/testing/matchers/index.ts
  src/testing/matchers/toEmitStrictTyped.ts
  src/testing/matchers/toEqualStrictTyped.ts
  src/testing/matchers/utils/getSerializableProperties.ts
Labels: :fried_egg: breaking change

#12478 Remove deprecated `onSubscriptionData`, `onSubscriptionComplete` callbacks and returned `variables` from `useSubscripton`
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_hooks.api.md
  .changeset/eleven-kangaroos-jump.md
  .changeset/slimy-chicken-melt.md
  .size-limits.json
  src/react/hooks/__tests__/useSubscription.test.tsx
  src/react/hooks/useSubscription.ts
  src/react/types/deprecated.ts
  src/react/types/types.documentation.ts
Labels: :fried_egg: breaking change, auto-cleanup
