Repository apollographql/apollo-client, pull requests merged in 2025-01, with the labels that each got.

#12234 fix timing problems in tests introduced by latest React canary
  .size-limits.json
  src/react/hooks/__tests__/useSubscription.test.tsx
Labels: auto-cleanup

#12252 Unmask types with explicit `mode: "unmask"` and default to leave the type alone
  .api-reports/api-report-cache.api.md
  .api-reports/api-report-core.api.md
  .api-reports/api-report-masking.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/cool-pants-smash.md
  docs/source/data/fragments.mdx
  src/masking/__benches__/types.bench.ts
  src/masking/types.ts
  src/react/hooks/__tests__/useBackgroundQuery.test.tsx
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/react/hooks/__tests__/useSubscription.test.tsx
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
Labels: auto-cleanup, 🎭 data-masking

#12207 Remove `itAsync` part 2
  .size-limits.json
  src/__tests__/local-state/export.ts
  src/__tests__/local-state/subscriptions.ts
  src/__tests__/optimistic.ts
  src/__tests__/subscribeToMore.ts
  src/core/__tests__/QueryManager/index.ts
  src/core/__tests__/QueryManager/multiple-results.ts
  src/core/__tests__/QueryManager/recycler.ts
  src/link/core/__tests__/ApolloLink.ts
  src/link/http/__tests__/parseAndCheckHttpResponse.ts
  src/testing/core/observableToPromise.ts
  src/testing/react/__tests__/MockedProvider.test.tsx
Labels: auto-cleanup

#12210 Remove `itAsync` from remaining relevant tests
  src/__tests__/graphqlSubscriptions.ts
  src/__tests__/optimistic.ts
  src/__tests__/refetchQueries.ts
  src/link/schema/__tests__/schemaLink.ts
  src/link/utils/__tests__/toPromise.ts
  src/testing/internal/ObservableStream.ts
  src/utilities/observables/__tests__/Concast.ts
Labels: auto-cleanup

#12262 Remove `itAsync` test function from `@apollo/client/testing`
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .changeset/itchy-drinks-refuse.md
  src/__tests__/__snapshots__/exports.ts.snap
  src/testing/core/index.ts
  src/testing/core/itAsync.ts
Labels: :fried_egg: breaking change, auto-cleanup

#12267 Leave `TData` alone in `Unmasked` if it does not contain fragment refs
  .api-reports/api-report-cache.api.md
  .api-reports/api-report-core.api.md
  .api-reports/api-report-masking.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/beige-eggs-nail.md
  src/masking/__benches__/types.bench.ts
  src/masking/types.ts
Labels: auto-cleanup

#12270 Handle tagged/branded primitive types when used with `Unmasked`
  .api-reports/api-report-cache.api.md
  .api-reports/api-report-core.api.md
  .api-reports/api-report-masking.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/tiny-ants-bow.md
  src/masking/__benches__/types.bench.ts
  src/masking/internal/types.ts
  src/utilities/index.ts
Labels: ⛑ TypeScript

#12260 Update `useLazyQuery` tests for robustness
  src/react/hooks/__tests__/useLazyQuery.test.tsx
  src/testing/matchers/index.d.ts
  src/testing/matchers/index.ts
  src/testing/matchers/toEqualQueryResult.ts
Labels: auto-cleanup

#12279 docs: set Codesandbox button width
  docs/source/development-testing/schema-driven-testing.mdx
  docs/source/development-testing/testing.mdx
Labels: auto-cleanup

#12286 manually update various tooling-related dependencies
  .api-reports/api-report-link_persisted-queries.api.md
  .eslintrc
  .size-limits.json
  eslint-local-rules/testSetup.ts
  eslint.config.mjs
  package-lock.json
  package.json
  patches/eslint-plugin-react-hooks+4.6.2.patch
  patches/eslint-plugin-testing-library+7.1.1.patch
  renovate.json
  scripts/memory/package.json
  src/cache/index.ts
  src/core/index.ts
  src/errors/index.ts
  src/link/core/index.ts
  src/react/components/__tests__/client/Mutation.test.tsx
  src/react/components/index.ts
  src/react/hoc/index.ts
  src/react/hooks/__tests__/useSuspenseQuery.test.tsx
  src/react/hooks/internal/useDeepMemo.ts
  src/react/hooks/useBackgroundQuery.ts
  src/react/hooks/useFragment.ts
  src/react/hooks/useMutation.ts
  src/react/hooks/useQuery.ts
  src/react/hooks/useQueryRefHandlers.ts
  src/react/hooks/useReadQuery.ts
  src/react/hooks/useSubscription.ts
  src/react/hooks/useSuspenseQuery.ts
  src/react/index.ts
  src/utilities/globals/__tests__/invariantWrappers.test.ts
  src/utilities/index.ts
Labels: auto-cleanup

#12281 Make protocol errors available in the error link
  .api-reports/api-report-core.api.md
  .api-reports/api-report-link_core.api.md
  .api-reports/api-report-link_error.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/giant-peas-lie.md
  .changeset/mighty-shoes-clap.md
  docs/source/api/link/apollo-link-error.md
  package-lock.json
  package.json
  src/link/core/types.ts
  src/link/error/__tests__/index.ts
  src/link/error/index.ts
  src/testing/internal/incremental.ts
  src/testing/internal/index.ts
Labels: auto-cleanup

#12292 Remove unused dependency `response-iterator`
  .changeset/lemon-singers-pay.md
  package-lock.json
  package.json
Labels: auto-cleanup

#12287 Ensure `watchFragment` used with variables does not crash when the cache updates #12284
  .changeset/ten-rules-stare.md
  .size-limits.json
  src/__tests__/ApolloClient.ts
  src/cache/core/cache.ts
Labels: auto-cleanup

#12303 Minor tweaks to `diffAgainstStore` tests
  src/cache/inmemory/__tests__/diffAgainstStore.ts
Labels: auto-cleanup

#12304 Don't throw on missing results with `cache.diff` and other changes
  .api-reports/api-report-cache.api.md
  .api-reports/api-report-core.api.md
  .api-reports/api-report-masking.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-testing_react.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/moody-lobsters-listen.md
  .changeset/tall-cups-suffer.md
  .changeset/yellow-cats-judge.md
  .size-limits.json
  src/__tests__/client.ts
  src/__tests__/dataMasking.ts
  src/__tests__/optimistic.ts
  src/__tests__/refetchQueries.ts
  src/cache/core/__tests__/cache.ts
  src/cache/core/cache.ts
  src/cache/core/types/DataProxy.ts
  src/cache/inmemory/__tests__/cache.ts
  src/cache/inmemory/__tests__/diffAgainstStore.ts
  src/cache/inmemory/__tests__/entityStore.ts
  src/cache/inmemory/__tests__/policies.ts
  src/cache/inmemory/__tests__/readFromStore.ts
  src/cache/inmemory/__tests__/roundtrip.ts
  src/cache/inmemory/inMemoryCache.ts
  src/cache/inmemory/readFromStore.ts
  src/config/jest/areMissingFieldErrorsEqual.ts
  src/config/jest/setup.ts
  src/core/ObservableQuery.ts
  src/core/QueryInfo.ts
  src/core/QueryManager.ts
  src/core/__tests__/ObservableQuery.ts
  src/core/__tests__/QueryManager/index.ts
  src/core/__tests__/fetchPolicies.ts
  src/react/hooks/useFragment.ts
Labels: :fried_egg: breaking change, auto-cleanup

#12314 some more knip reportings
  knip.config.js
  src/testing/internal/renderHelpers.tsx
  src/testing/react/MockedProvider.tsx
Labels: auto-cleanup

#12321 Fix type of `extensions` in `protocolErrors`
  .api-reports/api-report-core.api.md
  .api-reports/api-report-errors.api.md
  .api-reports/api-report-link_error.api.md
  .api-reports/api-report-react.api.md
  .api-reports/api-report-react_components.api.md
  .api-reports/api-report-react_context.api.md
  .api-reports/api-report-react_hoc.api.md
  .api-reports/api-report-react_hooks.api.md
  .api-reports/api-report-react_internal.api.md
  .api-reports/api-report-react_ssr.api.md
  .api-reports/api-report-testing.api.md
  .api-reports/api-report-testing_core.api.md
  .api-reports/api-report-utilities.api.md
  .api-reports/api-report.api.md
  .changeset/curvy-seahorses-walk.md
  src/__tests__/__snapshots__/graphqlSubscriptions.ts.snap
  src/__tests__/graphqlSubscriptions.ts
  src/errors/__tests__/ApolloError.ts
  src/errors/index.ts
  src/link/error/index.ts
Labels: ⛑ TypeScript, auto-cleanup

#12326 Move remaining `__tests__/QueryManager` tests to `ApolloClient` and test with `ApolloClient` instance
  src/core/__tests__/ApolloClient/links.test.ts
  src/core/__tests__/ApolloClient/multiple-results.test.ts
Labels: 👩‍🏭 refactor

#12327 Refactor remaining tests that instantiate `QueryManager` directly and remove `mockQueryManager` helper
  src/__tests__/__snapshots__/graphqlSubscriptions.ts.snap
  src/__tests__/graphqlSubscriptions.ts
  src/__tests__/local-state/resolvers.ts
  src/core/__tests__/ObservableQuery.ts
  src/testing/core/mocking/mockQueryManager.ts
  src/testing/core/mocking/mockWatchQuery.ts
  src/testing/matchers/index.d.ts
  src/testing/matchers/index.ts
  src/testing/matchers/toEmitFetchResult.ts
Labels: 👩‍🏭 refactor
